/**
 * procgenDocs/glossary — **THE GLOSSARY IS DATA, SO IT CAN BE GATED WITHOUT A
 * BROWSER.** (PROCGEN DOCS slice P2, D5.)
 *
 * ⛓ `check-procgen-demos.mjs` is the expensive gate: it LOADS `glossary.html`
 * and asserts the page renders what this module holds. This file is the cheap
 * one — the entry shape, the cross-references, and the half `assertGlossary()`
 * cannot answer because it runs in a browser too: **does the tracked doc a
 * `where` names actually EXIST on disk, and does its `#fragment` name a real
 * heading?**
 *
 * ⛔⛔ **THE SLUG RULE IS NOT INVENTED HERE, AND IT IS NOT AN ECHO** (trap
 * 367). A test that slugified with the same helper the DATA was generated by
 * would pass with a wrong rule and ship 140 broken anchors. The rule below is
 * pinned to SIX links other people already wrote in the tracked docs, asserted
 * in `describe('the GitHub heading-slug rule')` before it is used on anything:
 *
 *     `Instant — a pump, not a skip`  →  `instant--a-pump-not-a-skip`
 *
 * — the em dash is DROPPED and each space around it becomes a hyphen, which is
 * exactly what a first attempt (keeping every Unicode dash) got wrong.
 *
 * ⛓ P4 MOVED THE RULE ITSELF to `ghSlug.js` so the docs PAGE renders the same
 * anchors this file checks. The pin did not move: these six pairs are the
 * external evidence, and they now gate the shared function.
 *
 * ⛔ And a fragment whose heading begins with a stripped symbol (`## ⚖ What a
 * URL is FOR…`) would start with a hyphen, where NO tracked link evidences
 * what GitHub answers. Those are refused by name below rather than guessed at.
 */

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { DEMOS } from './demos.js';
import { ghSlug } from './ghSlug.js';
import {
    AREAS, AREA_IDS, DOC_ROOT, GLOSSARY_PAGE, PAGES_BASE, TERMS,
    assertGlossary, hrefFor, oneLinerFor, termById, termsInArea,
} from './glossary.js';

/** ⛓ Repo root from this file: `frontend/modules/procgenDocs/` → up three. */
const ROOT = new URL('../../../', import.meta.url).pathname;

/** ⛓⛓ THE RULE NOW LIVES IN `ghSlug.js`, BECAUSE A PAGE NEEDS IT TOO (P4,
 *  D2): `docs.html` renders these same documents and has to spell `#a-
 *  fragment` the way this file says it is spelled. ⛔ The six-link pin below
 *  STAYS HERE and is the reason to believe the rule — it is evidence written
 *  by people outside these slices, and sharing a function with the page is
 *  only safe while that pin is external. */

/** Every `##`–`####` heading of a doc, as its slug. ⛔ Fenced blocks skipped:
 *  a `# comment` inside one is not a heading. */
function headingSlugs(absPath) {
    const out = new Set();
    let fenced = false;
    for (const line of readFileSync(absPath, 'utf8').split('\n')) {
        if (line.trimStart().startsWith('```')) { fenced = !fenced; continue; }
        if (fenced) continue;
        const m = /^(#{2,4})\s+(.*)$/.exec(line);
        if (m) out.add(ghSlug(m[2]));
    }
    return out;
}

describe('the GitHub heading-slug rule — pinned to links nobody in this slice wrote', () => {
    /** ⛔ These six pairs are heading → fragment as they appear in the TRACKED
     *  docs today, written by earlier slices. They are the only reason to
     *  believe the rule; without them the disk checks below are an echo. */
    it.each([
        ['Instant — a pump, not a skip', 'instant--a-pump-not-a-skip'],
        ['`requiresLoopMode` — loop-game substrates', 'requiresloopmode--loop-game-substrates'],
        ['Managed-mode zone invariants', 'managed-mode-zone-invariants'],
        ['The bot flow (M6)', 'the-bot-flow-m6'],
        ['`autoRestartQueue` governs the resets loops owns', 'autorestartqueue-governs-the-resets-loops-owns'],
        ['A frozen substrate cannot generate the reset that unfreezes it',
            'a-frozen-substrate-cannot-generate-the-reset-that-unfreezes-it'],
    ])('%s', (heading, want) => {
        expect(ghSlug(heading)).toBe(want);
    });

    it('⛔ DROPS a Unicode dash rather than keeping it — the first rule kept it', () => {
        expect(ghSlug('Pass 1 — the skeleton, in draw order')).toBe('pass-1--the-skeleton-in-draw-order');
        expect(ghSlug('M4–M6')).toBe('m4m6');
    });
});

describe('the glossary as data', () => {
    it('is FROZEN, entries and all — a reader cannot edit the source of truth', () => {
        expect(Object.isFrozen(TERMS)).toBe(true);
        expect(Object.isFrozen(AREAS)).toBe(true);
        for (const e of TERMS) {
            expect(Object.isFrozen(e)).toBe(true);
            expect(Object.isFrozen(e.where)).toBe(true);
            expect(Object.isFrozen(e.seeAlso)).toBe(true);
        }
    });

    it('⛓⛓ passes its OWN shape gate — ids, areas, seeAlso, where, one sentence', () => {
        expect(assertGlossary()).toEqual([]);
    });

    /** ⚖ D5's band. ⛓ The count is NAMED rather than merely bounded: a slice
     *  that adds a term should have to look at this line. */
    /**
     * ⛓⛓ **THE CEILING MOVED, 140 → 149** (⚖ user, via the PROCGEN DOCS · P5
     * charge). P2 chose 140 to land inside D5's 80–140 band and named what it
     * had to drop to get there. P5 spends the nine the charge authorised: the
     * SEVEN URL parameters the generated URL-grammar table reported as having
     * no glossary term at all (`?attackhold=`, `?tick=`, `?speed=`, `?shot=`,
     * `?level=`, `?name=`, `?budgetms=`) and the TWO §18.8 named as first back
     * if the ceiling ever lifted — `component` and `a wall backend`.
     * ⛔ The upper bound is now 149 and it is still a BOUND: the next slice that
     * wants an entry comes here and says whose licence it is spending.
     *
     * ⛓⛓⛓ **151 — PROCGEN ELEMENTS arc 5, slice 1 SPENDS TWO**, and says whose
     * licence: ⚖ the user's arc-5 **ruling 1** (the room size is configurable,
     * max 60x60) and **ruling 2** (the sparse SHELL format and its closure law).
     * Each creates a URL parameter — `?width=`/`?height=` and `?fill=` — and the
     * generated URL-grammar table REFUSES a parameter with no glossary term,
     * which is the very finding that moved this ceiling to 149. ⛔ Two entries
     * for three parameters: `room-size` covers both axes, because a room is one
     * setting.
     */
    it('holds 151 entries — 149 + arc-5 slice 1\'s two, and every one is filed', () => {
        expect(TERMS).toHaveLength(151);
        expect(TERMS.length).toBeGreaterThanOrEqual(80);
        expect(TERMS.length).toBeLessThanOrEqual(151);
        expect(TERMS.filter((e) => !AREA_IDS.includes(e.area))).toHaveLength(0);
    });

    it('declares 8 areas and leaves none of them empty', () => {
        expect(AREAS).toHaveLength(8);
        for (const a of AREAS) {
            expect(termsInArea(a.id).length).toBeGreaterThan(0);
            expect(a.title.length).toBeGreaterThan(0);
            expect(a.blurb.length).toBeGreaterThan(0);
        }
    });

    it('⛔ keeps `plain` free of the jargon it exists to remove', () => {
        /** A `plain` sentence is for someone who has read nothing. Backticks,
         *  file paths and the arc's own ⛓/⛔/⚖ marks all belong in `detail`. */
        for (const e of TERMS) {
            expect(e.plain, e.id).not.toMatch(/[`⛓⛔⚖⚠]/);
            expect(e.plain, e.id).not.toMatch(/\.(js|mjs|md|html)\b/);
            expect(e.plain, e.id).not.toMatch(/§/);
        }
    });

    it('gives every entry at least one place it lives, and no HTML anywhere', () => {
        for (const e of TERMS) {
            expect(e.where.length, e.id).toBeGreaterThan(0);
            /** ⛓ CODE SPANS COME OUT FIRST. The prose legitimately writes
             *  `?skeleton=<kind>` inside backticks, and `inline()` escapes
             *  everything before it un-escapes its six forms — so the thing
             *  worth refusing is HAND-WRITTEN markup, not a placeholder. */
            for (const p of [e.plain, e.detail]) {
                expect(String(p).replace(/`[^`]*`/g, ''), e.id)
                    .not.toMatch(/<\/?[a-zA-Z][^>]*>/);
            }
        }
    });
});

describe('every `where` really is somewhere — measured against the disk', () => {
    const docWheres = TERMS.flatMap((e) => e.where.filter((w) => w.doc).map((w) => [e.id, w]));
    const codeWheres = TERMS.flatMap((e) => e.where.filter((w) => w.code).map((w) => [e.id, w]));

    it('names at least 30 distinct doc targets and 4 code targets', () => {
        expect(new Set(docWheres.map(([, w]) => w.doc)).size).toBeGreaterThanOrEqual(30);
        expect(new Set(codeWheres.map(([, w]) => w.code)).size).toBeGreaterThanOrEqual(4);
    });

    it.each(docWheres)('%s → %o', (id, w) => {
        const [path, fragment] = String(w.doc).split('#');
        expect(path.startsWith(DOC_ROOT), `${id}: ${path}`).toBe(true);
        expect(existsSync(join(ROOT, path)), `${id}: ${path} does not exist`).toBe(true);
        if (!fragment) return;
        /** ⛔ REFUSED BY NAME: a heading beginning with a stripped symbol
         *  slugifies to a leading hyphen, and no tracked link evidences what
         *  GitHub answers there — so this module does not ship one. */
        expect(fragment.startsWith('-'), `${id}: ${w.doc} targets a symbol-led heading`)
            .toBe(false);
        const slugs = headingSlugs(join(ROOT, path));
        expect([...slugs].includes(fragment),
            `${id}: ${path} has no heading slugging to #${fragment}`).toBe(true);
    });

    it.each(codeWheres)('%s → %o', (id, w) => {
        expect(existsSync(join(ROOT, w.code)), `${id}: ${w.code} does not exist`).toBe(true);
    });

    it('⛔ points at NO doc outside the tracked procgen directory, and never at NewDocs', () => {
        const tracked = new Set(readdirSync(join(ROOT, DOC_ROOT)).filter((n) => n.endsWith('.md')));
        for (const [id, w] of docWheres) {
            const file = String(w.doc).split('#')[0].slice(DOC_ROOT.length);
            expect(tracked.has(file), `${id}: ${file}`).toBe(true);
        }
        for (const e of TERMS) {
            expect(JSON.stringify(e.where)).not.toContain('NewDocs');
        }
    });
});

describe('the readers', () => {
    it('termById resolves every id and answers null for anything else', () => {
        for (const e of TERMS) expect(termById(e.id)).toBe(e);
        expect(termById('no-such-term')).toBeNull();
    });

    it('⛓ oneLinerFor IS the plain sentence — it is what a lab page hangs on a title=', () => {
        expect(oneLinerFor('door-law')).toBe(termById('door-law').plain);
        /** ⛔ An unknown id gives '', not a throw: a `title=""` is a missing
         *  tooltip, a thrown error is a broken page. */
        expect(oneLinerFor('no-such-term')).toBe('');
    });

    it('⛓⛓ hrefFor spells the Pages mapping through demos.js and STRIPS /frontend', () => {
        expect(hrefFor('door-law')).toBe('glossary.html#door-law');
        expect(hrefFor('door-law', { base: PAGES_BASE })).toBe(
            'https://peerinfinity.github.io/Archipelago-CC/modules/procgenDocs/glossary.html#door-law');
        expect(hrefFor('door-law', { base: 'http://example.test/' }))
            .toBe('http://example.test/modules/procgenDocs/glossary.html#door-law');
        expect(GLOSSARY_PAGE).toBe('/frontend/modules/procgenDocs/glossary.html');
    });
});

describe('the demo catalogue names terms this glossary defines', () => {
    const withTerms = DEMOS.filter((e) => e.terms.length);

    it('⛓ every catalogue entry now names some, and the field is no longer empty', () => {
        expect(withTerms).toHaveLength(DEMOS.length);
        for (const e of DEMOS) {
            expect(e.terms.length, e.id).toBeGreaterThanOrEqual(4);
            expect(e.terms.length, e.id).toBeLessThanOrEqual(14);
            expect(Object.isFrozen(e.terms)).toBe(true);
        }
    });

    it.each(DEMOS.map((e) => [e.id, e]))('%s — every slug RESOLVES', (_id, e) => {
        for (const slug of e.terms) {
            expect(termById(slug), `${e.id} names ${slug}`).not.toBeNull();
        }
        expect(new Set(e.terms).size, `${e.id} repeats a term`).toBe(e.terms.length);
    });

    it('⛓ the catalogue reaches every AREA of the glossary — not just level-gen', () => {
        const areas = new Set(DEMOS.flatMap((e) => e.terms.map((s) => termById(s).area)));
        expect(areas.size).toBeGreaterThanOrEqual(4);
    });
});
