"""
Game options for Saving Princess WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, DefaultOnToggle, Range, StartInventoryPool, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True


class UseCanonicalOptions(Toggle):
    """Use canonical options for seed 1.

    When enabled and generating seed 1, options will be loaded from the
    _worldgen_settings.json file to reproduce the exact original seed.
    This ensures deterministic output matching the original world export.
    """
    display_name = "Use Canonical Options"
    default = True

class AceWeaponUpgrade(Choice):
    """Option for Ace Weapon Upgrade."""
    display_name = "Ace Weapon Upgrade"
    option_never_upgraded = 0
    option_always_upgraded = 1
    option_vanilla = 2
    default = 1

class CliffWeaponUpgrade(Choice):
    """Option for Cliff Weapon Upgrade."""
    display_name = "Cliff Weapon Upgrade"
    option_never_upgraded = 0
    option_always_upgraded = 1
    option_vanilla = 2
    default = 1

class DeathLink(Toggle):
    """Option for Death Link."""
    display_name = "Death Link"

class ExpandedPool(DefaultOnToggle):
    """Option for Expanded Item Pool."""
    display_name = "Expanded Item Pool"

class IframesDuration(Range):
    """Option for IFrame Duration %."""
    display_name = "IFrame Duration %"
    range_start = 0
    range_end = 400
    default = 100

class InstantSaving(DefaultOnToggle):
    """Option for Instant Saving."""
    display_name = "Instant Saving"

class MusicShuffle(Toggle):
    """Option for Music Shuffle."""
    display_name = "Music Shuffle"

class ShakeIntensity(Range):
    """Option for Screen Shake Intensity %."""
    display_name = "Screen Shake Intensity %"
    range_start = 0
    range_end = 100
    default = 50

class SprintAvailability(Choice):
    """Option for Sprint Availability."""
    display_name = "Sprint Availability"
    option_never_available = 0
    option_always_available = 1
    option_available_with_jacket = 2
    default = 2

class StartInventoryFromPool(StartInventoryPool):
    """Start inventory from pool for Start Inventory from Pool."""

class TrapChance(Range):
    """Option for Trap Chance."""
    display_name = "Trap Chance"
    range_start = 0
    range_end = 100
    default = 50


@dataclass
class SavingPrincessWorldGenOptions(PerGameCommonOptions):
    """Options for Saving Princess WorldGen."""
    randomize_items: RandomizeItems
    use_canonical_options: UseCanonicalOptions
    ace_weapon_upgrade: AceWeaponUpgrade
    cliff_weapon_upgrade: CliffWeaponUpgrade
    death_link: DeathLink
    expanded_pool: ExpandedPool
    iframes_duration: IframesDuration
    instant_saving: InstantSaving
    music_shuffle: MusicShuffle
    shake_intensity: ShakeIntensity
    sprint_availability: SprintAvailability
    start_inventory_from_pool: StartInventoryFromPool
    trap_chance: TrapChance
