"""
Access rules for Saving Princess WorldGen.

Auto-generated by world_generator.
"""

from typing import TYPE_CHECKING

from BaseClasses import CollectionState

from rule_builder import True_, False_, Has

if TYPE_CHECKING:
    from BaseClasses import CollectionState
    from worlds.AutoWorld import World


# Helper functions
def _savingprincessworldgen_all_weapons(state: "CollectionState", player: int) -> bool:
    return state.has_all((), player)


def _savingprincessworldgen_can_hover(state: "CollectionState", player: int) -> bool:
    return (state.has('Faster Reload', player, 4)) and (state.has_any((), player))


def _savingprincessworldgen_is_gate_unlocked(state: "CollectionState", player: int) -> bool:
    return (state.has_all((), player)) and (_savingprincessworldgen_super_nice_check(state, player))


def _savingprincessworldgen_is_power_on(state: "CollectionState", player: int) -> bool:
    return state.has('System Power', player)


def _savingprincessworldgen_nice_check(state: "CollectionState", player: int) -> bool:
    return (state.has('Life Extension', player)) and (state.has('Clip Extension', player)) and (state.has('Faster Reload', player, 2))


def _savingprincessworldgen_super_nice_check(state: "CollectionState", player: int) -> bool:
    return (state.has('Life Extension', player, 2)) and (state.has('Clip Extension', player, 2)) and (state.has('Faster Reload', player, 4)) and (state.has('Powered Blaster', player)) and (state.has_any((), player))


def set_rules(world: "World") -> None:
    """Set access rules for all locations and entrances."""
    player = world.player
    multiworld = world.multiworld

    # Entrance rules
    world.set_rule(
        multiworld.get_entrance("Volcanic entrance", player),
        Has("Powered Blaster")
    )

    world.set_rule(
        multiworld.get_entrance("Arctic entrance", player),
        Has("Powered Blaster")
    )

    world.set_rule(
        multiworld.get_entrance("Swamp entrance", player),
        Has("Powered Blaster")
    )

    multiworld.get_entrance("Electrical entrance", player).access_rule = \
        lambda state: _savingprincessworldgen_is_gate_unlocked(state, player)

    multiworld.get_entrance("Electrical (Power On) entrance", player).access_rule = \
        lambda state: _savingprincessworldgen_is_power_on(state, player)
    # Location rules
    world.set_rule(
        multiworld.get_location("Cave: Powered Blaster chest", player),
        Has("Clip Extension")
    )

    world.set_rule(
        multiworld.get_location("Cave: Guard (Boss)", player),
        Has("Clip Extension")
    )

    multiworld.get_location("Volcanic: Hot coals", player).access_rule = \
        lambda state: (_savingprincessworldgen_can_hover(state, player)) or (state.has('Ice Spreadshot', player))

    multiworld.get_location("Volcanic: Flamethrower chest", player).access_rule = \
        lambda state: _savingprincessworldgen_nice_check(state, player)

    multiworld.get_location("Volcanic: Cliff (Boss)", player).access_rule = \
        lambda state: _savingprincessworldgen_nice_check(state, player)

    world.set_rule(
        multiworld.get_location("Arctic: Under snow", player),
        Has("Flamethrower")
    )

    multiworld.get_location("Arctic: Ice Spreadshot chest", player).access_rule = \
        lambda state: _savingprincessworldgen_nice_check(state, player)

    world.set_rule(
        multiworld.get_location("Arctic: Jacket chest", player),
        Has("Flamethrower")
    )

    multiworld.get_location("Arctic: Ace (Boss)", player).access_rule = \
        lambda state: _savingprincessworldgen_nice_check(state, player)

    world.set_rule(
        multiworld.get_location("Hub: Hidden near Arctic", player),
        Has("Powered Blaster")
    )

    world.set_rule(
        multiworld.get_location("Hub: Ninja scare (Boss?)", player),
        Has("Cave Key")
    )

    multiworld.get_location("Swamp: Bramble room", player).access_rule = \
        lambda state: _savingprincessworldgen_can_hover(state, player)

    multiworld.get_location("Swamp: Special Extension chest", player).access_rule = \
        lambda state: _savingprincessworldgen_nice_check(state, player)

    multiworld.get_location("Swamp: Snake (Boss)", player).access_rule = \
        lambda state: _savingprincessworldgen_nice_check(state, player)

    world.set_rule(
        multiworld.get_location("Electrical: Tesla orb", player),
        Has("Volt Laser")
    )

    multiworld.get_location("Electrical: BRAINOS (Boss)", player).access_rule = \
        lambda state: _savingprincessworldgen_all_weapons(state, player)

    multiworld.get_location("Mission objective", player).access_rule = \
        lambda state: _savingprincessworldgen_all_weapons(state, player)
