"""
Game options for Jak and Daxter The Precursor Legacy WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, DefaultOnToggle, Range, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True


class UseCanonicalOptions(Toggle):
    """Use canonical options for seed 1.

    When enabled and generating seed 1, options will be loaded from the
    _worldgen_options.json file to reproduce the exact original seed.
    This ensures deterministic output matching the original world export.
    """
    display_name = "Use Canonical Options"
    default = True

class CitizenOrbTradeAmount(Range):
    """Option for Citizen Orb Trade Amount."""
    display_name = "Citizen Orb Trade Amount"
    range_start = 0
    range_end = 120
    default = 90

class EnableMoveRandomizer(Toggle):
    """Option for Enable Move Randomizer."""
    display_name = "Enable Move Randomizer"
    default = False

class EnableOrbsanity(Choice):
    """Option for Enable Orbsanity."""
    display_name = "Enable Orbsanity"
    option_off = 0
    option_per_level = 1
    option_global = 2
    default = 0

class EnableOrderedCellCounts(DefaultOnToggle):
    """Option for Enable Ordered Cell Counts."""
    display_name = "Enable Ordered Cell Counts"

class FillerOrbBundlesReplacedWithTraps(Range):
    """Option for Filler Orb Bundles Replaced With Traps."""
    display_name = "Filler Orb Bundles Replaced With Traps"
    range_start = 0
    range_end = 2000
    default = 0

class FillerPowerCellsReplacedWithTraps(Range):
    """Option for Filler Power Cells Replaced With Traps."""
    display_name = "Filler Power Cells Replaced With Traps"
    range_start = 0
    range_end = 100
    default = 0

class FireCanyonCellCount(Range):
    """Option for Fire Canyon Cell Count."""
    display_name = "Fire Canyon Cell Count"
    range_start = 0
    range_end = 30
    default = 20

class GlobalOrbsanityBundleSize(Choice):
    """Option for Global Orbsanity Bundle Size."""
    display_name = "Global Orbsanity Bundle Size"
    option_10_orbs = 10
    option_16_orbs = 16
    option_20_orbs = 20
    option_25_orbs = 25
    option_40_orbs = 40
    option_50_orbs = 50
    option_80_orbs = 80
    option_100_orbs = 100
    option_125_orbs = 125
    option_200_orbs = 200
    default = 20

class JakCompletionCondition(Choice):
    """Option for Completion Condition."""
    display_name = "Completion Condition"
    option_cross_fire_canyon = 69
    option_defeat_klaww = 86
    option_cross_mountain_pass = 87
    option_cross_lava_tube = 89
    option_defeat_gol_and_maia = 112
    option_open_100_cell_door = 116
    default = 112

class LavaTubeCellCount(Range):
    """Option for Lava Tube Cell Count."""
    display_name = "Lava Tube Cell Count"
    range_start = 0
    range_end = 90
    default = 72

class LevelOrbsanityBundleSize(Choice):
    """Option for Per Level Orbsanity Bundle Size."""
    display_name = "Per Level Orbsanity Bundle Size"
    option_10_orbs = 10
    option_25_orbs = 25
    option_50_orbs = 50
    default = 25

class MountainPassCellCount(Range):
    """Option for Mountain Pass Cell Count."""
    display_name = "Mountain Pass Cell Count"
    range_start = 0
    range_end = 60
    default = 45

class OracleOrbTradeAmount(Range):
    """Option for Oracle Orb Trade Amount."""
    display_name = "Oracle Orb Trade Amount"
    range_start = 0
    range_end = 150
    default = 120

class RequirePunchForKlaww(DefaultOnToggle):
    """Option for Require Punch For Klaww."""
    display_name = "Require Punch For Klaww"

class TrapEffectDuration(Range):
    """Option for Trap Effect Duration."""
    display_name = "Trap Effect Duration"
    range_start = 5
    range_end = 60
    default = 30


@dataclass
class JakandDaxterThePrecursorLegacyWorldGenOptions(PerGameCommonOptions):
    """Options for Jak and Daxter The Precursor Legacy WorldGen."""
    randomize_items: RandomizeItems
    use_canonical_options: UseCanonicalOptions
    citizen_orb_trade_amount: CitizenOrbTradeAmount
    enable_move_randomizer: EnableMoveRandomizer
    enable_orbsanity: EnableOrbsanity
    enable_ordered_cell_counts: EnableOrderedCellCounts
    filler_orb_bundles_replaced_with_traps: FillerOrbBundlesReplacedWithTraps
    filler_power_cells_replaced_with_traps: FillerPowerCellsReplacedWithTraps
    fire_canyon_cell_count: FireCanyonCellCount
    global_orbsanity_bundle_size: GlobalOrbsanityBundleSize
    jak_completion_condition: JakCompletionCondition
    lava_tube_cell_count: LavaTubeCellCount
    level_orbsanity_bundle_size: LevelOrbsanityBundleSize
    mountain_pass_cell_count: MountainPassCellCount
    oracle_orb_trade_amount: OracleOrbTradeAmount
    require_punch_for_klaww: RequirePunchForKlaww
    trap_effect_duration: TrapEffectDuration
