"""
Game options for Mega Man 3 WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, Range, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True


class UseCanonicalOptions(Toggle):
    """Use canonical options for seed 1.

    When enabled and generating seed 1, options will be loaded from the
    _worldgen_options.json file to reproduce the exact original seed.
    This ensures deterministic output matching the original world export.
    """
    display_name = "Use Canonical Options"
    default = True

class Consumables(Choice):
    """Option for Consumables."""
    display_name = "Consumables"
    option_none = 0
    option_1up_etank = 1
    option_weapon_health = 2
    option_all = 3
    default = 1

class DeathLink(Toggle):
    """Option for Death Link."""
    display_name = "Death Link"
    default = False

class EnemyWeakness(Toggle):
    """Option for Random Enemy Weaknesses."""
    display_name = "Random Enemy Weaknesses"
    default = False

class EnergyLink(Toggle):
    """Option for EnergyLink."""
    display_name = "EnergyLink"
    default = False

class MusicShuffle(Choice):
    """Option for Music Shuffle."""
    display_name = "Music Shuffle"
    option_none = 0
    option_shuffled = 1
    option_randomized = 2
    option_no_music = 3
    default = 0

class PaletteShuffle(Choice):
    """Option for Palette Shuffle."""
    display_name = "Palette Shuffle"
    option_none = 0
    option_shuffled = 1
    option_randomized = 2
    option_singularity = 3
    default = 0

class RandomWeakness(Choice):
    """Option for Random Boss Weaknesses."""
    display_name = "Random Boss Weaknesses"
    option_none = 0
    option_shuffled = 1
    option_randomized = 2
    default = 0

class ReduceFlashing(Toggle):
    """Option for Reduce Flashing."""
    display_name = "Reduce Flashing"
    default = False

class StartingRobotMaster(Choice):
    """Option for Starting Robot Master."""
    display_name = "Starting Robot Master"
    option_needle_man = 0
    option_magnet_man = 1
    option_gemini_man = 2
    option_hard_man = 3
    option_top_man = 4
    option_snake_man = 5
    option_spark_man = 6
    option_shadow_man = 7
    default = "random"

class StrictWeakness(Toggle):
    """Option for Strict Boss Weaknesses."""
    display_name = "Strict Boss Weaknesses"
    default = False

class Wily4Requirement(Range):
    """Option for Wily 4 Requirement."""
    display_name = "Wily 4 Requirement"
    range_start = 1
    range_end = 8
    default = 8


@dataclass
class MegaMan3WorldGenOptions(PerGameCommonOptions):
    """Options for Mega Man 3 WorldGen."""
    randomize_items: RandomizeItems
    use_canonical_options: UseCanonicalOptions
    consumables: Consumables
    death_link: DeathLink
    enemy_weakness: EnemyWeakness
    energy_link: EnergyLink
    music_shuffle: MusicShuffle
    palette_shuffle: PaletteShuffle
    random_weakness: RandomWeakness
    reduce_flashing: ReduceFlashing
    starting_robot_master: StartingRobotMaster
    strict_weakness: StrictWeakness
    wily_4_requirement: Wily4Requirement
