"""
Location definitions for Muse Dash WorldGen.

Auto-generated by world_generator.
"""

from typing import Any, Dict, Optional
from BaseClasses import Location, LocationProgressType


class MuseDashWorldGenLocation(Location):
    """Location class for Muse Dash WorldGen."""
    game: str = "Muse Dash WorldGen"


class LocationData:
    """Data container for location definitions."""

    def __init__(self, region: str, name: str, location_id: Optional[int], event: bool = False,
                 progress_type: "LocationProgressType" = None, show_in_spoiler: bool = True,
                 access: Optional[Dict[str, Any]] = None, extra_attributes: Optional[Dict[str, Any]] = None):
        self.region = region
        self.name = name
        self.location_id = location_id
        self.event = event
        self.progress_type = progress_type
        self.show_in_spoiler = show_in_spoiler
        self.access = access  # Game-specific access data
        self.extra_attributes = extra_attributes or {}  # Game-specific attributes


location_table: Dict[str, LocationData] = {
    "Breaking Dawn-0": LocationData("Menu", "Breaking Dawn-0", 2900006, False),
    "Breaking Dawn-1": LocationData("Menu", "Breaking Dawn-1", 2900007, False),
    "Best One feat.tooko-0": LocationData("Menu", "Best One feat.tooko-0", 2900024, False),
    "Best One feat.tooko-1": LocationData("Menu", "Best One feat.tooko-1", 2900025, False),
    "I don't care about Christmas though-0": LocationData("Menu", "I don't care about Christmas though-0", 2900064, False),
    "I don't care about Christmas though-1": LocationData("Menu", "I don't care about Christmas though-1", 2900065, False),
    "Koi no Moonlight-0": LocationData("Menu", "Koi no Moonlight-0", 2900036, False),
    "Koi no Moonlight-1": LocationData("Menu", "Koi no Moonlight-1", 2900037, False),
    "Yuki no Shizuku Ame no Oto-0": LocationData("Menu", "Yuki no Shizuku Ame no Oto-0", 2900022, False),
    "Yuki no Shizuku Ame no Oto-1": LocationData("Menu", "Yuki no Shizuku Ame no Oto-1", 2900023, False),
    "Iyaiya-0": LocationData("Menu", "Iyaiya-0", 2900002, False),
    "Iyaiya-1": LocationData("Menu", "Iyaiya-1", 2900003, False),
    "Heart Message feat. Aoi Tokimori-0": LocationData("Menu", "Heart Message feat. Aoi Tokimori-0", 2901260, False),
    "Heart Message feat. Aoi Tokimori-1": LocationData("Menu", "Heart Message feat. Aoi Tokimori-1", 2901261, False),
    "irregulyze-0": LocationData("Menu", "irregulyze-0", 2900062, False),
    "irregulyze-1": LocationData("Menu", "irregulyze-1", 2900063, False),
    "Clock Room & Spiritual World-0": LocationData("Menu", "Clock Room & Spiritual World-0", 2900092, False),
    "Clock Room & Spiritual World-1": LocationData("Menu", "Clock Room & Spiritual World-1", 2900093, False),
    "Latitude-0": LocationData("Menu", "Latitude-0", 2900086, False),
    "Latitude-1": LocationData("Menu", "Latitude-1", 2900087, False),
    "Etude -Sunset--0": LocationData("Menu", "Etude -Sunset--0", 2900824, False),
    "Etude -Sunset--1": LocationData("Menu", "Etude -Sunset--1", 2900825, False),
    "Evolution-0": LocationData("Menu", "Evolution-0", 2900018, False),
    "Evolution-1": LocationData("Menu", "Evolution-1", 2900019, False),
    "Blackest Luxury Car-0": LocationData("Menu", "Blackest Luxury Car-0", 2900058, False),
    "Blackest Luxury Car-1": LocationData("Menu", "Blackest Luxury Car-1", 2900059, False),
    "Bass Telekinesis-0": LocationData("Menu", "Bass Telekinesis-0", 2900052, False),
    "Bass Telekinesis-1": LocationData("Menu", "Bass Telekinesis-1", 2900053, False),
    "Confession-0": LocationData("Menu", "Confession-0", 2900046, False),
    "Confession-1": LocationData("Menu", "Confession-1", 2900047, False),
    "Lys Tourbillon-0": LocationData("Menu", "Lys Tourbillon-0", 2900830, False),
    "Lys Tourbillon-1": LocationData("Menu", "Lys Tourbillon-1", 2900831, False),
    "Pancake is Love-0": LocationData("Menu", "Pancake is Love-0", 2900014, False),
    "Pancake is Love-1": LocationData("Menu", "Pancake is Love-1", 2900015, False),
    "umpopoff-0": LocationData("Menu", "umpopoff-0", 2900102, False),
    "umpopoff-1": LocationData("Menu", "umpopoff-1", 2900103, False),
    "Night Wander-0": LocationData("Menu", "Night Wander-0", 2900028, False),
    "Night Wander-1": LocationData("Menu", "Night Wander-1", 2900029, False),
    "Dolphin and Broadcast-0": LocationData("Menu", "Dolphin and Broadcast-0", 2900020, False),
    "Dolphin and Broadcast-1": LocationData("Menu", "Dolphin and Broadcast-1", 2900021, False),
    "Mezame Eurythmics-0": LocationData("Menu", "Mezame Eurythmics-0", 2900082, False),
    "Mezame Eurythmics-1": LocationData("Menu", "Mezame Eurythmics-1", 2900083, False),
    "Mujinku-Vacuum-0": LocationData("Menu", "Mujinku-Vacuum-0", 2900098, False),
    "Mujinku-Vacuum-1": LocationData("Menu", "Mujinku-Vacuum-1", 2900099, False),
    "Departure Road-0": LocationData("Menu", "Departure Road-0", 2900050, False),
    "Departure Road-1": LocationData("Menu", "Departure Road-1", 2900051, False),
    "MilK-0": LocationData("Menu", "MilK-0", 2900100, False),
    "MilK-1": LocationData("Menu", "MilK-1", 2900101, False),
    "Yume Ou Mono Yo-0": LocationData("Menu", "Yume Ou Mono Yo-0", 2901066, False),
    "Yume Ou Mono Yo-1": LocationData("Menu", "Yume Ou Mono Yo-1", 2901067, False),
    "Frost Land-0": LocationData("Menu", "Frost Land-0", 2900010, False),
    "Frost Land-1": LocationData("Menu", "Frost Land-1", 2900011, False),
    "Say! Fanfare!-0": LocationData("Menu", "Say! Fanfare!-0", 2900074, False),
    "Say! Fanfare!-1": LocationData("Menu", "Say! Fanfare!-1", 2900075, False),
    "Out of Sense-0": LocationData("Menu", "Out of Sense-0", 2900820, False),
    "Out of Sense-1": LocationData("Menu", "Out of Sense-1", 2900821, False),
    "Funkotsu Saishin Casino-0": LocationData("Menu", "Funkotsu Saishin Casino-0", 2900090, False),
    "Funkotsu Saishin Casino-1": LocationData("Menu", "Funkotsu Saishin Casino-1", 2900091, False),
    "Medicine of Sing-0": LocationData("Menu", "Medicine of Sing-0", 2900060, False),
    "Medicine of Sing-1": LocationData("Menu", "Medicine of Sing-1", 2900061, False),
    "Goodbye Boss-0": LocationData("Menu", "Goodbye Boss-0", 2900826, False),
    "Goodbye Boss-1": LocationData("Menu", "Goodbye Boss-1", 2900827, False),
    "Dohna Dohna no Uta-0": LocationData("Menu", "Dohna Dohna no Uta-0", 2900030, False),
    "Dohna Dohna no Uta-1": LocationData("Menu", "Dohna Dohna no Uta-1", 2900031, False),
    "Heart-Pounding Flight-0": LocationData("Menu", "Heart-Pounding Flight-0", 2900012, False),
    "Heart-Pounding Flight-1": LocationData("Menu", "Heart-Pounding Flight-1", 2900013, False),
    "Stargazer-0": LocationData("Menu", "Stargazer-0", 2900828, False),
    "Stargazer-1": LocationData("Menu", "Stargazer-1", 2900829, False),
    "Aqua Stars-0": LocationData("Menu", "Aqua Stars-0", 2900088, False),
    "Aqua Stars-1": LocationData("Menu", "Aqua Stars-1", 2900089, False),
    "Ira-0": LocationData("Menu", "Ira-0", 2900056, False),
    "Ira-1": LocationData("Menu", "Ira-1", 2900057, False),
    "Mopemope-0": LocationData("Menu", "Mopemope-0", 2900104, False),
    "Mopemope-1": LocationData("Menu", "Mopemope-1", 2900105, False),
    "DISCO NIGHT-0": LocationData("Menu", "DISCO NIGHT-0", 2900034, False),
    "DISCO NIGHT-1": LocationData("Menu", "DISCO NIGHT-1", 2900035, False),
    "From the New World-0": LocationData("Menu", "From the New World-0", 2900070, False),
    "From the New World-1": LocationData("Menu", "From the New World-1", 2900071, False),
    "Lights of Muse-0": LocationData("Menu", "Lights of Muse-0", 2900040, False),
    "Lights of Muse-1": LocationData("Menu", "Lights of Muse-1", 2900041, False),
    "Shenri Kuaira -repeat--0": LocationData("Menu", "Shenri Kuaira -repeat--0", 2900084, False),
    "Shenri Kuaira -repeat--1": LocationData("Menu", "Shenri Kuaira -repeat--1", 2900085, False),
    "EXIST-0": LocationData("Menu", "EXIST-0", 2900648, False),
    "EXIST-1": LocationData("Menu", "EXIST-1", 2900649, False),
    "Lian Ai Audio Navigation-0": LocationData("Menu", "Lian Ai Audio Navigation-0", 2900038, False),
    "Lian Ai Audio Navigation-1": LocationData("Menu", "Lian Ai Audio Navigation-1", 2900039, False),
    "Candy-coloured Love Theory-0": LocationData("Menu", "Candy-coloured Love Theory-0", 2900026, False),
    "Candy-coloured Love Theory-1": LocationData("Menu", "Candy-coloured Love Theory-1", 2900027, False),
    "Galaxy Striker-0": LocationData("Menu", "Galaxy Striker-0", 2900048, False),
    "Galaxy Striker-1": LocationData("Menu", "Galaxy Striker-1", 2900049, False),
}
