"""
shapez WorldGen world implementation for Archipelago.

Auto-generated by world_generator.
"""

from typing import ClassVar, Dict, Any, TYPE_CHECKING
from BaseClasses import Item, ItemClassification, Tutorial
from worlds.AutoWorld import WebWorld, World
from rule_builder import RuleWorldMixin

if TYPE_CHECKING:
    from BaseClasses import CollectionState, MultiWorld

from .Items import item_table, shapezWorldGenItem
from .Locations import location_table, shapezWorldGenLocation
from .Options import shapezWorldGenOptions
from .Regions import create_regions
from .Rules import set_rules


# Item pool counts from original generation (excluding locked placements)
ITEMPOOL_COUNTS: Dict[str, int] = {
    "Belt Reader": 1,
    "Big Belt Upgrade": 9,
    "Big Miner Upgrade": 12,
    "Big Painting Upgrade": 10,
    "Big Processors Upgrade": 12,
    "Blueprint Shapes Bundle": 10,
    "Blueprints": 1,
    "Chaining Extractor": 1,
    "Color Mixer": 1,
    "Compact Merger": 1,
    "Compact Splitter": 1,
    "Constant Signal": 1,
    "Cutter": 1,
    "Display": 1,
    "Double Painter": 1,
    "Item Filter": 1,
    "Level Shapes Bundle": 8,
    "Logic Gates": 1,
    "Painter": 1,
    "Quad Cutter": 1,
    "Quad Painter": 1,
    "Rotator": 1,
    "Rotator (180°)": 1,
    "Rotator (CCW)": 1,
    "Small Belt Upgrade": 13,
    "Small Miner Upgrade": 13,
    "Small Painting Upgrade": 7,
    "Small Processors Upgrade": 10,
    "Stacker": 1,
    "Switch": 1,
    "Trash": 1,
    "Tunnel": 1,
    "Tunnel Tier II": 1,
    "Upgrade Shapes Bundle": 8,
    "Virtual Processing": 1,
    "Wires": 1,
}

# Locked placements - items that must be placed via place_locked_item
LOCKED_PLACEMENTS: Dict[str, str] = {
    "Level 1": "Balancer",
    "Level 1 Additional": "Storage",
    "Goal": "Goal",
}

# Starting items - items the player begins with (precollected)
STARTING_ITEMS: Dict[str, int] = {
    "Belt": 1,
    "Extractor": 1,
}


class shapezWorldGenWeb(WebWorld):
    """Web interface for shapez WorldGen."""
    theme = "stone"
    tutorials = [
        Tutorial(
            "Multiworld Setup Guide",
            "A guide to playing shapez with Archipelago:",
            "English",
            "setup_en.md",
            "setup/en",
            ["BlastSlimey"]
        ),
        Tutorial(
            "Multiworld Setup Guide",
            "A guide to playing shapez with Archipelago:",
            "Deutsch",
            "setup_de.md",
            "setup/de",
            ["BlastSlimey"]
        ),
        Tutorial(
            "Changing datapackage settings",
            "3000 locations are too many or not enough? Here's how you can change that:",
            "English",
            "datapackage_settings_en.md",
            "datapackage_settings/en",
            ["BlastSlimey"]
        ),
        Tutorial(
            "Changing datapackage settings",
            "3000 locations are too many or not enough? Here's how you can change that:",
            "Deutsch",
            "datapackage_settings_de.md",
            "datapackage_settings/de",
            ["BlastSlimey"]
        )
    ]


class shapezWorldGenWorld(RuleWorldMixin, World):
    """
    shapez is an automation game about cutting, rotating, stacking, and painting shapes, that you extract from randomly
    generated patches on an infinite canvas, without the need to manage your infinite resources or to pay for building
    your factories.
    """

    game: ClassVar[str] = "shapez WorldGen"
    web: ClassVar[WebWorld] = shapezWorldGenWeb()

    options_dataclass = shapezWorldGenOptions
    options: shapezWorldGenOptions

    base_id: ClassVar[int] = 20010707
    # Disable rule caching - requires CollectionState.rule_cache from PR #5048
    rule_caching_enabled: ClassVar[bool] = False

    item_name_to_id: ClassVar[Dict[str, int]] = {
        name: data.id for name, data in item_table.items() if data.id is not None
    }

    location_name_to_id: ClassVar[Dict[str, int]] = {
        name: data.location_id for name, data in location_table.items()
        if data.location_id is not None
    }

    item_name_groups: ClassVar[Dict[str, frozenset]] = {
        "Everything": frozenset(["Cutter", "Quad Cutter", "Rotator", "Rotator (CCW)", "Rotator (180°)", "Stacker", "Painter", "Double Painter", "Quad Painter", "Color Mixer", "Balancer", "Compact Merger", "Compact Splitter", "Tunnel", "Tunnel Tier II", "Trash", "Chaining Extractor", "Belt Reader", "Storage", "Switch", "Item Filter", "Display", "Wires", "Constant Signal", "Logic Gates", "Virtual Processing", "Blueprints", "Big Belt Upgrade", "Big Miner Upgrade", "Big Processors Upgrade", "Big Painting Upgrade", "Small Belt Upgrade", "Small Miner Upgrade", "Small Processors Upgrade", "Small Painting Upgrade", "Gigantic Belt Upgrade", "Gigantic Miner Upgrade", "Gigantic Processors Upgrade", "Gigantic Painting Upgrade", "Rising Belt Upgrade", "Rising Miner Upgrade", "Rising Processors Upgrade", "Rising Painting Upgrade", "Big Random Upgrade", "Small Random Upgrade", "Belt Upgrade Trap", "Miner Upgrade Trap", "Processors Upgrade Trap", "Painting Upgrade Trap", "Demonic Belt Upgrade Trap", "Demonic Miner Upgrade Trap", "Demonic Processors Upgrade Trap", "Demonic Painting Upgrade Trap", "Blueprint Shapes Bundle", "Level Shapes Bundle", "Upgrade Shapes Bundle", "Locked Building Trap", "Throttled Building Trap", "Malfunctioning Trap", "Inflation Trap", "Belts Clearing Trap", "Inventory Draining Trap", "Blueprint Shapes Draining Trap", "Level Shapes Draining Trap", "Upgrade Shapes Draining Trap", "Belt", "Extractor"]),
        "Goal Buildings": frozenset(["Cutter", "Quad Cutter", "Rotator", "Rotator (CCW)", "Stacker", "Painter", "Double Painter", "Quad Painter", "Color Mixer", "Switch", "Wires", "Constant Signal"]),
        "Main Buildings": frozenset(["Cutter", "Rotator", "Stacker", "Painter", "Color Mixer"]),
        "Processing Buildings": frozenset(["Cutter", "Quad Cutter", "Rotator", "Rotator (CCW)", "Rotator (180°)", "Stacker", "Painter", "Double Painter", "Quad Painter", "Color Mixer"]),
        "Most Useful Buildings": frozenset(["Balancer", "Compact Merger", "Compact Splitter", "Tunnel", "Tunnel Tier II", "Trash", "Chaining Extractor"]),
        "Top Row Buildings": frozenset(["Belt Reader", "Storage", "Switch", "Item Filter", "Display"]),
        "Gameplay Mechanics": frozenset(["Wires", "Blueprints"]),
        "Wires Layer Buildings": frozenset(["Wires", "Constant Signal", "Logic Gates", "Virtual Processing"]),
        "Belt Upgrades": frozenset(["Big Belt Upgrade", "Small Belt Upgrade", "Gigantic Belt Upgrade", "Rising Belt Upgrade", "Belt Upgrade Trap", "Demonic Belt Upgrade Trap"]),
        "Upgrades": frozenset(["Big Belt Upgrade", "Big Miner Upgrade", "Big Processors Upgrade", "Big Painting Upgrade", "Small Belt Upgrade", "Small Miner Upgrade", "Small Processors Upgrade", "Small Painting Upgrade", "Gigantic Belt Upgrade", "Gigantic Miner Upgrade", "Gigantic Processors Upgrade", "Gigantic Painting Upgrade", "Rising Belt Upgrade", "Rising Miner Upgrade", "Rising Processors Upgrade", "Rising Painting Upgrade", "Big Random Upgrade", "Small Random Upgrade", "Belt Upgrade Trap", "Miner Upgrade Trap", "Processors Upgrade Trap", "Painting Upgrade Trap", "Demonic Belt Upgrade Trap", "Demonic Miner Upgrade Trap", "Demonic Processors Upgrade Trap", "Demonic Painting Upgrade Trap"]),
        "Miner Upgrades": frozenset(["Big Miner Upgrade", "Small Miner Upgrade", "Gigantic Miner Upgrade", "Rising Miner Upgrade", "Miner Upgrade Trap", "Demonic Miner Upgrade Trap"]),
        "Processors Upgrades": frozenset(["Big Processors Upgrade", "Small Processors Upgrade", "Gigantic Processors Upgrade", "Rising Processors Upgrade", "Processors Upgrade Trap", "Demonic Processors Upgrade Trap"]),
        "Painting Upgrades": frozenset(["Big Painting Upgrade", "Small Painting Upgrade", "Gigantic Painting Upgrade", "Rising Painting Upgrade", "Painting Upgrade Trap", "Demonic Painting Upgrade Trap"]),
        "Traps": frozenset(["Belt Upgrade Trap", "Miner Upgrade Trap", "Processors Upgrade Trap", "Painting Upgrade Trap", "Demonic Belt Upgrade Trap", "Demonic Miner Upgrade Trap", "Demonic Processors Upgrade Trap", "Demonic Painting Upgrade Trap", "Locked Building Trap", "Throttled Building Trap", "Malfunctioning Trap", "Inflation Trap", "Belts Clearing Trap", "Inventory Draining Trap", "Blueprint Shapes Draining Trap", "Level Shapes Draining Trap", "Upgrade Shapes Draining Trap"]),
        "Bundles": frozenset(["Blueprint Shapes Bundle", "Level Shapes Bundle", "Upgrade Shapes Bundle"]),
        "Most Important Buildings": frozenset(["Belt", "Extractor"]),
        "Event": frozenset(["Goal"]),
    }

    def generate_early(self) -> None:
        """Push starting items as precollected."""
        self._push_starting_items()

    def create_regions(self) -> None:
        """Create regions, locations, and connections."""
        create_regions(self.multiworld, self.player)

    def set_rules(self) -> None:
        """Set access rules."""
        set_rules(self)

    def create_items(self) -> None:
        """Create randomized item pool."""
        # First, place any locked items
        self._place_locked_items()

        # Then create the random item pool
        item_pool = []

        for item_name, count in ITEMPOOL_COUNTS.items():
            # Skip event items
            if item_name not in item_table or item_table[item_name].id is None:
                continue

            item_data = item_table[item_name]
            for _ in range(count):
                item = shapezWorldGenItem(
                    item_name,
                    item_data.classification,
                    item_data.id,
                    self.player
                )
                item_pool.append(item)

        self.multiworld.itempool += item_pool

    def _place_locked_items(self) -> None:
        """Place items that must be in specific locations (locked placements)."""
        for location_name, item_name in LOCKED_PLACEMENTS.items():
            if item_name and item_name in item_table:
                location = self.multiworld.get_location(location_name, self.player)
                item_data = item_table[item_name]
                item = shapezWorldGenItem(
                    item_name,
                    item_data.classification,
                    item_data.id,
                    self.player
                )
                location.place_locked_item(item)

    def _push_starting_items(self) -> None:
        """Push starting items as precollected (for state counters like coins)."""
        for item_name, count in STARTING_ITEMS.items():
            if item_name in item_table:
                for _ in range(count):
                    item = self.create_item(item_name)
                    self.multiworld.push_precollected(item)

    def create_item(self, name: str) -> Item:
        """Create an item by name."""
        data = item_table[name]
        return shapezWorldGenItem(name, data.classification, data.id, self.player)


    def fill_slot_data(self) -> Dict[str, Any]:
        """Return data for the client."""
        return {
            "Level building 1": "Cutter",
            "Level building 2": "Rotator",
            "Level building 3": "Painter",
            "Level building 4": "Color Mixer",
            "Level building 5": "Stacker",
            "Upgrade building 1": "Stacker",
            "Upgrade building 2": "Cutter",
            "Upgrade building 3": "Rotator",
            "Upgrade building 4": "Painter",
            "Upgrade building 5": "Color Mixer",
            "goal": "vanilla",
            "maxlevel": 25,
            "finaltier": 8,
            "required_shapes_multiplier": 10,
            "allow_floating_layers": False,
            "randomize_level_requirements": True,
            "randomize_upgrade_requirements": True,
            "randomize_level_logic": "stretched",
            "randomize_upgrade_logic": "linear",
            "throughput_levels_ratio": 0,
            "complexity_growth_gradient": 0.5,
            "same_late_upgrade_requirements": True,
            "toolbar_shuffling": True,
            "Phase 0 length": 1,
            "Phase 1 length": 1,
            "Phase 2 length": 1,
            "Phase 3 length": 1,
            "Phase 4 length": 1,
            "belt category buildings amount": 0,
            "miner category buildings amount": 1,
            "processors category buildings amount": 2,
            "painting category buildings amount": 3,
            "seed": 3745,
            "shapesanity": ['Uncolored Circle', 'Uncolored Square', 'Uncolored Star', 'Uncolored Windmill', 'Cyan Windmill', 'Cornered Yellow Star', 'Half Cyan Circle', 'Purple Square Piece', 'Yellow Circle Piece', 'Half Blue Circle', 'Cut Out Green Circle', 'Cut Out Blue Square', 'Green Star Piece', 'Red Square Piece', 'Cornered Yellow Square', 'Red Windmill', 'Half Red Star', 'Yellow Windmill Piece', 'Cut Out Red Star', 'Half White Circle', 'Cut Out Red Square', 'Blue Square', 'Cut Out Blue Star', 'Blue Star Piece', 'Purple Circle', 'bcgr Star', 'Yellow CRS-', 'cpru Circle', 'Blue CSW-', 'Adjacent 2-1 Wc Ww', 'Adjacent Singles Cr Wr', '3-1 Rr Sg', 'Cornered 2-1 Rr Ww', 'Adjacent 2-1 Su Cc', 'Adjacent 2-1 Su Wc', '3-1 Ru Cu', 'Half-Half Cp Su', 'Checkered Cr Wp', '3-1 Rc Rr', 'Adjacent 2-1 Cy Wr', 'Adjacent Singles Cw Sy', 'Adjacent 2-1-1 Sg Cb Ww', 'Singles Cy Sw Wr', 'Cornered 2-1-1 Ry Cc Cy', 'Adjacent 2-1-1 Su Sy Wu', 'Singles Cr Rb Wg Wy', 'Singles Cw Sy Wg Wr', 'Singles Cp Rb Sg Sr', 'Singles Cc Cp Ru Rw', 'Singles Cr Cw Rb Rw'],
        }
