"""
Access rules for shapez WorldGen.

Auto-generated by world_generator.
"""

from typing import TYPE_CHECKING


from rule_builder import True_, False_, And, Conditional, False_, Has, HasAll, HasAny, Not, Or, True_

if TYPE_CHECKING:
    from BaseClasses import CollectionState
    from worlds.AutoWorld import World


def set_rules(world: "World") -> None:
    """Set access rules for all locations and entrances."""
    player = world.player
    multiworld = world.multiworld

    # Entrance rules
    world.set_rule(
        multiworld.get_entrance("Placing belts", player),
        Has('Belt')
    )

    world.set_rule(
        multiworld.get_entrance("Extracting shapes from patches", player),
        HasAny('Chaining Extractor', 'Extractor')
    )

    world.set_rule(
        multiworld.get_entrance("Using the wires layer", player),
        Has('Wires')
    )

    world.set_rule(
        multiworld.get_entrance("Placing any building", player),
        HasAny('Balancer', 'Belt', 'Belt Reader', 'Chaining Extractor', 'Color Mixer', 'Compact Merger', 'Compact Splitter', 'Cutter', 'Display', 'Double Painter', 'Extractor', 'Item Filter', 'Painter', 'Quad Cutter', 'Quad Painter', 'Rotator', 'Rotator (180°)', 'Rotator (CCW)', 'Stacker', 'Storage', 'Switch', 'Trash', 'Tunnel', 'Tunnel Tier II', 'Wires')
    )

    world.set_rule(
        multiworld.get_entrance("Transporting shapes over the canvas", player),
        HasAny('Belt', 'Compact Merger', 'Compact Splitter')
    )

    world.set_rule(
        multiworld.get_entrance("Cutting with half cutter", player),
        Has('Cutter')
    )

    world.set_rule(
        multiworld.get_entrance("Rotating clockwise", player),
        Has('Rotator')
    )

    world.set_rule(
        multiworld.get_entrance("Stacking shapes", player),
        Has('Stacker')
    )

    world.set_rule(
        multiworld.get_entrance("Storing shapes", player),
        Has('Storage')
    )

    world.set_rule(
        multiworld.get_entrance("Trashing shapes", player),
        Has('Trash')
    )

    world.set_rule(
        multiworld.get_entrance("Painting with (double) painter", player),
        HasAny('Double Painter', 'Painter')
    )

    world.set_rule(
        multiworld.get_entrance("Copying and placing blueprints", player),
        And(And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker')), Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter')), Has('Blueprints'), Has('Color Mixer'))
    )

    world.set_rule(
        multiworld.get_entrance("Building a MAM", player),
        And(And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker')), Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter')), Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAll('Belt Reader', 'Item Filter', 'Logic Gates', 'Storage', 'Virtual Processing', 'Wires'), HasAny('Tunnel', 'Tunnel Tier II'), Has('Color Mixer'))
    )

    world.set_rule(
        multiworld.get_entrance("Using all main buildings", player),
        And(And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker')), Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter')), Has('Color Mixer'))
    )

    world.set_rule(
        multiworld.get_entrance("Using first level building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Conditional(test=And(False_(), True_()), if_true=HasAny('Cutter', 'Quad Cutter'), if_false=Has('Cutter')))
    )

    world.set_rule(
        multiworld.get_entrance("Using first upgrade building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Has('Stacker'))
    )

    world.set_rule(
        multiworld.get_entrance("Cutting in single half", player),
        Or(HasAll('Quad Cutter', 'Stacker'), Has('Cutter'))
    )

    world.set_rule(
        multiworld.get_entrance("Cutting in single piece", player),
        Or(And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter')), Has('Quad Cutter'))
    )

    world.set_rule(
        multiworld.get_entrance("Cutting and stacking into two halves", player),
        And(HasAny('Cutter', 'Quad Cutter'), Has('Stacker'))
    )

    world.set_rule(
        multiworld.get_entrance("Stitching complex shapes", player),
        And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker'))
    )

    world.set_rule(
        multiworld.get_entrance("Rotating and stitching a single windmill half", player),
        And(Or(And(HasAny('Rotator', 'Rotator (180°)', 'Rotator (CCW)'), Has('Cutter')), Has('Quad Cutter')), Has('Stacker'))
    )

    world.set_rule(
        multiworld.get_entrance("Painting with a quad painter or stitching", player),
        Or(And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker')), And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')))
    )

    world.set_rule(
        multiworld.get_entrance("Why windmill, why?", player),
        Or(And(And(Or(And(HasAny('Rotator', 'Rotator (180°)', 'Rotator (CCW)'), Has('Cutter')), Has('Quad Cutter')), Has('Stacker')), And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch'))), And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker')))
    )

    world.set_rule(
        multiworld.get_entrance("Quad painting a half-half shape", player),
        Or(And(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), And(HasAny('Cutter', 'Quad Cutter'), Has('Stacker'))), And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker')))
    )

    world.set_rule(
        multiworld.get_entrance("Quad painting a half shape", player),
        Or(And(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), Or(HasAll('Quad Cutter', 'Stacker'), Has('Cutter'))), And(Or(And(True_(), Has('Quad Cutter')), And(HasAny('Rotator', 'Rotator (CCW)'), Has('Cutter'))), Has('Stacker')))
    )

    world.set_rule(
        multiworld.get_entrance("Using second level building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=HasAny('Rotator', 'Rotator (CCW)'))
    )

    world.set_rule(
        multiworld.get_entrance("Using third level building", player),
        Conditional(test=And(True_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter')))
    )

    world.set_rule(
        multiworld.get_entrance("Using fourth level building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Has('Color Mixer'))
    )

    world.set_rule(
        multiworld.get_entrance("Using fifth level building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Has('Stacker'))
    )

    world.set_rule(
        multiworld.get_entrance("Using second upgrade building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Conditional(test=And(True_(), True_()), if_true=HasAny('Cutter', 'Quad Cutter'), if_false=Has('Cutter')))
    )

    world.set_rule(
        multiworld.get_entrance("Using third upgrade building", player),
        Conditional(test=And(True_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=HasAny('Rotator', 'Rotator (CCW)'))
    )

    world.set_rule(
        multiworld.get_entrance("Using fourth upgrade building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter')))
    )

    world.set_rule(
        multiworld.get_entrance("Using fifth upgrade building", player),
        Conditional(test=And(False_(), Not(And(Or(HasAll('Compact Merger', 'Compact Splitter'), Has('Balancer')), HasAny('Tunnel', 'Tunnel Tier II'), Has('Trash')))), if_true=False_(), if_false=Has('Color Mixer'))
    )

    world.set_rule(
        multiworld.get_entrance("Delivering per second with 1.6x belt speed", player),
        False_()
    )

    world.set_rule(
        multiworld.get_entrance("Painting a full shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a full shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a half shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a half shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a piece shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a piece shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a stitched shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a stitched shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a east windmill shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a east windmill shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a half-half shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a half-half shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a colorful east windmill shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a colorful east windmill shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a colorful half-half shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a colorful half-half shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a colorful full shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a colorful full shape", player),
        Has('Color Mixer')
    )

    world.set_rule(
        multiworld.get_entrance("Painting a colorful half shape", player),
        Or(And(HasAll('Quad Painter', 'Wires'), HasAny('Constant Signal', 'Switch')), HasAny('Double Painter', 'Painter'))
    )

    world.set_rule(
        multiworld.get_entrance("Mixing colors for a colorful half shape", player),
        Has('Color Mixer')
    )
