"""
Item definitions for Castlevania 64 WorldGen.

Auto-generated by world_generator.
"""

from typing import Dict, Optional
from BaseClasses import ItemClassification, Item


class Castlevania64WorldGenItem(Item):
    """Item class for Castlevania 64 WorldGen."""
    game: str = "Castlevania 64 WorldGen"


class ItemData:
    """Data container for item definitions."""

    def __init__(self, item_id: Optional[int], classification: ItemClassification):
        self.id = item_id
        self.classification = classification


item_table: Dict[str, ItemData] = {
    "Red jewel(S)": ItemData(12992514, ItemClassification.filler),
    "Red jewel(L)": ItemData(12992515, ItemClassification.filler),
    "Special1": ItemData(12992516, ItemClassification.progression),
    "Special2": ItemData(12992517, ItemClassification.filler),
    "Roast chicken": ItemData(12992518, ItemClassification.filler),
    "Roast beef": ItemData(12992519, ItemClassification.filler),
    "Healing kit": ItemData(12992520, ItemClassification.useful),
    "Purifying": ItemData(12992521, ItemClassification.filler),
    "Cure ampoule": ItemData(12992522, ItemClassification.filler),
    "PowerUp": ItemData(12992524, ItemClassification.filler),
    "Knife": ItemData(12992525, ItemClassification.filler),
    "Holy water": ItemData(12992526, ItemClassification.filler),
    "Cross": ItemData(12992527, ItemClassification.filler),
    "Axe": ItemData(12992528, ItemClassification.filler),
    "Ice Trap": ItemData(12992530, ItemClassification.filler),
    "Magical Nitro": ItemData(12992533, ItemClassification.progression),
    "Mandragora": ItemData(12992534, ItemClassification.progression),
    "Sun card": ItemData(12992535, ItemClassification.filler),
    "Moon card": ItemData(12992536, ItemClassification.filler),
    "Archives Key": ItemData(12992538, ItemClassification.progression),
    "Left Tower Key": ItemData(12992539, ItemClassification.progression),
    "Storeroom Key": ItemData(12992540, ItemClassification.progression),
    "Garden Key": ItemData(12992541, ItemClassification.progression),
    "Copper Key": ItemData(12992542, ItemClassification.progression),
    "Chamber Key": ItemData(12992543, ItemClassification.progression),
    "Execution Key": ItemData(12992544, ItemClassification.progression),
    "Science Key1": ItemData(12992545, ItemClassification.progression),
    "Science Key2": ItemData(12992546, ItemClassification.progression),
    "Science Key3": ItemData(12992547, ItemClassification.progression),
    "Clocktower Key1": ItemData(12992548, ItemClassification.progression),
    "Clocktower Key2": ItemData(12992549, ItemClassification.progression),
    "Clocktower Key3": ItemData(12992550, ItemClassification.progression),
    "500 GOLD": ItemData(12992551, ItemClassification.filler),
    "300 GOLD": ItemData(12992552, ItemClassification.filler),
    "100 GOLD": ItemData(12992553, ItemClassification.filler),
    "PermaUp": ItemData(12992780, ItemClassification.filler),
    "Crystal": ItemData(None, ItemClassification.progression),
    "The Count Downed": ItemData(None, ItemClassification.progression),
}
