"""
Region definitions for ChecksFinder Test.

Auto-generated by world_generator.
"""

from BaseClasses import MultiWorld, Region, Entrance
from .Locations import location_table, ChecksFinderTestLocation


def create_regions(multiworld: MultiWorld, player: int) -> None:
    """Create all regions, locations, and connections."""

    # Create all regions
    region_names = ["Board", "Menu"]

    regions = {}
    for region_name in region_names:
        region = Region(region_name, player, multiworld)
        regions[region_name] = region
        multiworld.regions.append(region)

    # Add locations to regions
    for location_name, location_data in location_table.items():
        region = regions[location_data.region]
        location = ChecksFinderTestLocation(
            player,
            location_name,
            location_data.location_id,
            region
        )

        # Mark event locations - use place_locked_item in __init__.py instead

        region.locations.append(location)

    # Create entrances
    _create_entrance(regions["Menu"], regions["Board"], "New Board")


def _create_entrance(source: Region, target: Region, name: str) -> Entrance:
    """Helper to create and connect an entrance."""
    entrance = Entrance(source.player, name, source)
    entrance.connect(target)
    source.exits.append(entrance)
    return entrance
