"""
Region definitions for Wargroove WorldGen.

Auto-generated by world_generator.
"""

from typing import Dict, Set
from BaseClasses import MultiWorld, Region, Entrance
from .Locations import location_table, WargrooveWorldGenLocation


def create_regions(multiworld: MultiWorld, player: int) -> None:
    """Create all regions, locations, and connections."""

    # Create all regions
    region_names = ["Menu", "Humble Beginnings", "Best Friendssss", "A Knight's Folly", "Denrunaway", "Dragon Freeway", "Deep Thicket", "Corrupted Inlet", "Mage Mayhem", "Endless Knight", "Ambushed in the Middle", "The Churning Sea", "Frigid Archery", "Archery Lessons", "Surrounded", "Darkest Knight", "Robbed", "Open Season", "Doggo Mountain", "Tenri's Fall", "Foolish Canal", "Master of the Lake", "A Ballista's Revenge", "Rebel Village", "Wargroove Finale"]

    regions = {}
    for region_name in region_names:
        hint = None
        region = Region(region_name, player, multiworld, hint)
        regions[region_name] = region
        multiworld.regions.append(region)

    # Mark dynamically added regions (these won't appear in sphere log comparisons)
    try:
        _dynamically_added = DYNAMICALLY_ADDED_REGIONS
    except NameError:
        _dynamically_added = set()
    for region_name in _dynamically_added:
        if region_name in regions:
            regions[region_name].dynamically_added = True

    # Add locations to regions
    for location_name, location_data in location_table.items():
        region = regions[location_data.region]
        location = WargrooveWorldGenLocation(
            player,
            location_name,
            location_data.location_id,
            region
        )

        # Apply location properties from location_data
        if location_data.event:
            location.event = True
        if location_data.progress_type is not None:
            location.progress_type = location_data.progress_type
        if not location_data.show_in_spoiler:
            location.show_in_spoiler = False

        region.locations.append(location)

    # Create entrances
    _create_entrance(regions["Menu"], regions["Humble Beginnings"], "Humble Beginnings")
    _create_entrance(regions["Humble Beginnings"], regions["Best Friendssss"], "Best Friendssss")
    _create_entrance(regions["Humble Beginnings"], regions["A Knight's Folly"], "A Knight's Folly")
    _create_entrance(regions["Humble Beginnings"], regions["Denrunaway"], "Denrunaway")
    _create_entrance(regions["Humble Beginnings"], regions["Wargroove Finale"], "Wargroove Finale")
    _create_entrance(regions["Best Friendssss"], regions["Dragon Freeway"], "Dragon Freeway")
    _create_entrance(regions["Best Friendssss"], regions["Deep Thicket"], "Deep Thicket")
    _create_entrance(regions["Best Friendssss"], regions["Corrupted Inlet"], "Corrupted Inlet")
    _create_entrance(regions["A Knight's Folly"], regions["Mage Mayhem"], "Mage Mayhem")
    _create_entrance(regions["A Knight's Folly"], regions["Endless Knight"], "Endless Knight")
    _create_entrance(regions["A Knight's Folly"], regions["Ambushed in the Middle"], "Ambushed in the Middle")
    _create_entrance(regions["Denrunaway"], regions["The Churning Sea"], "The Churning Sea")
    _create_entrance(regions["Denrunaway"], regions["Frigid Archery"], "Frigid Archery")
    _create_entrance(regions["Denrunaway"], regions["Archery Lessons"], "Archery Lessons")
    _create_entrance(regions["Dragon Freeway"], regions["Surrounded"], "Surrounded")
    _create_entrance(regions["Deep Thicket"], regions["Darkest Knight"], "Darkest Knight")
    _create_entrance(regions["Corrupted Inlet"], regions["Robbed"], "Robbed")
    _create_entrance(regions["Mage Mayhem"], regions["Open Season"], "Open Season")
    _create_entrance(regions["Mage Mayhem"], regions["Foolish Canal"], "Foolish Canal: Mage Mayhem Entrance")
    _create_entrance(regions["Endless Knight"], regions["Doggo Mountain"], "Doggo Mountain")
    _create_entrance(regions["Endless Knight"], regions["Foolish Canal"], "Foolish Canal: Endless Knight Entrance")
    _create_entrance(regions["Ambushed in the Middle"], regions["Tenri's Fall"], "Tenri's Fall")
    _create_entrance(regions["The Churning Sea"], regions["Rebel Village"], "Rebel Village")
    _create_entrance(regions["Frigid Archery"], regions["A Ballista's Revenge"], "A Ballista's Revenge")
    _create_entrance(regions["Archery Lessons"], regions["Master of the Lake"], "Master of the Lake")


def _create_entrance(source: Region, target: Region, name: str) -> Entrance:
    """Helper to create and connect an entrance."""
    entrance = Entrance(source.player, name, source)
    entrance.connect(target)
    source.exits.append(entrance)
    return entrance
