"""
Access rules for Seedling WorldGen.

Auto-generated by world_generator.
"""

from typing import TYPE_CHECKING

from BaseClasses import CollectionState

from rule_builder import True_, False_, And, HelperCall, Or

if TYPE_CHECKING:
    from BaseClasses import CollectionState
    from worlds.AutoWorld import World


# Helper functions
def has_item(state: "CollectionState", player: int, item = None) -> bool:
    return ((state.count('Progressive Swim', player) >= 1) if (item == 'Conch') else ((state.count('Progressive Swim', player) >= 2) if (item == "Penguin's Feather") else ((state.count('Progressive Sword', player) >= 1) if (item == 'Sword') else ((state.count('Progressive Shield', player) >= 1) if (item == 'Shield') else ((state.count('Progressive Shield', player) >= 2) if (item == 'Dark Shield') else ((state.count('Totem Shard', player) >= 5) if (item == 'Shards') else (((state.count('Progressive Sword', player) >= 1)) and (state.has('Ghost Spear', player)) and (state.has('Ghost Sword Fusion', player)) if (item == 'Ghost Sword') else ((state.has('Fire', player)) and (state.has('Wand', player)) and (state.has('Fire Wand Fusion', player)) if (item == 'Fire Wand') else state.has(item, player)))))))))


def set_rules(world: "World") -> None:
    """Set access rules for all locations and entrances."""
    player = world.player
    multiworld = world.multiworld

    # Location rules
    world.set_rule(
        multiworld.get_location("Penguin's Feather", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',))))
    )

    world.set_rule(
        multiworld.get_location("Dark Sword", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',))))
    )

    world.set_rule(
        multiworld.get_location("Chest (Waterfall)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',))))
    )

    world.set_rule(
        multiworld.get_location("Chest (Adnan's cave)", player),
        Or(And(Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))), Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Suit',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Health',))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))
    )

    world.set_rule(
        multiworld.get_location("Chest (South Rocks)", player),
        Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)))
    )

    world.set_rule(
        multiworld.get_location("Shield", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Red Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',))))
    )

    world.set_rule(
        multiworld.get_location("Red Key", player),
        Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))
    )

    world.set_rule(
        multiworld.get_location("Chest (Gundernourd Water)", player),
        HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',))
    )

    world.set_rule(
        multiworld.get_location("Chest (Gundernourd Pit)", player),
        Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))
    )

    world.set_rule(
        multiworld.get_location("Light", player),
        Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Green Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Red Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))))
    )

    world.set_rule(
        multiworld.get_location("Green Key", player),
        Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Red Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))))
    )

    world.set_rule(
        multiworld.get_location("Fire", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Green Key',)), Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(And(Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',))), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Red Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',))))))
    )

    world.set_rule(
        multiworld.get_location("Chest (Rostef)", player),
        Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(And(Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',))), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Red Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))), And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)))))
    )

    world.set_rule(
        multiworld.get_location("Conch", player),
        HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))
    )

    world.set_rule(
        multiworld.get_location("Blue Key", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',))))
    )

    world.set_rule(
        multiworld.get_location("Chest (Trohn Inside)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)))
    )

    world.set_rule(
        multiworld.get_location("Chest (Trohn Outside)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',))))
    )

    world.set_rule(
        multiworld.get_location("Totem Shard (Three Blocks Puzzle)", player),
        HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))
    )

    world.set_rule(
        multiworld.get_location("Totem Shard (Main Room Left)", player),
        HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))
    )

    world.set_rule(
        multiworld.get_location("Totem Shard (Mortar)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Purple Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',))))
    )

    world.set_rule(
        multiworld.get_location("Totem Shard (One Moving Block Puzzle)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Purple Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',))))
    )

    world.set_rule(
        multiworld.get_location("Totem Shard (Two Moving Blocks Puzzle)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Purple Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',))))
    )

    world.set_rule(
        multiworld.get_location("Purple Key", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',))))
    )

    world.set_rule(
        multiworld.get_location("Wand", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Shards',)))
    )

    world.set_rule(
        multiworld.get_location("Chest (Lacste Entrance)", player),
        Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)))
    )

    world.set_rule(
        multiworld.get_location("Chest (Lacste Main Room)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',))))
    )

    world.set_rule(
        multiworld.get_location("Ghost Spear", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), Or(And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)))), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire Wand',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Sword',))))
    )

    world.set_rule(
        multiworld.get_location("Yellow Key", player),
        HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',))
    )

    world.set_rule(
        multiworld.get_location("Health", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)))
    )

    world.set_rule(
        multiworld.get_location("Chest (Woshad)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Suit',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)))
    )

    world.set_rule(
        multiworld.get_location("Dark Shield", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))))
    )

    world.set_rule(
        multiworld.get_location("Dark Suit", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Shield',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))))
    )

    world.set_rule(
        multiworld.get_location("Chest (Bosiniad Main Room)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))))
    )

    world.set_rule(
        multiworld.get_location("Chest (Bosiniad Lava)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Suit',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Wand',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Yellow Key',)), Or(HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Fire',))))
    )

    world.set_rule(
        multiworld.get_location("Ghost Sword", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Suit',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)))
    )

    world.set_rule(
        multiworld.get_location("Fire Wand", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Suit',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Sword',)))
    )

    world.set_rule(
        multiworld.get_location("Chest (Ghethis)", player),
        And(HelperCall(helper_func=has_item, helper_name="has_item", args=("Penguin's Feather",)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Conch',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Dark Suit',)), HelperCall(helper_func=has_item, helper_name="has_item", args=('Ghost Spear',)))
    )
