from typing import Dict

Computer = "Computer"
Blade = "Blade Upgrade"
Suit = "Suit Upgrade"
Blaster = "Blaster Upgrade"
Scanner = "Pattern Scanner"
Level = "Level Up"
Filler = "Health Restore"
Victory = "Victory!"

Barriers: Dict[str, str] = {
    "A,9": "Barrier Removal - (A,9)",
    "B,9": "Barrier Removal - (B,9)",
    "B,11": "Barrier Removal - (B,11)",
    "C,6": "Barrier Removal - (C,6)",
    "D,11": "Barrier Removal - (D,11)",
    "E,3": "Barrier Removal - (E,3)",
    "G,4": "Barrier Removal - (G,4)",
    "G,9": "Barrier Removal - (G,9)",
    "H,1": "Barrier Removal - (H,1)",
    "H,4": "Barrier Removal - (H,4)",
    "H,11": "Barrier Removal - (H,11)",
    "H,14": "Barrier Removal - (H,14)",
    "I,4": "Barrier Removal - (I,4)",
    "I,7": "Barrier Removal - (I,7)",
    "J,2": "Barrier Removal - (J,2)",
    "K,4": "Barrier Removal - (K,4)",
    "L,10": "Barrier Removal - (L,10)",
    "L,15": "Barrier Removal - (L,15)",
    "M,4": "Barrier Removal - (M,4)",
    "M,6": "Barrier Removal - (M,6)",
    "M,11": "Barrier Removal - (M,11)"
}

Saves: Dict[str, str] = {
    "A,3": "Warp Point (A,3)",
    "A,8": "Warp Point (A,8)",
    "B,10": "Warp Point (B,10)",
    "C,5": "Warp Point (C,5)",
    "C,11": "Warp Point (C,11)",
    "D,5": "Warp Point (D,5)",
    "D,14": "Warp Point (D,14)",
    "D,15": "Warp Point (D,15)",
    "E,2": "Warp Point (E,2)",
    "E,8": "Warp Point (E,8)",
    "E,11": "Warp Point (E,11)",
    "F,2": "Warp Point (F,2)",
    "F,8": "Warp Point (F,8)",
    "F,12": "Warp Point (F,12)",
    "G,1": "Warp Point (G,1)",
    "G,3": "Warp Point (G,3)",
    "G,5": "Warp Point (G,5)",
    "G,11": "Warp Point (G,11)",
    "G,12": "Warp Point (G,12)",
    "H,6": "Warp Point (H,6)",
    "H,15": "Warp Point (H,15)",
    "I,1": "Warp Point (I,1)",
    "I,10": "Warp Point (I,10)",
    "J,3": "Warp Point (J,3)",
    "J,4": "Warp Point (J,4)",
    "J,5": "Warp Point (J,5)",
    "J,8": "Warp Point (J,8)",
    "J,11": "Warp Point (J,11)",
    "J,15": "Warp Point (J,15)",
    "K,1": "Warp Point (K,1)",
    "L,4": "Warp Point (L,4)",
    "L,8": "Warp Point (L,8)",
    "L,12": "Warp Point (L,12)",
    "L,15": "Warp Point (L,15)",
    "M,4": "Warp Point (M,4)",
    "M,11": "Warp Point (M,11)",
    "N,5": "Warp Point (N,5)",
    "N,9": "Warp Point (N,9)",
    "O,8": "Warp Point (O,8)"
}

Doors: Dict[str, str] = {
    "A,4": "Door Key (A,4)",
    "A,5": "Door Key (A,5)",
    "A,7": "Door Key (A,7)",
    "A,8": "Door Key (A,8)",
    "A,12": "Door Key (A,12)",
    "B,4": "Door Key (B,4)",
    "B,5": "Door Key (B,5)",
    "B,6": "Door Key (B,6)",
    "B,7": "Door Key (B,7)",
    "B,8": "Door Key (B,8)",
    "C,8": "Door Key (C,8)",
    "C,9": "Door Key (C,9)",
    "C,10": "Door Key (C,10)",
    "C,11": "Door Key (C,11)",
    "C,12": "Door Key (C,12)",
    "D,2": "Door Key (D,2)",
    "D,3": "Door Key (D,3)",
    "D,10": "Door Key (D,10)",
    "D,12": "Door Key (D,12)",
    "D,14": "Door Key (D,14)",
    "E,4": "Door Key (E,4)",
    "E,5": "Door Key (E,5)",
    "E,8": "Door Key (E,8)",
    "E,9": "Door Key (E,9)",
    "E,12": "Door Key (E,12)",
    "E,13": "Door Key (E,13)",
    "E,14": "Door Key (E,14)",
    "E,15": "Door Key (E,15)",
    "F,2": "Door Key (F,2)",
    "F,5": "Door Key (F,5)",
    "F,6": "Door Key (F,6)",
    "F,9": "Door Key (F,9)",
    "F,13": "Door Key (F,13)",
    "F,14": "Door Key (F,14)",
    "F,15": "Door Key (F,15)",
    "G,1": "Door Key (G,1)",
    "G,6": "Door Key (G,6)",
    "G,10": "Door Key (G,10)",
    "H,2": "Door Key (H,2)",
    "H,3": "Door Key (H,3)",
    "H,4": "Door Key (H,4)",
    "H,5": "Door Key (H,5)",
    "H,6": "Door Key (H,6)",
    "H,7": "Door Key (H,7)",
    "H,12": "Door Key (H,12)",
    "H,14": "Door Key (H,14)",
    "I,2": "Door Key (I,2)",
    "I,3": "Door Key (I,3)",
    "I,4": "Door Key (I,4)",
    "I,5": "Door Key (I,5)",
    "I,6": "Door Key (I,6)",
    "I,11": "Door Key (I,11)",
    "I,13": "Door Key (I,13)",
    "I,14": "Door Key (I,14)",
    "I,15": "Door Key (I,15)",
    "J,1": "Door Key (J,1)",
    "J,2": "Door Key (J,2)",
    "J,7": "Door Key (J,7)",
    "J,10": "Door Key (J,10)",
    "J,11": "Door Key (J,11)",
    "J,13": "Door Key (J,13)",
    "K,2": "Door Key (K,2)",
    "K,3": "Door Key (K,3)",
    "K,7": "Door Key (K,7)",
    "K,9": "Door Key (K,9)",
    "K,14": "Door Key (K,14)",
    "K,15": "Door Key (K,15)",
    "L,1": "Door Key (L,1)",
    "L,2": "Door Key (L,2)",
    "L,5": "Door Key (L,5)",
    "L,7": "Door Key (L,7)",
    "L,8": "Door Key (L,8)",
    "L,11": "Door Key (L,11)",
    "L,13": "Door Key (L,13)",
    "M,2": "Door Key (M,2)",
    "M,3": "Door Key (M,3)",
    "M,6": "Door Key (M,6)",
    "M,7": "Door Key (M,7)",
    "M,10": "Door Key (M,10)",
    "N,4": "Door Key (N,4)",
    "N,8": "Door Key (N,8)",
    "N,9": "Door Key (N,9)",
    "N,11": "Door Key (N,11)",
    "N,12": "Door Key (N,12)",
    "O,7": "Door Key (O,7)",
    "O,9": "Door Key (O,9)",
    "O,10": "Door Key (O,10)",
    "O,11": "Door Key (O,11)",
    "O,12": "Door Key (O,12)"
}

Battle_Doors: Dict[str, str] = {
    "B,6": "Battle Door Key (B,6)",
    "E,3": "Battle Door Key (E,3)",
    "H,2": "Battle Door Key (H,2)",
    "J,7": "Battle Door Key (J,7)",
    "K,2": "Battle Door Key (K,2)",
    "O,4": "Battle Door Key (O,4)"
}