from typing import List, Dict

Generators: Dict[str, str] = {
    "A,9": "Destroy Generator - (A,9)",
    "B,9": "Destroy Generator - (B,9)",
    "B,11": "Destroy Generator - (B,11)",
    "C,6": "Destroy Generator - (C,6)",
    "D,11": "Destroy Generator - (D,11)",
    "E,3": "Destroy Generator - (E,3)",
    "G,4": "Destroy Generator - (G,4)",
    "G,9": "Destroy Generator - (G,9)",
    "H,1": "Destroy Generator - (H,1)",
    "H,4": "Destroy Generator - (H,4)",
    "H,11": "Destroy Generator - (H,11)",
    "H,14": "Destroy Generator - (H,14)",
    "I,4": "Destroy Generator - (I,4)",
    "I,7": "Destroy Generator - (I,7)",
    "J,2": "Destroy Generator - (J,2)",
    "K,4": "Destroy Generator - (K,4)",
    "L,10": "Destroy Generator - (L,10)",
    "L,15": "Destroy Generator - (L,15)",
    "M,4": "Destroy Generator - (M,4)",
    "M,6": "Destroy Generator - (M,6)",
    "M,11": "Destroy Generator - (M,11)",
}

Powerups: Dict[str, str] = {
    "J,10": "Powerup from Rock Smasher - (J,10)",
    "H,5": "Powerup from Rock Smasher - (H,5)",
    "L,5": "Powerup from Silencer - (L,5)",
    "N,9": "Powerup from Silencer - (N,9)",
    "L,1": "Powerup from Plasma Hydra - (L,1)",
    "L,7": "Powerup from Plasma Hydra - (L,7)",
    "J,7": "Powerup from Reaper Drone - (J,7)",
    "B,5": "Powerup from Reaper Drone - (B,5)",
    "A,4": "Powerup from Liquid Metal Processor - (A,4)",
    "I,14": "Powerup from Liquid Metal Processor - (I,14)",
    "I,2": "Powerup from Grand Mother - (I,2)",
    "F,15": "Powerup from Grand Mother - (F,15)",
    "B,7": "Powerup from Guardian - (B,7)",
    "O,12": "Powerup from Guardian - (O,12)",
    "G,10": "Powerup from Star Splitter - (G,10)",
    "A,12": "Powerup from Star Splitter - (A,12)",
    "F,14": "Powerup from Elites - (F,14)",
    "J,2": "Powerup from Elites - (J,2)"
}

Level_Ups: Dict[str,str] = {
    "J,10": "Level Up from Rock Smasher - (J,10)",
    "H,5": "Level Up from Rock Smasher - (H,5)",
    "L,5": "Level Up from Silencer - (L,5)",
    "N,9": "Level Up from Silencer - (N,9)",
    "L,1": "Level Up from Plasma Hydra - (L,1)",
    "L,7": "Level Up from Plasma Hydra - (L,7)",
    "J,7": "Level Up from Reaper Drone - (J,7)",
    "B,5": "Level Up from Reaper Drone - (B,5)",
    "A,4": "Level Up from Liquid Metal Processor - (A,4)",
    "I,14": "Level Up from Liquid Metal Processor - (I,14)",
    "I,2": "Level Up from Grand Mother - (I,2)",
    "F,15": "Level Up from Grand Mother - (F,15)",
    "B,7": "Level Up from Guardian - (B,7)",
    "O,12": "Level Up from Guardian - (O,12)",
    "G,10": "Level Up from Star Splitter - (G,10)",
    "A,12": "Level Up from Star Splitter - (A,12)",
    "F,14": "Level Up from Elites - (F,14)",
    "J,2": "Level Up from Elites - (J,2)"
}

Eliminator = "Level Up from Eliminator"

Computers: Dict[str, str] = {
    "B,12": "Computer - (B,12)",
    "D,2": "Computer - (D,2)",
    "D,3": "Computer - (D,3)",
    "D,4": "Computer - (D,4)",
    "D,9": "Computer - (D,9)",
    "D,13": "Computer - (D,13)",
    "F,3": "Computer - (F,3)",
    "F,7": "Computer - (F,7)",
    "F,13": "Computer - (F,13)",
    "H,2": "Computer - (H,2)",
    "H,3": "Computer - (H,3)",
    "H,5": "Computer - (H,5)",
    "I,6": "Computer - (I,6)",
    "I,12": "Computer - (I,12)",
    "I,14": "Computer - (I,14)",
    "J,3": "Computer - (J,3)",
    "J,9": "Computer - (J,9)",
    "J,12": "Computer - (J,12)",
    "K,1": "Computer - (K,1)",
    "K,4": "Computer - (K,4)",
    "K,5": "Computer - (K,5)",
    "K,8": "Computer - (K,8)",
    "K,12": "Computer - (K,12)",
    "L,2": "Computer - (L,2)",
    "L,3": "Computer - (L,3)",
    "M,10": "Computer - (M,10)",
    "N,4": "Computer - (N,4)",
    "O,4": "Computer - (O,4)",
}

Saves: Dict[str, str] = {
    "A,3": "Save Point - (A,3)",
    "A,8": "Save Point - (A,8)",
    "B,10": "Save Point - (B,10)",
    "C,5": "Save Point - (C,5)",
    "C,11": "Save Point - (C,11)",
    "D,5": "Save Point - (D,5)",
    "D,14": "Save Point - (D,14)",
    "D,15": "Save Point - (D,15)",
    "E,2": "Save Point - (E,2)",
    "E,8": "Save Point - (E,8)",
    "E,11": "Save Point - (E,11)",
    "F,2": "Save Point - (F,2)",
    "F,8": "Save Point - (F,8)",
    "F,12": "Save Point - (F,12)",
    "G,1": "Save Point - (G,1)",
    "G,3": "Save Point - (G,3)",
    "G,5": "Save Point - (G,5)",
    "G,11": "Save Point - (G,11)",
    "G,12": "Save Point - (G,12)",
    "H,6": "Save Point - (H,6)",
    "H,15": "Save Point - (H,15)",
    "I,1": "Save Point - (I,1)",
    "I,10": "Save Point - (I,10)",
    "J,3": "Save Point - (J,3)",
    "J,4": "Save Point - (J,4)",
    "J,5": "Save Point - (J,5)",
    "J,8": "Save Point - (J,8)",
    "J,11": "Save Point - (J,11)",
    "J,15": "Save Point - (J,15)",
    "K,1": "Save Point - (K,1)",
    "L,4": "Save Point - (L,4)",
    "L,8": "Save Point - (L,8)",
    "L,12": "Save Point - (L,12)",
    "L,15": "Save Point - (L,15)",
    "M,4": "Save Point - (M,4)",
    "M,11": "Save Point - (M,11)",
    "N,5": "Save Point - (N,5)",
    "N,9": "Save Point - (N,9)",
    "O,8": "Save Point - (O,8)"
}

Doors: Dict[str, str] = {
    "A,4": "Defeat all Enemies - (A,4)",
    "A,5": "Defeat all Enemies - (A,5)",
    "A,7": "Defeat all Enemies - (A,7)",
    "A,8": "Defeat all Enemies - (A,8)",
    "A,12": "Defeat all Enemies - (A,12)",
    "B,4": "Defeat all Enemies - (B,4)",
    "B,5": "Defeat all Enemies - (B,5)",
    "B,6": "Defeat all Enemies - (B,6)",
    "B,7": "Defeat all Enemies - (B,7)",
    "B,8": "Defeat all Enemies - (B,8)",
    "C,8": "Defeat all Enemies - (C,8)",
    "C,9": "Defeat all Enemies - (C,9)",
    "C,10": "Defeat all Enemies - (C,10)",
    "C,11": "Defeat all Enemies - (C,11)",
    "C,12": "Defeat all Enemies - (C,12)",
    "D,2": "Defeat all Enemies - (D,2)",
    "D,3": "Defeat all Enemies - (D,3)",
    "D,10": "Defeat all Enemies - (D,10)",
    "D,12": "Defeat all Enemies - (D,12)",
    "D,14": "Defeat all Enemies - (D,14)",
    "E,4": "Defeat all Enemies - (E,4)",
    "E,5": "Defeat all Enemies - (E,5)",
    "E,8": "Defeat all Enemies - (E,8)",
    "E,9": "Defeat all Enemies - (E,9)",
    "E,12": "Defeat all Enemies - (E,12)",
    "E,13": "Defeat all Enemies - (E,13)",
    "E,14": "Defeat all Enemies - (E,14)",
    "E,15": "Defeat all Enemies - (E,15)",
    "F,2": "Defeat all Enemies - (F,2)",
    "F,5": "Defeat all Enemies - (F,5)",
    "F,6": "Defeat all Enemies - (F,6)",
    "F,9": "Defeat all Enemies - (F,9)",
    "F,13": "Defeat all Enemies - (F,13)",
    "F,14": "Defeat all Enemies - (F,14)",
    "F,15": "Defeat all Enemies - (F,15)",
    "G,1": "Defeat all Enemies - (G,1)",
    "G,6": "Defeat all Enemies - (G,6)",
    "G,10": "Defeat all Enemies - (G,10)",
    "H,2": "Defeat all Enemies - (H,2)",
    "H,3": "Defeat all Enemies - (H,3)",
    "H,4": "Defeat all Enemies - (H,4)",
    "H,5": "Defeat all Enemies - (H,5)",
    "H,6": "Defeat all Enemies - (H,6)",
    "H,7": "Defeat all Enemies - (H,7)",
    "H,12": "Defeat all Enemies - (H,12)",
    "H,14": "Defeat all Enemies - (H,14)",
    "I,2": "Defeat all Enemies - (I,2)",
    "I,3": "Defeat all Enemies - (I,3)",
    "I,4": "Defeat all Enemies - (I,4)",
    "I,5": "Defeat all Enemies - (I,5)",
    "I,6": "Defeat all Enemies - (I,6)",
    "I,11": "Defeat all Enemies - (I,11)",
    "I,13": "Defeat all Enemies - (I,13)",
    "I,14": "Defeat all Enemies - (I,14)",
    "I,15": "Defeat all Enemies - (I,15)",
    "J,1": "Defeat all Enemies - (J,1)",
    "J,2": "Defeat all Enemies - (J,2)",
    "J,7": "Defeat all Enemies - (J,7)",
    "J,10": "Defeat all Enemies - (J,10)",
    "J,11": "Defeat all Enemies - (J,11)",
    "J,13": "Defeat all Enemies - (J,13)",
    "K,2": "Defeat all Enemies - (K,2)",
    "K,3": "Defeat all Enemies - (K,3)",
    "K,7": "Defeat all Enemies - (K,7)",
    "K,9": "Defeat all Enemies - (K,9)",
    "K,14": "Defeat all Enemies - (K,14)",
    "K,15": "Defeat all Enemies - (K,15)",
    "L,1": "Defeat all Enemies - (L,1)",
    "L,2": "Defeat all Enemies - (L,2)",
    "L,5": "Defeat all Enemies - (L,5)",
    "L,7": "Defeat all Enemies - (L,7)",
    "L,8": "Defeat all Enemies - (L,8)",
    "L,11": "Defeat all Enemies - (L,11)",
    "L,13": "Defeat all Enemies - (L,13)",
    "M,2": "Defeat all Enemies - (M,2)",
    "M,3": "Defeat all Enemies - (M,3)",
    "M,6": "Defeat all Enemies - (M,6)",
    "M,7": "Defeat all Enemies - (M,7)",
    "M,10": "Defeat all Enemies - (M,10)",
    "N,4": "Defeat all Enemies - (N,4)",
    "N,8": "Defeat all Enemies - (N,8)",
    "N,9": "Defeat all Enemies - (N,9)",
    "N,11": "Defeat all Enemies - (N,11)",
    "N,12": "Defeat all Enemies - (N,12)",
    "O,7": "Defeat all Enemies - (O,7)",
    "O,9": "Defeat all Enemies - (O,9)",
    "O,10": "Defeat all Enemies - (O,10)",
    "O,11": "Defeat all Enemies - (O,11)",
    "O,12": "Defeat all Enemies - (O,12)"
}

Battle_Doors: Dict[str, str] = {
    "B,6": "Defeat Battle Door - (B,6)",
    "E,3": "Defeat Battle Door - (E,3)",
    "H,2": "Defeat Battle Door - (H,2)",
    "J,7": "Defeat Battle Door - (J,7)",
    "K,2": "Defeat Battle Door - (K,2)",
    "O,4": "Defeat Battle Door - (O,4)"
}

ShipScan = "Obtain Ship Scan"
Zero = "Defeat Zero"
Expel = "Obtain Expel Computer"
Speedrun = "Obtain Speedrun Times Computer"
Shapeshift = "Obtain Shapeshift Computer"
Flower = "Touch Secret X Flower"
Grave = "Touch Trollis' Grave"
Tetron = "Defeat Cruiser Tetron"
WarMachine = "Defeat the Living Warmachine"