from typing import List, Dict

Menu = "Menu"

Normal: Dict[str, str] = {
    "A,4": "Normal (A,4)",
    "A,7": "Normal (A,7)",
    "A,10": "Normal (A,10)",
    "B,4": "Normal (B,4)",
    "B,7": "Normal (B,7)",
    "B,8": "Normal (B,8)",
    "B,9": "Normal (B,9)",
    "B,12": "Normal (B,12)",
    "C,6": "Normal (C,6)",
    "C,7": "Normal (C,7)",
    "C,9": "Normal (C,9)",
    "D,1": "Normal Main Region",
    "D,2": "Normal (D,2)",
    "D,3": "Normal (D,3)",
    "D,4": "Normal (D,4)",
    "D,8": "Normal (D,8)",
    "D,9": "Normal (D,9)",
    "D,11": "Normal (D,11)",
    "D,13": "Normal (D,13)",
    "D,14": "Normal (D,14)",
    "D,15": "Normal (D,15)",
    "E,3": "Normal (E,3)",
    "E,9": "Normal (E,9)",
    "E,13": "Normal (E,13)",
    "E,14": "Normal (E,14)",
    "F,13": "Normal (F,13)",
    "F,14": "Normal (F,14)",
    "F,15": "Normal (F,15)",
    "G,10": "Normal (G,10)",
    "H,2": "Normal (H,2)",
    "H,3": "Normal (H,3)",
    "H,8": "Tetron",
    "H,11": "Normal (H,11)",
    "H,12": "Normal (H,12)",
    "I,2": "Normal (I,2)",
    "I,5": "Normal (I,5)",
    "I,6": "Normal (I,6)",
    "I,11": "Normal (I,11)",
    "I,14": "Normal (I,14)",
    "J,4": "Normal (J,4)",
    "J,6": "Normal (J,6)",
    "J,7": "Normal (J,7)",
    "J,9": "Normal (J,9)",
    "J,10": "Normal (J,10)",
    "J,12": "Normal (J,12)",
    "J,14": "Normal (J,14)",
    "L,2": "Normal (L,2)",
    "L,4": "Normal (L,4)",
    "L,5": "Normal (L,5)",
    "L,11": "Normal (L,11)",
    "L,13": "Normal Start",
    "M,4": "Normal (M,4)",
    "M,5": "Normal (M,5)",
    "M,6": "Normal (M,6)",
    "M,11": "Normal (M,11)",
    "N,6": "Normal (N,6)",
    "O,4": "Normal (O,4)",
    "O,12": "Normal (O,12)"
}

Hard: Dict[str, str] = {
    "A,4": "Hard (A,4)",
    "A,6": "Hard (A,6)",
    "A,7": "Hard (A,7)",
    "A,8": "Hard (A,8)",
    "A,9": "Hard (A,9)",
    "A,10": "Hard (A,10)",
    "A,11": "Hard (A,11)",
    "B,4": "Hard Main Region",
    "B,5": "Hard (B,5)",
    "B,8": "Hard (B,8)",
    "B,11": "Hard (B,11)",
    "B,12": "Hard (B,12)",
    "C,6": "Hard (C,6)",
    "C,10": "Hard (C,10)",
    "C,11": "Hard (C,11)",
    "C,12": "Hard (C,12)",
    "D,1": "Hard (D,1)",
    "D,12": "Hard (D,12)",
    "D,13": "Hard (D,13)",
    "D,14": "Hard (D,14)",
    "E,1": "Hard (E,1)",
    "E,10": "Hard (E,10)",
    "F,5": "Hard (F,5)",
    "F,6": "Hard (F,6)",
    "F,7": "Hard (F,7)",
    "F,13": "Hard (F,13)",
    "F,15": "Hard (F,15)",
    "G,1": "Hard Start",
    "G,2": "Hard (G,2)",
    "G,5": "Hard (G,5)",
    "H,5": "Hard (H,5)",
    "H,8": "Tetron",
    "H,13": "Hard (H,13)",
    "I,5": "Hard (I,5)",
    "I,6": "Hard (I,6)",
    "I,7": "Hard (I,7)",
    "I,12": "Hard (I,12)",
    "I,13": "Hard (I,13)",
    "I,14": "Hard (I,14)",
    "J,1": "Hard (J,1)",
    "J,2": "Hard (J,2)",
    "J,3": "Hard (J,3)",
    "J,4": "Hard (J,4)",
    "J,14": "Hard (J,14)",
    "K,2": "Hard (K,2)",
    "K,3": "Hard (K,3)",
    "K,7": "Hard (K,7)",
    "K,8": "Hard (K,8)",
    "K,12": "Hard (K,12)",
    "L,2": "Hard (L,2)",
    "L,8": "Hard (L,8)",
    "L,10": "Hard (L,10)",
    "L,15": "Hard (L,15)",
    "M,10": "Hard (M,10)",
    "M,11": "Hard (M,11)",
    "N,4": "Hard (N,4)",
    "N,5": "Hard (N,5)",
    "N,9": "Hard (N,9)",
    "N,10": "Hard (N,10)",
    "N,11": "Hard (N,11)",
    "N,12": "Hard (N,12)",
    "O,4": "Hard (O,4)",
    "O,8": "Hard (O,8)",
    "O,9": "Hard (O,9)",
    "O,10": "Hard (O,10)",
    "O,11": "Hard (O,11)",
    "O,12": "Hard (O,12)"
}

Annihilation: Dict[str, str] = {
    "A,3": "Annihilator Start",
    "D,4": "Annihilator (D,4)",
    "E,1": "Annihilator (E,1)",
    "E,3": "Annihilator (E,3)",
    "E,4": "Annihilator (E,4)",
    "E,5": "Annihilator (E,5)",
    "F,2": "Annihilator (F,2)",
    "F,4": "Annihilator (F,4)",
    "G,2": "Annihilator (G,2)",
    "G,4": "Annihilator (G,4)",
    "G,5": "Annihilator (G,5)",
    "H,1": "Annihilator (H,1)",
    "H,4": "Annihilator (H,4)",
    "H,6": "Annihilator (H,6)",
    "I,1": "Annihilator (I,1)",
    "I,5": "Annihilator (I,5)",
    "I,6": "Annihilator (I,6)",
    "J,2": "Annihilator (J,2)",
    "K,3": "Annihilator (K,3)",
    "L,1": "Annihilator (L,1)",
    "L,5": "Living War Machine",
    "M,3": "Annihilator (M,3)"
}