"""
Game options for Celeste 64 WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, Range, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True

class BadelineChaserFrequency(Range):
    """Option for Badeline Chaser Frequency."""
    display_name = "Badeline Chaser Frequency"
    range_start = 0
    range_end = 10
    default = 0

class BadelineChaserSource(Choice):
    """Option for Badeline Chaser Source."""
    display_name = "Badeline Chaser Source"
    option_locations = 0
    option_strawberries = 1
    default = 0

class BadelineChaserSpeed(Range):
    """Option for Badeline Chaser Speed."""
    display_name = "Badeline Chaser Speed"
    range_start = 2
    range_end = 10
    default = 3

class Carsanity(Toggle):
    """Option for Carsanity."""
    display_name = "Carsanity"

class Checkpointsanity(Toggle):
    """Option for Checkpointsanity."""
    display_name = "Checkpointsanity"

class DeathLink(Toggle):
    """Option for Death Link."""
    display_name = "Death Link"

class DeathLinkAmnesty(Range):
    """Option for Death Link Amnesty."""
    display_name = "Death Link Amnesty"
    range_start = 1
    range_end = 30
    default = 10

class Friendsanity(Toggle):
    """Option for Friendsanity."""
    display_name = "Friendsanity"

class LogicDifficulty(Choice):
    """Option for Logic Difficulty."""
    display_name = "Logic Difficulty"
    option_standard = 0
    option_hard = 1
    default = 0

class MadelineFeatherHairColor(Choice):
    """Option for Madeline Feather Hair Color."""
    display_name = "Madeline Feather Hair Color"
    option_any_color = -1
    option_black = 0
    option_royal_blue = 14015
    option_bright_green = 896773
    option_forest_green = 1255448
    option_empty = 7258367
    option_maroon = 8388608
    option_grey = 8421504
    option_lime_green = 9304352
    option_baddy = 10174389
    option_brown = 12027686
    option_orange = 14183946
    option_strawberry = 14363648
    option_golden = 15914064
    option_double = 16421375
    option_fire_red = 16711680
    option_salmon = 16726629
    option_white = 16777215
    default = 15914064

class MadelineNoDashHairColor(Choice):
    """Option for Madeline No Dash Hair Color."""
    display_name = "Madeline No Dash Hair Color"
    option_any_color = -1
    option_black = 0
    option_royal_blue = 14015
    option_bright_green = 896773
    option_forest_green = 1255448
    option_empty = 7258367
    option_maroon = 8388608
    option_grey = 8421504
    option_lime_green = 9304352
    option_baddy = 10174389
    option_brown = 12027686
    option_orange = 14183946
    option_strawberry = 14363648
    option_golden = 15914064
    option_double = 16421375
    option_fire_red = 16711680
    option_salmon = 16726629
    option_white = 16777215
    default = 7258367

class MadelineOneDashHairColor(Choice):
    """Option for Madeline One Dash Hair Color."""
    display_name = "Madeline One Dash Hair Color"
    option_any_color = -1
    option_black = 0
    option_royal_blue = 14015
    option_bright_green = 896773
    option_forest_green = 1255448
    option_empty = 7258367
    option_maroon = 8388608
    option_grey = 8421504
    option_lime_green = 9304352
    option_baddy = 10174389
    option_brown = 12027686
    option_orange = 14183946
    option_strawberry = 14363648
    option_golden = 15914064
    option_double = 16421375
    option_fire_red = 16711680
    option_salmon = 16726629
    option_white = 16777215
    default = 14363648

class MadelineTwoDashHairColor(Choice):
    """Option for Madeline Two Dash Hair Color."""
    display_name = "Madeline Two Dash Hair Color"
    option_any_color = -1
    option_black = 0
    option_royal_blue = 14015
    option_bright_green = 896773
    option_forest_green = 1255448
    option_empty = 7258367
    option_maroon = 8388608
    option_grey = 8421504
    option_lime_green = 9304352
    option_baddy = 10174389
    option_brown = 12027686
    option_orange = 14183946
    option_strawberry = 14363648
    option_golden = 15914064
    option_double = 16421375
    option_fire_red = 16711680
    option_salmon = 16726629
    option_white = 16777215
    default = 16421375

class MoveShuffle(Toggle):
    """Option for Move Shuffle."""
    display_name = "Move Shuffle"

class Signsanity(Toggle):
    """Option for Signsanity."""
    display_name = "Signsanity"

class StrawberriesRequiredPercentage(Range):
    """Option for Strawberries Required Percentage."""
    display_name = "Strawberries Required Percentage"
    range_start = 0
    range_end = 100
    default = 80

class TotalStrawberries(Range):
    """Option for Total Strawberries."""
    display_name = "Total Strawberries"
    range_start = 0
    range_end = 55
    default = 20


@dataclass
class Celeste64WorldGenOptions(PerGameCommonOptions):
    """Options for Celeste 64 WorldGen."""
    randomize_items: RandomizeItems
    badeline_chaser_frequency: BadelineChaserFrequency
    badeline_chaser_source: BadelineChaserSource
    badeline_chaser_speed: BadelineChaserSpeed
    carsanity: Carsanity
    checkpointsanity: Checkpointsanity
    death_link: DeathLink
    death_link_amnesty: DeathLinkAmnesty
    friendsanity: Friendsanity
    logic_difficulty: LogicDifficulty
    madeline_feather_hair_color: MadelineFeatherHairColor
    madeline_no_dash_hair_color: MadelineNoDashHairColor
    madeline_one_dash_hair_color: MadelineOneDashHairColor
    madeline_two_dash_hair_color: MadelineTwoDashHairColor
    move_shuffle: MoveShuffle
    signsanity: Signsanity
    strawberries_required_percentage: StrawberriesRequiredPercentage
    total_strawberries: TotalStrawberries
