"""
Region definitions for Celeste 64 WorldGen.

Auto-generated by world_generator.
"""

from typing import Dict, Set
from BaseClasses import MultiWorld, Region, Entrance
from .Locations import location_table, Celeste64WorldGenLocation


def create_regions(multiworld: MultiWorld, player: int) -> None:
    """Create all regions, locations, and connections."""

    # Create all regions
    region_names = ["Menu", "Forsaken City", "Intro Islands", "Granny Island", "Freeway Island", "North-West Girders Island", "North-East Feathers Island", "South-East House Island", "Badeline Tower Lower", "Badeline Tower Upper", "Badeline Island"]

    regions = {}
    for region_name in region_names:
        hint = None
        region = Region(region_name, player, multiworld, hint)
        regions[region_name] = region
        multiworld.regions.append(region)

    # Mark dynamically added regions (these won't appear in sphere log comparisons)
    try:
        _dynamically_added = DYNAMICALLY_ADDED_REGIONS
    except NameError:
        _dynamically_added = set()
    for region_name in _dynamically_added:
        if region_name in regions:
            regions[region_name].dynamically_added = True

    # Add locations to regions
    for location_name, location_data in location_table.items():
        region = regions[location_data.region]
        location = Celeste64WorldGenLocation(
            player,
            location_name,
            location_data.location_id,
            region
        )

        # Apply location properties from location_data
        if location_data.event:
            location.event = True
        if location_data.progress_type is not None:
            location.progress_type = location_data.progress_type
        if not location_data.show_in_spoiler:
            location.show_in_spoiler = False

        region.locations.append(location)

    # Create entrances
    _create_entrance(regions["Menu"], regions["Forsaken City"], "Menu -> Forsaken City")
    _create_entrance(regions["Forsaken City"], regions["Intro Islands"], "Forsaken City -> Intro Islands")
    _create_entrance(regions["Forsaken City"], regions["Granny Island"], "Forsaken City -> Granny Island")
    _create_entrance(regions["Forsaken City"], regions["Freeway Island"], "Forsaken City -> Freeway Island")
    _create_entrance(regions["Forsaken City"], regions["North-East Feathers Island"], "Forsaken City -> North-East Feathers Island")
    _create_entrance(regions["Forsaken City"], regions["South-East House Island"], "Forsaken City -> South-East House Island")
    _create_entrance(regions["Forsaken City"], regions["Badeline Tower Upper"], "Forsaken City -> Badeline Tower Upper")
    _create_entrance(regions["Forsaken City"], regions["Badeline Island"], "Forsaken City -> Badeline Island")
    _create_entrance(regions["Intro Islands"], regions["Granny Island"], "Intro Islands -> Granny Island")
    _create_entrance(regions["Granny Island"], regions["Freeway Island"], "Granny Island -> Freeway Island")
    _create_entrance(regions["Granny Island"], regions["North-West Girders Island"], "Granny Island -> North-West Girders Island")
    _create_entrance(regions["Granny Island"], regions["Badeline Tower Lower"], "Granny Island -> Badeline Tower Lower")
    _create_entrance(regions["Granny Island"], regions["South-East House Island"], "Granny Island -> South-East House Island")
    _create_entrance(regions["Freeway Island"], regions["Granny Island"], "Freeway Island -> Granny Island")
    _create_entrance(regions["Freeway Island"], regions["North-East Feathers Island"], "Freeway Island -> North-East Feathers Island")
    _create_entrance(regions["Freeway Island"], regions["North-West Girders Island"], "Freeway Island -> North-West Girders Island")
    _create_entrance(regions["North-West Girders Island"], regions["Freeway Island"], "North-West Girders Island -> Freeway Island")
    _create_entrance(regions["North-East Feathers Island"], regions["South-East House Island"], "North-East Feathers Island -> South-East House Island")
    _create_entrance(regions["North-East Feathers Island"], regions["Freeway Island"], "North-East Feathers Island -> Freeway Island")
    _create_entrance(regions["North-East Feathers Island"], regions["Badeline Tower Lower"], "North-East Feathers Island -> Badeline Tower Lower")
    _create_entrance(regions["North-East Feathers Island"], regions["Badeline Tower Upper"], "North-East Feathers Island -> Badeline Tower Upper")
    _create_entrance(regions["South-East House Island"], regions["North-East Feathers Island"], "South-East House Island -> North-East Feathers Island")
    _create_entrance(regions["South-East House Island"], regions["Granny Island"], "South-East House Island -> Granny Island")
    _create_entrance(regions["South-East House Island"], regions["Badeline Tower Lower"], "South-East House Island -> Badeline Tower Lower")
    _create_entrance(regions["Badeline Tower Lower"], regions["South-East House Island"], "Badeline Tower Lower -> South-East House Island")
    _create_entrance(regions["Badeline Tower Lower"], regions["North-East Feathers Island"], "Badeline Tower Lower -> North-East Feathers Island")
    _create_entrance(regions["Badeline Tower Lower"], regions["Granny Island"], "Badeline Tower Lower -> Granny Island")
    _create_entrance(regions["Badeline Tower Lower"], regions["Badeline Tower Upper"], "Badeline Tower Lower -> Badeline Tower Upper")
    _create_entrance(regions["Badeline Tower Upper"], regions["Badeline Island"], "Badeline Tower Upper -> Badeline Island")
    _create_entrance(regions["Badeline Tower Upper"], regions["Badeline Tower Lower"], "Badeline Tower Upper -> Badeline Tower Lower")
    _create_entrance(regions["Badeline Tower Upper"], regions["South-East House Island"], "Badeline Tower Upper -> South-East House Island")
    _create_entrance(regions["Badeline Tower Upper"], regions["North-East Feathers Island"], "Badeline Tower Upper -> North-East Feathers Island")
    _create_entrance(regions["Badeline Tower Upper"], regions["Granny Island"], "Badeline Tower Upper -> Granny Island")
    _create_entrance(regions["Badeline Island"], regions["Badeline Tower Upper"], "Badeline Island -> Badeline Tower Upper")
    _create_entrance(regions["Badeline Island"], regions["Granny Island"], "Badeline Island -> Granny Island")
    _create_entrance(regions["Badeline Island"], regions["Freeway Island"], "Badeline Island -> Freeway Island")


def _create_entrance(source: Region, target: Region, name: str) -> Entrance:
    """Helper to create and connect an entrance."""
    entrance = Entrance(source.player, name, source)
    entrance.connect(target)
    source.exits.append(entrance)
    return entrance
