"""
Access rules for VVVVVV WorldGen.

Auto-generated by world_generator using Rule Builder pattern.
The world class must inherit from RuleWorldMixin to use these rules.
"""

from typing import TYPE_CHECKING

from rule_builder import True_, False_

if TYPE_CHECKING:
    from worlds.AutoWorld import World


def set_rules(world: "World") -> None:
    """Set access rules for all locations and entrances.

    Uses world.set_rule() from RuleWorldMixin to properly resolve Rule Builder rules.
    """
    player = world.player
    multiworld = world.multiworld

    # Entrance rules
    world.set_rule(
        multiworld.get_entrance("Menu -> Laboratory", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("Menu -> The Tower", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("Menu -> Space Station 2", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("Menu -> Warp Zone", player),
        True_()
    )
    # Location rules
    world.set_rule(
        multiworld.get_location("NPC Trinket", player),
        ((True_()) & (True_()) & (True_())) | (True_())
    )

    world.set_rule(
        multiworld.get_location("V", player),
        (True_()) & (True_()) & (True_()) & (True_())
    )
