"""
Location definitions for MathProof2p2e4 WorldGen.

Auto-generated by world_generator.
"""

from typing import Dict, Optional
from BaseClasses import Location


class MathProof2p2e4WorldGenLocation(Location):
    """Location class for MathProof2p2e4 WorldGen."""
    game: str = "MathProof2p2e4 WorldGen"


class LocationData:
    """Data container for location definitions."""

    def __init__(self, region: str, name: str, location_id: Optional[int], event: bool = False,
                 progress_type: "LocationProgressType" = None, show_in_spoiler: bool = True):
        self.region = region
        self.name = name
        self.location_id = location_id
        self.event = event
        self.progress_type = progress_type
        self.show_in_spoiler = show_in_spoiler


location_table: Dict[str, LocationData] = {
    "Definition of 2": LocationData("Definitions", "Definition of 2", 200000001, False),
    "Definition of 3": LocationData("Definitions", "Definition of 3", 200000002, False),
    "Definition of 4": LocationData("Definitions", "Definition of 4", 200000003, False),
    "1 is Complex": LocationData("Axioms", "1 is Complex", 200000004, False),
    "2 is Complex": LocationData("BasicProperties", "2 is Complex", 200000005, False),
    "Equality Substitution Right": LocationData("ArithmeticOperations", "Equality Substitution Right", 200000006, False),
    "Equality Substitution Left": LocationData("ArithmeticOperations", "Equality Substitution Left", 200000007, False),
    "Addition Associativity": LocationData("ArithmeticOperations", "Addition Associativity", 200000008, False),
    "Triple Equality Transitivity": LocationData("ProofCompletion", "Triple Equality Transitivity", 200000009, False),
    "Final Equality": LocationData("ProofCompletion", "Final Equality", 200000010, False),
    "Theorem: 2+2=4": LocationData("ProofCompletion", "Theorem: 2+2=4", None, True),
}
