"""
Game options for The Wind Waker WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, DefaultOnToggle, Range, StartInventoryPool, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True


class UseCanonicalOptions(Toggle):
    """Use canonical options for seed 1.

    When enabled and generating seed 1, options will be loaded from the
    _worldgen_settings.json file to reproduce the exact original seed.
    This ensures deterministic output matching the original world export.
    """
    display_name = "Use Canonical Options"
    default = True

class AddShortcutWarpsBetweenDungeons(Toggle):
    """Option for Add Shortcut Warps Between Dungeons."""
    display_name = "Add Shortcut Warps Between Dungeons"

class ChestTypeMatchesContents(Toggle):
    """Option for Chest Type Matches Contents."""
    display_name = "Chest Type Matches Contents"

class DeathLink(Toggle):
    """Option for Death Link."""
    display_name = "Death Link"

class EnableTunerLogic(Toggle):
    """Option for Enable Tuner Logic."""
    display_name = "Enable Tuner Logic"

class HeroMode(Toggle):
    """Option for Hero Mode."""
    display_name = "Hero Mode"

class InstantTextBoxes(DefaultOnToggle):
    """Option for Instant Text Boxes."""
    display_name = "Instant Text Boxes"

class LogicObscurity(Choice):
    """Option for Obscure Tricks Required."""
    display_name = "Obscure Tricks Required"
    option_none = 0
    option_normal = 1
    option_hard = 2
    option_very_hard = 3
    default = 0

class LogicPrecision(Choice):
    """Option for Precise Tricks Required."""
    display_name = "Precise Tricks Required"
    option_none = 0
    option_normal = 1
    option_hard = 2
    option_very_hard = 3
    default = 0

class MixEntrances(Choice):
    """Option for Mix Entrances."""
    display_name = "Mix Entrances"
    option_separate_pools = 0
    option_mix_pools = 1
    default = 0

class NumRequiredBosses(Range):
    """Option for Number of Required Bosses."""
    display_name = "Number of Required Bosses"
    range_start = 1
    range_end = 6
    default = 4

class ProgressionBattlesquid(Toggle):
    """Option for Battlesquid Minigame."""
    display_name = "Battlesquid Minigame"

class ProgressionBigOctosGunboats(Toggle):
    """Option for Big Octos and Gunboats."""
    display_name = "Big Octos and Gunboats"

class ProgressionCombatSecretCaves(Toggle):
    """Option for Combat Secret Caves."""
    display_name = "Combat Secret Caves"

class ProgressionDungeonSecrets(Toggle):
    """Option for Dungeon Secrets."""
    display_name = "Dungeon Secrets"

class ProgressionDungeons(DefaultOnToggle):
    """Option for Dungeons."""
    display_name = "Dungeons"

class ProgressionExpensivePurchases(DefaultOnToggle):
    """Option for Expensive Purchases."""
    display_name = "Expensive Purchases"

class ProgressionEyeReefChests(Toggle):
    """Option for Eye Reef Chests."""
    display_name = "Eye Reef Chests"

class ProgressionFreeGifts(DefaultOnToggle):
    """Option for Free Gifts."""
    display_name = "Free Gifts"

class ProgressionGreatFairies(DefaultOnToggle):
    """Option for Great Fairies."""
    display_name = "Great Fairies"

class ProgressionIslandPuzzles(Toggle):
    """Option for Island Puzzles."""
    display_name = "Island Puzzles"

class ProgressionLongSidequests(Toggle):
    """Option for Long Sidequests."""
    display_name = "Long Sidequests"

class ProgressionMail(Toggle):
    """Option for Mail."""
    display_name = "Mail"

class ProgressionMinigames(Toggle):
    """Option for Minigames."""
    display_name = "Minigames"

class ProgressionMisc(Toggle):
    """Option for Miscellaneous."""
    display_name = "Miscellaneous"

class ProgressionPlatformsRafts(Toggle):
    """Option for Lookout Platforms and Rafts."""
    display_name = "Lookout Platforms and Rafts"

class ProgressionPuzzleSecretCaves(DefaultOnToggle):
    """Option for Puzzle Secret Caves."""
    display_name = "Puzzle Secret Caves"

class ProgressionSavageLabyrinth(Toggle):
    """Option for Savage Labyrinth."""
    display_name = "Savage Labyrinth"

class ProgressionShortSidequests(Toggle):
    """Option for Short Sidequests."""
    display_name = "Short Sidequests"

class ProgressionSpoilsTrading(Toggle):
    """Option for Spoils Trading."""
    display_name = "Spoils Trading"

class ProgressionSubmarines(Toggle):
    """Option for Submarines."""
    display_name = "Submarines"

class ProgressionTingleChests(Toggle):
    """Option for Tingle Chests."""
    display_name = "Tingle Chests"

class ProgressionTreasureCharts(Toggle):
    """Option for Sunken Treasure (From Treasure Charts)."""
    display_name = "Sunken Treasure (From Treasure Charts)"

class ProgressionTriforceCharts(Toggle):
    """Option for Sunken Treasure (From Triforce Charts)."""
    display_name = "Sunken Treasure (From Triforce Charts)"

class RandomizeBigkeys(Choice):
    """Option for Randomize Big Keys."""
    display_name = "Randomize Big Keys"
    option_startwith = 0
    option_vanilla = 1
    option_dungeon = 2
    option_any_dungeon = 3
    option_local = 4
    option_keylunacy = 5
    default = 2

class RandomizeBossEntrances(Toggle):
    """Option for Randomize Nested Bosses."""
    display_name = "Randomize Nested Bosses"

class RandomizeCharts(Toggle):
    """Option for Randomize Charts."""
    display_name = "Randomize Charts"

class RandomizeDungeonEntrances(Toggle):
    """Option for Randomize Dungeons."""
    display_name = "Randomize Dungeons"

class RandomizeEnemies(Toggle):
    """Option for Randomize Enemies."""
    display_name = "Randomize Enemies"

class RandomizeFairyFountainEntrances(Toggle):
    """Option for Randomize Fairy Fountains."""
    display_name = "Randomize Fairy Fountains"

class RandomizeMapcompass(Choice):
    """Option for Randomize Maps & Compasses."""
    display_name = "Randomize Maps & Compasses"
    option_startwith = 0
    option_vanilla = 1
    option_dungeon = 2
    option_any_dungeon = 3
    option_local = 4
    option_keylunacy = 5
    default = 2

class RandomizeMinibossEntrances(Toggle):
    """Option for Randomize Nested Minibosses."""
    display_name = "Randomize Nested Minibosses"

class RandomizeSecretCaveEntrances(Toggle):
    """Option for Randomize Secret Caves."""
    display_name = "Randomize Secret Caves"

class RandomizeSecretCaveInnerEntrances(Toggle):
    """Option for Randomize Inner Secret Caves."""
    display_name = "Randomize Inner Secret Caves"

class RandomizeSmallkeys(Choice):
    """Option for Randomize Small Keys."""
    display_name = "Randomize Small Keys"
    option_startwith = 0
    option_vanilla = 1
    option_dungeon = 2
    option_any_dungeon = 3
    option_local = 4
    option_keylunacy = 5
    default = 2

class RandomizeStartingIsland(Toggle):
    """Option for Randomize Starting Island."""
    display_name = "Randomize Starting Island"

class RemoveMusic(Toggle):
    """Option for Remove Music."""
    display_name = "Remove Music"

class RequiredBosses(Toggle):
    """Option for Required Bosses Mode."""
    display_name = "Required Bosses Mode"

class RevealFullSeaChart(DefaultOnToggle):
    """Option for Reveal Full Sea Chart."""
    display_name = "Reveal Full Sea Chart"

class SkipRematchBosses(DefaultOnToggle):
    """Option for Skip Boss Rematches."""
    display_name = "Skip Boss Rematches"

class StartInventoryFromPool(StartInventoryPool):
    """Start inventory from pool for Start Inventory from Pool."""

class SwiftSail(DefaultOnToggle):
    """Option for Swift Sail."""
    display_name = "Swift Sail"

class SwordMode(Choice):
    """Option for Sword Mode."""
    display_name = "Sword Mode"
    option_start_with_sword = 0
    option_no_starting_sword = 1
    option_swords_optional = 2
    option_swordless = 3
    default = 0


@dataclass
class TheWindWakerWorldGenOptions(PerGameCommonOptions):
    """Options for The Wind Waker WorldGen."""
    randomize_items: RandomizeItems
    use_canonical_options: UseCanonicalOptions
    add_shortcut_warps_between_dungeons: AddShortcutWarpsBetweenDungeons
    chest_type_matches_contents: ChestTypeMatchesContents
    death_link: DeathLink
    enable_tuner_logic: EnableTunerLogic
    hero_mode: HeroMode
    instant_text_boxes: InstantTextBoxes
    logic_obscurity: LogicObscurity
    logic_precision: LogicPrecision
    mix_entrances: MixEntrances
    num_required_bosses: NumRequiredBosses
    progression_battlesquid: ProgressionBattlesquid
    progression_big_octos_gunboats: ProgressionBigOctosGunboats
    progression_combat_secret_caves: ProgressionCombatSecretCaves
    progression_dungeon_secrets: ProgressionDungeonSecrets
    progression_dungeons: ProgressionDungeons
    progression_expensive_purchases: ProgressionExpensivePurchases
    progression_eye_reef_chests: ProgressionEyeReefChests
    progression_free_gifts: ProgressionFreeGifts
    progression_great_fairies: ProgressionGreatFairies
    progression_island_puzzles: ProgressionIslandPuzzles
    progression_long_sidequests: ProgressionLongSidequests
    progression_mail: ProgressionMail
    progression_minigames: ProgressionMinigames
    progression_misc: ProgressionMisc
    progression_platforms_rafts: ProgressionPlatformsRafts
    progression_puzzle_secret_caves: ProgressionPuzzleSecretCaves
    progression_savage_labyrinth: ProgressionSavageLabyrinth
    progression_short_sidequests: ProgressionShortSidequests
    progression_spoils_trading: ProgressionSpoilsTrading
    progression_submarines: ProgressionSubmarines
    progression_tingle_chests: ProgressionTingleChests
    progression_treasure_charts: ProgressionTreasureCharts
    progression_triforce_charts: ProgressionTriforceCharts
    randomize_bigkeys: RandomizeBigkeys
    randomize_boss_entrances: RandomizeBossEntrances
    randomize_charts: RandomizeCharts
    randomize_dungeon_entrances: RandomizeDungeonEntrances
    randomize_enemies: RandomizeEnemies
    randomize_fairy_fountain_entrances: RandomizeFairyFountainEntrances
    randomize_mapcompass: RandomizeMapcompass
    randomize_miniboss_entrances: RandomizeMinibossEntrances
    randomize_secret_cave_entrances: RandomizeSecretCaveEntrances
    randomize_secret_cave_inner_entrances: RandomizeSecretCaveInnerEntrances
    randomize_smallkeys: RandomizeSmallkeys
    randomize_starting_island: RandomizeStartingIsland
    remove_music: RemoveMusic
    required_bosses: RequiredBosses
    reveal_full_sea_chart: RevealFullSeaChart
    skip_rematch_bosses: SkipRematchBosses
    start_inventory_from_pool: StartInventoryFromPool
    swift_sail: SwiftSail
    sword_mode: SwordMode
