"""
DepGraph WorldGen world implementation for Archipelago.

Auto-generated by world_generator.
"""
import json
import os

from typing import ClassVar, Dict, List, Set, Any, TYPE_CHECKING
from BaseClasses import Item, ItemClassification, Tutorial
from worlds.AutoWorld import WebWorld, World
from rule_builder import RuleWorldMixin

if TYPE_CHECKING:
    from BaseClasses import CollectionState, MultiWorld

from .Items import item_table, ItemData, DepGraphWorldGenItem
from .Locations import location_table, DepGraphWorldGenLocation
from .Options import DepGraphWorldGenOptions
from .Regions import create_regions
from .Rules import set_rules


# Item pool counts from original generation (excluding locked placements)
ITEMPOOL_COUNTS: Dict[str, int] = {
    "Logging": 1,
    "Carpentry": 1,
    "Mining": 1,
    "Smelting": 1,
    "Metalworking": 1,
    "Architecture": 1,
    "Engineering": 1,
    "Steam Power": 1,
    "Industrial Age": 1,
}

# Locked placements - items that must be placed via place_locked_item
LOCKED_PLACEMENTS: Dict[str, str] = {
    "Proved Statement 2": "Event: Logging",
    "Proved Statement 3": "Event: Carpentry",
    "Proved Statement 4": "Event: Mining",
    "Proved Statement 5": "Event: Smelting",
    "Proved Statement 6": "Event: Metalworking",
    "Proved Statement 7": "Event: Architecture",
    "Proved Statement 8": "Event: Engineering",
    "Proved Statement 9": "Event: Steam Power",
    "Proved Statement 10": "Event: Industrial Age",
}

# Starting items - items the player begins with (precollected)
STARTING_ITEMS: Dict[str, int] = {
    "Basic Tools": 1,
    "Event: Basic Tools": 1,
}


class DepGraphWorldGenWeb(WebWorld):
    """Web interface for DepGraph WorldGen."""
    theme = "grass"
    game_info_languages: List[str] = ['en']
    tutorials = [
        Tutorial(
            "Multiworld Setup Guide",
            "A guide to setting up DepGraph for MultiWorld.",
            "English",
            "setup_en.md",
            "setup/en",
            ["Archipelago Team"]
        )
    ]


class DepGraphWorld(RuleWorldMixin, World):
    """
    Turn any directed acyclic graph into an Archipelago world!
    Each node is both a location (unlocking it) and an item (ability to use it).
    Navigate dependency edges across the multiworld to reach the final node.
    """

    game: ClassVar[str] = "DepGraph WorldGen"
    web: ClassVar[WebWorld] = DepGraphWorldGenWeb()

    options_dataclass = DepGraphWorldGenOptions
    options: DepGraphWorldGenOptions

    # Disable rule caching - requires CollectionState.rule_builder_cache from PR #5048
    rule_caching_enabled: ClassVar[bool] = False

    item_name_to_id: ClassVar[Dict[str, int]] = {
        name: data.id for name, data in item_table.items() if data.id is not None
    }

    # Expose item_table as item_name_to_item for exporter compatibility
    # This allows the exporter handler to find item classifications
    item_name_to_item: ClassVar[Dict[str, "ItemData"]] = item_table

    location_name_to_id: ClassVar[Dict[str, int]] = {
        name: data.location_id for name, data in location_table.items()
        if data.location_id is not None
    }

    item_name_groups: ClassVar[Dict[str, frozenset]] = {
        "Everything": frozenset(["Statement 11", "Statement 12", "Statement 13", "Statement 14", "Statement 15", "Statement 16", "Statement 17", "Statement 18", "Statement 19", "Statement 20", "Statement 21", "Statement 22", "Statement 23", "Statement 24", "Statement 25", "Statement 26", "Statement 27", "Statement 28", "Statement 29", "Statement 30", "Statement 31", "Statement 32", "Statement 33", "Statement 34", "Statement 35", "Statement 36", "Statement 37", "Statement 38", "Statement 39", "Statement 40", "Statement 41", "Statement 42", "Statement 43", "Statement 44", "Statement 45", "Statement 46", "Statement 47", "Statement 48", "Statement 49", "Statement 50", "Statement 51", "Statement 52", "Statement 53", "Statement 54", "Statement 55", "Statement 56", "Statement 57", "Statement 58", "Statement 59", "Statement 60", "Statement 61", "Statement 62", "Statement 63", "Statement 64", "Statement 65", "Statement 66", "Statement 67", "Statement 68", "Statement 69", "Statement 70", "Statement 71", "Statement 72", "Statement 73", "Statement 74", "Statement 75", "Statement 76", "Statement 77", "Statement 78", "Statement 79", "Statement 80", "Statement 81", "Statement 82", "Statement 83", "Statement 84", "Statement 85", "Statement 86", "Statement 87", "Statement 88", "Statement 89", "Statement 90", "Statement 91", "Statement 92", "Statement 93", "Statement 94", "Statement 95", "Statement 96", "Statement 97", "Statement 98", "Statement 99", "Statement 100", "Basic Tools", "Logging", "Carpentry", "Mining", "Smelting", "Metalworking", "Architecture", "Engineering", "Steam Power", "Industrial Age"]),
        "Statements": frozenset(["Statement 11", "Statement 12", "Statement 13", "Statement 14", "Statement 15", "Statement 16", "Statement 17", "Statement 18", "Statement 19", "Statement 20", "Statement 21", "Statement 22", "Statement 23", "Statement 24", "Statement 25", "Statement 26", "Statement 27", "Statement 28", "Statement 29", "Statement 30", "Statement 31", "Statement 32", "Statement 33", "Statement 34", "Statement 35", "Statement 36", "Statement 37", "Statement 38", "Statement 39", "Statement 40", "Statement 41", "Statement 42", "Statement 43", "Statement 44", "Statement 45", "Statement 46", "Statement 47", "Statement 48", "Statement 49", "Statement 50", "Statement 51", "Statement 52", "Statement 53", "Statement 54", "Statement 55", "Statement 56", "Statement 57", "Statement 58", "Statement 59", "Statement 60", "Statement 61", "Statement 62", "Statement 63", "Statement 64", "Statement 65", "Statement 66", "Statement 67", "Statement 68", "Statement 69", "Statement 70", "Statement 71", "Statement 72", "Statement 73", "Statement 74", "Statement 75", "Statement 76", "Statement 77", "Statement 78", "Statement 79", "Statement 80", "Statement 81", "Statement 82", "Statement 83", "Statement 84", "Statement 85", "Statement 86", "Statement 87", "Statement 88", "Statement 89", "Statement 90", "Statement 91", "Statement 92", "Statement 93", "Statement 94", "Statement 95", "Statement 96", "Statement 97", "Statement 98", "Statement 99", "Statement 100", "Basic Tools", "Logging", "Carpentry", "Mining", "Smelting", "Metalworking", "Architecture", "Engineering", "Steam Power", "Industrial Age"]),
    }

    # Placements are deterministically reproduced by world generator
    is_canonical: ClassVar[bool] = True

    # Frontend preset button label (e.g., "canth s4")
    preset_label: ClassVar[str] = "tech_tree s1"

    # Canonical item placements - where items belong in the "vanilla" game
    # Used by exporter to distinguish canonical placements from always-locked items
    canonical_placements: ClassVar[Dict[str, str]] = {
        "Logging": "Logging",
        "Carpentry": "Carpentry",
        "Mining": "Mining",
        "Smelting": "Smelting",
        "Metalworking": "Metalworking",
        "Architecture": "Architecture",
        "Engineering": "Engineering",
        "Steam Power": "Steam Power",
    }

    # Canonical placement advancement status - for items with mixed classifications
    # True = progression, False = useful/filler. Used to select correct item copy during placement.
    canonical_placement_advancements: ClassVar[Dict[str, bool]] = {
        "Logging": True,
        "Proved Statement 2": True,
        "Carpentry": True,
        "Proved Statement 3": True,
        "Mining": True,
        "Proved Statement 4": True,
        "Smelting": True,
        "Proved Statement 5": True,
        "Metalworking": True,
        "Proved Statement 6": True,
        "Architecture": True,
        "Proved Statement 7": True,
        "Engineering": True,
        "Proved Statement 8": True,
        "Steam Power": True,
        "Proved Statement 9": True,
        "Industrial Age": True,
        "Proved Statement 10": True,
    }

    def __init__(self, multiworld: "MultiWorld", player: int):
        super().__init__(multiworld, player)
        # Game-specific world attributes
        self.world_class_name = 'DepGraphWorld'
        self.graph_structure = {'label_to_index': {'basic_tools': 1, 'logging': 2, 'carpentry': 3, 'mining': 4, 'smelting': 5, 'metalworking': 6, 'architecture': 7, 'engineering': 8, 'steam_power': 9, 'industrial_age': 10}, 'title': 'Tech Tree'}
        self.num_statements = 10
        self.preset_label = 'tech_tree s1'
        self.canonical_placements = {'Logging': 'Logging', 'Carpentry': 'Carpentry', 'Mining': 'Mining', 'Smelting': 'Smelting', 'Metalworking': 'Metalworking', 'Architecture': 'Architecture', 'Engineering': 'Engineering', 'Steam Power': 'Steam Power'}
        self.location_dependencies = {'Proved Statement 2': ['Basic Tools', 'Event: Basic Tools'], 'Proved Statement 3': ['Logging', 'Event: Logging'], 'Proved Statement 4': ['Basic Tools', 'Event: Basic Tools'], 'Proved Statement 5': ['Mining', 'Event: Mining'], 'Proved Statement 6': ['Carpentry', 'Event: Carpentry', 'Smelting', 'Event: Smelting'], 'Proved Statement 7': ['Metalworking', 'Event: Metalworking'], 'Proved Statement 8': ['Metalworking', 'Event: Metalworking'], 'Proved Statement 9': ['Architecture', 'Event: Architecture', 'Engineering', 'Event: Engineering'], 'Proved Statement 10': ['Steam Power', 'Event: Steam Power'], 'Logging': ['Basic Tools', 'Event: Basic Tools'], 'Carpentry': ['Logging', 'Event: Logging'], 'Mining': ['Basic Tools', 'Event: Basic Tools'], 'Smelting': ['Mining', 'Event: Mining'], 'Metalworking': ['Carpentry', 'Event: Carpentry', 'Smelting', 'Event: Smelting'], 'Architecture': ['Metalworking', 'Event: Metalworking'], 'Engineering': ['Metalworking', 'Event: Metalworking'], 'Steam Power': ['Architecture', 'Event: Architecture', 'Engineering', 'Event: Engineering'], 'Industrial Age': ['Steam Power', 'Event: Steam Power']}
        self.entrance_dependencies = {'From basic_tools to logging': ['Basic Tools', 'Event: Basic Tools'], 'From logging to carpentry': ['Logging', 'Event: Logging'], 'From basic_tools to mining': ['Basic Tools', 'Event: Basic Tools'], 'From mining to smelting': ['Mining', 'Event: Mining'], 'From carpentry to metalworking': ['Carpentry', 'Event: Carpentry', 'Smelting', 'Event: Smelting'], 'From smelting to metalworking': ['Carpentry', 'Event: Carpentry', 'Smelting', 'Event: Smelting'], 'From metalworking to architecture': ['Metalworking', 'Event: Metalworking'], 'From metalworking to engineering': ['Metalworking', 'Event: Metalworking'], 'From architecture to steam_power': ['Architecture', 'Event: Architecture', 'Engineering', 'Event: Engineering'], 'From engineering to steam_power': ['Architecture', 'Event: Architecture', 'Engineering', 'Event: Engineering'], 'From steam_power to industrial_age': ['Steam Power', 'Event: Steam Power']}
        self.exit_dependencies = {'From basic_tools to logging': ['Basic Tools', 'Event: Basic Tools'], 'From basic_tools to mining': ['Basic Tools', 'Event: Basic Tools'], 'From logging to carpentry': ['Logging', 'Event: Logging'], 'From carpentry to metalworking': ['Carpentry', 'Event: Carpentry', 'Smelting', 'Event: Smelting'], 'From mining to smelting': ['Mining', 'Event: Mining'], 'From smelting to metalworking': ['Carpentry', 'Event: Carpentry', 'Smelting', 'Event: Smelting'], 'From metalworking to architecture': ['Metalworking', 'Event: Metalworking'], 'From metalworking to engineering': ['Metalworking', 'Event: Metalworking'], 'From architecture to steam_power': ['Architecture', 'Event: Architecture', 'Engineering', 'Event: Engineering'], 'From engineering to steam_power': ['Architecture', 'Event: Architecture', 'Engineering', 'Event: Engineering'], 'From steam_power to industrial_age': ['Steam Power', 'Event: Steam Power']}
        self.world_description = 'Turn any directed acyclic graph into an Archipelago world!\nEach node is both a location (unlocking it) and an item (ability to use it).\nNavigate dependency edges across the multiworld to reach the final node.'
        self.slot_data = {'proof_structure': {1: {'label': 'basic_tools', 'expression': 'Basic Tools', 'dependencies': [], 'full_text': 'basic_tools: Craft primitive tools from stone and wood'}, 2: {'label': 'logging', 'expression': 'Logging', 'dependencies': [1], 'full_text': 'logging: Harvest timber from forests'}, 3: {'label': 'carpentry', 'expression': 'Carpentry', 'dependencies': [2], 'full_text': 'carpentry: Shape wood into useful structures'}, 4: {'label': 'mining', 'expression': 'Mining', 'dependencies': [1], 'full_text': 'mining: Extract ores from the earth'}, 5: {'label': 'smelting', 'expression': 'Smelting', 'dependencies': [4], 'full_text': 'smelting: Smelt ores into metal ingots'}, 6: {'label': 'metalworking', 'expression': 'Metalworking', 'dependencies': [3, 5], 'full_text': 'metalworking: Forge metal into advanced components'}, 7: {'label': 'architecture', 'expression': 'Architecture', 'dependencies': [6], 'full_text': 'architecture: Design and construct buildings'}, 8: {'label': 'engineering', 'expression': 'Engineering', 'dependencies': [6], 'full_text': 'engineering: Apply scientific principles to construction'}, 9: {'label': 'steam_power', 'expression': 'Steam Power', 'dependencies': [7, 8], 'full_text': 'steam_power: Harness the power of steam engines'}, 10: {'label': 'industrial_age', 'expression': 'Industrial Age', 'dependencies': [9], 'full_text': 'industrial_age: Enter the era of mass production'}}, 'starting_statements': [1], 'theorem': 'Tech Tree', 'randomize_items': 1, 'vanilla_placement': 0}

    # Canonical seed for deterministic placement
    CANONICAL_SEED: ClassVar[int] = 1

    def generate_early(self) -> None:
        """Push starting items and load canonical options for canonical seed."""
        self._push_starting_items()
        # Set preset_label for exporter: use class-level label as base, append seed/vanilla suffix
        base_label = getattr(self.__class__, 'preset_label', '')
        if base_label:
            base = base_label.split()[0] if ' ' in base_label else base_label
            is_vanilla = getattr(self.__class__, 'is_vanilla', False)
            self.preset_label = f"{base} v" if is_vanilla else f"{base} s{self.multiworld.seed}"
        if self.multiworld.seed == self.CANONICAL_SEED:
            self.options.randomize_items.value = False
            if self.options.use_canonical_options.value:
                self._load_canonical_options()

    def _load_canonical_options(self) -> None:
        """Load options from _worldgen_options.json for canonical seed generation.

        This ensures that when generating the canonical seed, the same options are used
        as in the original export, producing identical output.
        """
        # Find the options file in the same directory as this module
        world_dir = os.path.dirname(os.path.abspath(__file__))
        options_path = os.path.join(world_dir, '_worldgen_options.json')

        if not os.path.exists(options_path):
            return  # No options file, use defaults

        try:
            with open(options_path, 'r') as f:
                options_data = json.load(f)
        except (json.JSONDecodeError, IOError):
            return  # Can't read options, use defaults

        if not options_data:
            return

        # Map option names from JSON (snake_case) to option attributes
        for option_name, option_value in options_data.items():
            # Get the option attribute if it exists
            if not hasattr(self.options, option_name):
                continue

            option_obj = getattr(self.options, option_name)

            # Handle different option types
            if isinstance(option_value, bool):
                # Toggle options - preserve as boolean to match original world behavior
                # (Original worlds set value = False directly, not value = 0)
                option_obj.value = option_value
            elif isinstance(option_value, int):
                # Range or Choice options with numeric value
                option_obj.value = option_value
            elif isinstance(option_value, str):
                # Choice options with string value - need to look up the value
                # Try to find the corresponding option_* attribute
                option_attr_name = f"option_{option_value}"
                if hasattr(option_obj.__class__, option_attr_name):
                    option_obj.value = getattr(option_obj.__class__, option_attr_name)
                else:
                    # Try to use the string directly if the class has a from_text method
                    try:
                        option_obj.value = option_obj.__class__.from_text(option_value).value
                    except (ValueError, KeyError, AttributeError):
                        pass  # Keep existing value

    def create_regions(self) -> None:
        """Create regions, locations, and connections."""
        create_regions(self.multiworld, self.player)

    def set_rules(self) -> None:
        """Set access rules."""
        set_rules(self)

    def create_items(self) -> None:
        """Create randomized item pool."""
        # First, place any locked items
        self._place_locked_items()

        # Then create the random item pool
        item_pool = []

        for item_name, count in ITEMPOOL_COUNTS.items():
            # Skip event items
            if item_name not in item_table or item_table[item_name].id is None:
                continue

            item_data = item_table[item_name]

            # Check for mixed classification items (e.g., some progression, some filler)
            classification_counts = getattr(item_data, 'classification_counts', None)
            if classification_counts:
                # Create items with per-classification counts
                classification_map = {
                    'progression': ItemClassification.progression,
                    'progression_skip_balancing': ItemClassification.progression_skip_balancing,
                    'useful': ItemClassification.useful,
                    'trap': ItemClassification.trap,
                    'filler': ItemClassification.filler,
                }
                for classification_name, class_count in classification_counts.items():
                    classification = classification_map.get(classification_name, ItemClassification.filler)
                    for _ in range(class_count):
                        item = DepGraphWorldGenItem(
                            item_name,
                            classification,
                            item_data.id,
                            self.player
                        )
                        item_pool.append(item)
            else:
                # Standard case: all items have the same classification
                for _ in range(count):
                    item = DepGraphWorldGenItem(
                        item_name,
                        item_data.classification,
                        item_data.id,
                        self.player
                    )
                    item_pool.append(item)

        self.multiworld.itempool += item_pool

    def _place_locked_items(self) -> None:
        """Place items that must be in specific locations (locked placements)."""
        for location_name, item_name in LOCKED_PLACEMENTS.items():
            if item_name and item_name in item_table:
                location = self.multiworld.get_location(location_name, self.player)
                item_data = item_table[item_name]
                item = DepGraphWorldGenItem(
                    item_name,
                    item_data.classification,
                    item_data.id,
                    self.player
                )
                location.place_locked_item(item)
                # If the location is an event, mark the item as an event too
                # (matches original world behavior where item.code = None for events)
                if getattr(location, 'event', False) or location.address is None:
                    item.code = None

    def _push_starting_items(self) -> None:
        """Push starting items as precollected (for state counters like coins)."""
        for item_name, count in STARTING_ITEMS.items():
            if item_name in item_table:
                for _ in range(count):
                    item = self.create_item(item_name)
                    self.multiworld.push_precollected(item)

    def generate_basic(self) -> None:
        """Set completion condition."""
        self.multiworld.completion_condition[self.player] = \
            lambda state: state.has("Event: Industrial Age", self.player)

    def pre_fill(self) -> None:
        """Pre-fill items if not randomizing or when tracking.

        During tracking (generation_is_fake=True), we always place canonical items
        so that location_item_name() checks work correctly for self-locking rules.
        """
        if not self.options.randomize_items.value or getattr(self.multiworld, 'generation_is_fake', False):
            self._place_original_items()

    def _place_original_items(self) -> None:
        """Place items in their canonical locations when not randomized.

        Process advancement locations first to ensure they get advancement items.
        This is critical for cross-validation in spoiler tests, where item
        advancement flags determine whether items are counted.
        """
        # Two-pass placement: first advancement locations, then the rest
        advancement_locs = getattr(self, 'advancement_locations', set())

        # Sort locations to process advancement locations first
        sorted_placements = sorted(
            self.canonical_placements.items(),
            key=lambda x: 0 if x[0] in advancement_locs else 1
        )

        for location_name, item_name in sorted_placements:
            location = self.multiworld.get_location(location_name, self.player)

            # Skip if already filled (e.g., by _place_locked_items or generate_basic)
            if location.item is not None:
                continue

            # Check if we have expected advancement status for this location (for mixed-class items)
            # This ensures we match the original's progression distribution
            expected_advancement = None
            if hasattr(self, 'canonical_placement_advancements'):
                expected_advancement = self.canonical_placement_advancements.get(location_name)

            # Try to find and use an item from the pool (preserves correct classification)
            # Note: Must use index-based removal because Item.__eq__ only compares name/player,
            # not classification, so list.remove() would remove the wrong item
            item = None
            progression_idx = None
            filler_idx = None

            for idx, pool_item in enumerate(self.multiworld.itempool):
                if pool_item.name == item_name and pool_item.player == self.player:
                    if pool_item.advancement:
                        if progression_idx is None:
                            progression_idx = idx
                    else:
                        if filler_idx is None:
                            filler_idx = idx

                    # If we found both types, stop searching
                    if progression_idx is not None and filler_idx is not None:
                        break

            # Select item based on expected advancement status or fall back to progression-first
            if expected_advancement is True and progression_idx is not None:
                chosen_idx = progression_idx
            elif expected_advancement is False and filler_idx is not None:
                chosen_idx = filler_idx
            elif progression_idx is not None:
                # Default: prefer progression
                chosen_idx = progression_idx
            else:
                chosen_idx = filler_idx

            if chosen_idx is not None:
                item = self.multiworld.itempool.pop(chosen_idx)
            else:
                # Fall back to creating a new item if not found in pool
                item = self.create_item(item_name)

            # Place item without setting locked=True, so the exporter writes
            # locked=false in rules.json (matching the original world's behavior).
            # place_locked_item() would mark these as locked, causing the frontend
            # spoiler test to skip them.
            location.item = item
            item.location = location

    def create_item(self, name: str) -> Item:
        """Create an item by name."""
        data = item_table[name]
        item = DepGraphWorldGenItem(name, data.classification, data.id, self.player)
        return item


    def fill_slot_data(self) -> Dict[str, Any]:
        """Return data for the client."""
        return {
            "proof_structure": {1: {'label': 'basic_tools', 'expression': 'Basic Tools', 'dependencies': [], 'full_text': 'basic_tools: Craft primitive tools from stone and wood'}, 2: {'label': 'logging', 'expression': 'Logging', 'dependencies': [1], 'full_text': 'logging: Harvest timber from forests'}, 3: {'label': 'carpentry', 'expression': 'Carpentry', 'dependencies': [2], 'full_text': 'carpentry: Shape wood into useful structures'}, 4: {'label': 'mining', 'expression': 'Mining', 'dependencies': [1], 'full_text': 'mining: Extract ores from the earth'}, 5: {'label': 'smelting', 'expression': 'Smelting', 'dependencies': [4], 'full_text': 'smelting: Smelt ores into metal ingots'}, 6: {'label': 'metalworking', 'expression': 'Metalworking', 'dependencies': [3, 5], 'full_text': 'metalworking: Forge metal into advanced components'}, 7: {'label': 'architecture', 'expression': 'Architecture', 'dependencies': [6], 'full_text': 'architecture: Design and construct buildings'}, 8: {'label': 'engineering', 'expression': 'Engineering', 'dependencies': [6], 'full_text': 'engineering: Apply scientific principles to construction'}, 9: {'label': 'steam_power', 'expression': 'Steam Power', 'dependencies': [7, 8], 'full_text': 'steam_power: Harness the power of steam engines'}, 10: {'label': 'industrial_age', 'expression': 'Industrial Age', 'dependencies': [9], 'full_text': 'industrial_age: Enter the era of mass production'}},
            "starting_statements": [1],
            "theorem": "Tech Tree",
            "randomize_items": self.options.randomize_items.value,
            "vanilla_placement": 0,
        }
