"""
Game options for Sonic Adventure 2 Battle WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, DefaultOnToggle, Range, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True


class UseCanonicalOptions(Toggle):
    """Use canonical options for seed 1.

    When enabled and generating seed 1, options will be loaded from the
    _worldgen_settings.json file to reproduce the exact original seed.
    This ensures deterministic output matching the original world export.
    """
    display_name = "Use Canonical Options"
    default = True

class Animalsanity(Toggle):
    """Option for Animalsanity."""
    display_name = "Animalsanity"

class BeeTrapWeight(Choice):
    """Option for Bee Trap Weight."""
    display_name = "Bee Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class Beetlesanity(DefaultOnToggle):
    """Option for Beetlesanity."""
    display_name = "Beetlesanity"

class BigFishingDifficulty(Choice):
    """Option for Big Fishing Difficulty."""
    display_name = "Big Fishing Difficulty"
    option_easy = 0
    option_medium = 1
    option_hard = 2
    option_chaos = 3
    default = 1

class Bigsanity(Toggle):
    """Option for Bigsanity."""
    display_name = "Bigsanity"

class BlackMarketPriceMultiplier(Range):
    """Option for Black Market Price Multiplier."""
    display_name = "Black Market Price Multiplier"
    range_start = 0
    range_end = 40
    default = 1

class BlackMarketSlots(Range):
    """Option for Black Market Slots."""
    display_name = "Black Market Slots"
    range_start = 0
    range_end = 64
    default = 0

class BlackMarketUnlockCosts(Choice):
    """Option for Black Market Unlock Costs."""
    display_name = "Black Market Unlock Costs"
    option_low = 0
    option_medium = 1
    option_high = 2
    default = 1

class BossRushShuffle(Choice):
    """Option for Boss Rush Shuffle."""
    display_name = "Boss Rush Shuffle"
    option_vanilla = 0
    option_shuffled = 1
    option_chaos = 2
    option_singularity = 3
    default = 0

class BreakoutTrapWeight(Choice):
    """Option for Breakout Trap Weight."""
    display_name = "Breakout Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class CannonsCoreMission2(DefaultOnToggle):
    """Option for Cannon's Core Mission 2."""
    display_name = "Cannon's Core Mission 2"

class CannonsCoreMission3(DefaultOnToggle):
    """Option for Cannon's Core Mission 3."""
    display_name = "Cannon's Core Mission 3"

class CannonsCoreMission4(DefaultOnToggle):
    """Option for Cannon's Core Mission 4."""
    display_name = "Cannon's Core Mission 4"

class CannonsCoreMission5(DefaultOnToggle):
    """Option for Cannon's Core Mission 5."""
    display_name = "Cannon's Core Mission 5"

class CannonsCoreMissionCount(Range):
    """Option for Cannon's Core Mission Count."""
    display_name = "Cannon's Core Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class ChaoAnimalParts(Toggle):
    """Option for Chao Animal Parts."""
    display_name = "Chao Animal Parts"

class ChaoEntranceRandomization(Toggle):
    """Option for Chao Entrance Randomization."""
    display_name = "Chao Entrance Randomization"

class ChaoKarateDifficulty(Choice):
    """Option for Chao Karate Difficulty."""
    display_name = "Chao Karate Difficulty"
    option_none = 0
    option_beginner = 1
    option_standard = 2
    option_expert = 3
    option_super = 4
    default = 0

class ChaoKindergarten(Choice):
    """Option for Chao Kindergarten Checks."""
    display_name = "Chao Kindergarten Checks"
    option_none = 0
    option_basics = 1
    option_full = 2
    default = 0

class ChaoRaceDifficulty(Choice):
    """Option for Chao Race Difficulty."""
    display_name = "Chao Race Difficulty"
    option_none = 0
    option_beginner = 1
    option_intermediate = 2
    option_expert = 3
    default = 0

class ChaoStadiumChecks(Choice):
    """Option for Chao Stadium Checks."""
    display_name = "Chao Stadium Checks"
    option_all = 0
    option_prize = 1
    default = 0

class ChaoStats(Range):
    """Option for Chao Stats."""
    display_name = "Chao Stats"
    range_start = 0
    range_end = 99
    default = 0

class ChaoStatsFrequency(Range):
    """Option for Chao Stats Frequency."""
    display_name = "Chao Stats Frequency"
    range_start = 1
    range_end = 20
    default = 5

class ChaoStatsHidden(Toggle):
    """Option for Chao Stats - Luck and Intelligence."""
    display_name = "Chao Stats - Luck and Intelligence"

class ChaoStatsStamina(Toggle):
    """Option for Chao Stats - Stamina."""
    display_name = "Chao Stats - Stamina"

class ConfusionTrapWeight(Choice):
    """Option for Confusion Trap Weight."""
    display_name = "Confusion Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class ControllerDriftTrapWeight(Choice):
    """Option for Controller Drift Trap Weight."""
    display_name = "Controller Drift Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class CutsceneTrapWeight(Choice):
    """Option for Cutscene Trap Weight."""
    display_name = "Cutscene Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class DeathLink(Toggle):
    """Option for Death Link."""
    display_name = "Death Link"

class EggmanMission2(DefaultOnToggle):
    """Option for Eggman Mission 2."""
    display_name = "Eggman Mission 2"

class EggmanMission3(DefaultOnToggle):
    """Option for Eggman Mission 3."""
    display_name = "Eggman Mission 3"

class EggmanMission4(DefaultOnToggle):
    """Option for Eggman Mission 4."""
    display_name = "Eggman Mission 4"

class EggmanMission5(DefaultOnToggle):
    """Option for Eggman Mission 5."""
    display_name = "Eggman Mission 5"

class EggmanMissionCount(Range):
    """Option for Eggman Mission Count."""
    display_name = "Eggman Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class EmblemPercentageForCannonsCore(Range):
    """Option for Emblem Percentage for Cannon's Core."""
    display_name = "Emblem Percentage for Cannon's Core"
    range_start = 0
    range_end = 75
    default = 50

class ExpositionTrapWeight(Choice):
    """Option for Exposition Trap Weight."""
    display_name = "Exposition Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class FishingTrapWeight(Choice):
    """Option for Fishing Trap Weight."""
    display_name = "Fishing Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class GateBossPlando(Choice):
    """Option for Boss Shuffle."""
    display_name = "Boss Shuffle"
    option_plando = 0
    default = 0

class Goal(Choice):
    """Option for Goal."""
    display_name = "Goal"
    option_biolizard = 0
    option_chaos_emerald_hunt = 1
    option_finalhazard_chaos_emerald_hunt = 2
    option_grand_prix = 3
    option_boss_rush = 4
    option_cannons_core_boss_rush = 5
    option_boss_rush_chaos_emerald_hunt = 6
    option_chaos_chao = 7
    option_minigame_madness = 8
    default = 0

class GravityTrapWeight(Choice):
    """Option for Gravity Trap Weight."""
    display_name = "Gravity Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class IceTrapWeight(Choice):
    """Option for Ice Trap Weight."""
    display_name = "Ice Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class InputSequenceTrapWeight(Choice):
    """Option for Input Sequence Trap Weight."""
    display_name = "Input Sequence Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class Itemboxsanity(Choice):
    """Option for Itemboxsanity."""
    display_name = "Itemboxsanity"
    option_none = 0
    option_extra_lives = 1
    option_all = 2
    default = 0

class JunkFillPercentage(Range):
    """Option for Junk Fill Percentage."""
    display_name = "Junk Fill Percentage"
    range_start = 0
    range_end = 100
    default = 50

class KartMission2(DefaultOnToggle):
    """Option for Kart Mission 2."""
    display_name = "Kart Mission 2"

class KartMission3(DefaultOnToggle):
    """Option for Kart Mission 3."""
    display_name = "Kart Mission 3"

class KartMission4(DefaultOnToggle):
    """Option for Kart Mission 4."""
    display_name = "Kart Mission 4"

class KartMission5(DefaultOnToggle):
    """Option for Kart Mission 5."""
    display_name = "Kart Mission 5"

class KartMissionCount(Range):
    """Option for Kart Mission Count."""
    display_name = "Kart Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class KartRaceChecks(Choice):
    """Option for Kart Race Checks."""
    display_name = "Kart Race Checks"
    option_none = 0
    option_mini = 1
    option_full = 2
    default = 0

class Keysanity(DefaultOnToggle):
    """Option for Keysanity."""
    display_name = "Keysanity"

class KnucklesMission2(DefaultOnToggle):
    """Option for Knuckles Mission 2."""
    display_name = "Knuckles Mission 2"

class KnucklesMission3(DefaultOnToggle):
    """Option for Knuckles Mission 3."""
    display_name = "Knuckles Mission 3"

class KnucklesMission4(DefaultOnToggle):
    """Option for Knuckles Mission 4."""
    display_name = "Knuckles Mission 4"

class KnucklesMission5(DefaultOnToggle):
    """Option for Knuckles Mission 5."""
    display_name = "Knuckles Mission 5"

class KnucklesMissionCount(Range):
    """Option for Knuckles Mission Count."""
    display_name = "Knuckles Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class LevelGateCosts(Choice):
    """Option for Level Gate Costs."""
    display_name = "Level Gate Costs"
    option_low = 0
    option_medium = 1
    option_high = 2
    default = 0

class LevelGateDistribution(Choice):
    """Option for Level Gate Distribution."""
    display_name = "Level Gate Distribution"
    option_early = 0
    option_even = 1
    option_late = 2
    default = 1

class LightUpPathTrapWeight(Choice):
    """Option for Light Up Path Trap Weight."""
    display_name = "Light Up Path Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class LiteratureTrapWeight(Choice):
    """Option for Literature Trap Weight."""
    display_name = "Literature Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class LogicDifficulty(Choice):
    """Option for Logic Difficulty."""
    display_name = "Logic Difficulty"
    option_standard = 0
    option_hard = 1
    option_expert = 2
    default = 0

class MathQuizTrapWeight(Choice):
    """Option for Math Quiz Trap Weight."""
    display_name = "Math Quiz Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class MaxEmblemCap(Range):
    """Option for Max Emblem Cap."""
    display_name = "Max Emblem Cap"
    range_start = 50
    range_end = 1000
    default = 180

class MinigameMadnessMinimum(Range):
    """Option for Minigame Madness Trap Minimum."""
    display_name = "Minigame Madness Trap Minimum"
    range_start = 1
    range_end = 10
    default = 5

class MinigameMadnessRequirement(Range):
    """Option for Minigame Madness Trap Requirement."""
    display_name = "Minigame Madness Trap Requirement"
    range_start = 1
    range_end = 10
    default = 3

class MinigameTrapDifficulty(Choice):
    """Option for Minigame Trap Difficulty."""
    display_name = "Minigame Trap Difficulty"
    option_easy = 0
    option_medium = 1
    option_hard = 2
    option_chaos = 3
    default = 1

class MissionShuffle(Toggle):
    """Option for Mission Shuffle."""
    display_name = "Mission Shuffle"

class MusicShuffle(Choice):
    """Option for Music Shuffle Type."""
    display_name = "Music Shuffle Type"
    option_none = 0
    option_levels = 1
    option_full = 2
    option_singularity = 3
    default = 0

class Narrator(Choice):
    """Option for Narrator."""
    display_name = "Narrator"
    option_default = 0
    option_shadow = 1
    option_rouge = 2
    option_eggman = 3
    option_maria = 4
    option_secretary = 5
    option_omochao = 6
    option_amy = 7
    option_tails = 8
    option_knuckles = 9
    option_sonic = 10
    default = 0

class NumberOfLevelGates(Range):
    """Option for Number of Level Gates."""
    display_name = "Number of Level Gates"
    range_start = 0
    range_end = 5
    default = 3

class NumberSequenceTrapWeight(Choice):
    """Option for Number Sequence Trap Weight."""
    display_name = "Number Sequence Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class OmochaoTrapWeight(Choice):
    """Option for OmoTrap Weight."""
    display_name = "OmoTrap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class Omosanity(Toggle):
    """Option for Omosanity."""
    display_name = "Omosanity"

class PinballTrapWeight(Choice):
    """Option for Pinball Trap Weight."""
    display_name = "Pinball Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class PoisonTrapWeight(Choice):
    """Option for Poison Trap Weight."""
    display_name = "Poison Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class PokemonCountTrapWeight(Choice):
    """Option for Pokemon Count Trap Weight."""
    display_name = "Pokemon Count Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class PokemonTriviaTrapWeight(Choice):
    """Option for Pokemon Trivia Trap Weight."""
    display_name = "Pokemon Trivia Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class PongTrapWeight(Choice):
    """Option for Pong Trap Weight."""
    display_name = "Pong Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class RequiredCannonsCoreMissions(Choice):
    """Option for Required Cannon's Core Missions."""
    display_name = "Required Cannon's Core Missions"
    option_first = 0
    option_all_active = 1
    default = 0

class RequiredRank(Choice):
    """Option for Required Rank."""
    display_name = "Required Rank"
    option_e = 0
    option_d = 1
    option_c = 2
    option_b = 3
    option_a = 4
    default = 0

class ReverseTrapWeight(Choice):
    """Option for Reverse Trap Weight."""
    display_name = "Reverse Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class RingLink(Toggle):
    """Option for Ring Link."""
    display_name = "Ring Link"

class RingLoss(Choice):
    """Option for Ring Loss."""
    display_name = "Ring Loss"
    option_classic = 0
    option_modern = 1
    option_ohko = 2
    default = 0

class RougeMission2(DefaultOnToggle):
    """Option for Rouge Mission 2."""
    display_name = "Rouge Mission 2"

class RougeMission3(DefaultOnToggle):
    """Option for Rouge Mission 3."""
    display_name = "Rouge Mission 3"

class RougeMission4(DefaultOnToggle):
    """Option for Rouge Mission 4."""
    display_name = "Rouge Mission 4"

class RougeMission5(DefaultOnToggle):
    """Option for Rouge Mission 5."""
    display_name = "Rouge Mission 5"

class RougeMissionCount(Range):
    """Option for Rouge Mission Count."""
    display_name = "Rouge Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class SadxMusic(Choice):
    """Option for SADX Music."""
    display_name = "SADX Music"
    option_sa2b = 0
    option_sadx = 1
    option_both = 2
    default = 0

class ShadowMission2(DefaultOnToggle):
    """Option for Shadow Mission 2."""
    display_name = "Shadow Mission 2"

class ShadowMission3(DefaultOnToggle):
    """Option for Shadow Mission 3."""
    display_name = "Shadow Mission 3"

class ShadowMission4(DefaultOnToggle):
    """Option for Shadow Mission 4."""
    display_name = "Shadow Mission 4"

class ShadowMission5(DefaultOnToggle):
    """Option for Shadow Mission 5."""
    display_name = "Shadow Mission 5"

class ShadowMissionCount(Range):
    """Option for Shadow Mission Count."""
    display_name = "Shadow Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class ShuffleStartingChaoEggs(DefaultOnToggle):
    """Option for Shuffle Starting Chao Eggs."""
    display_name = "Shuffle Starting Chao Eggs"

class SlowTrapWeight(Choice):
    """Option for Slow Trap Weight."""
    display_name = "Slow Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class SnakeTrapWeight(Choice):
    """Option for Snake Trap Weight."""
    display_name = "Snake Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class SonicMission2(DefaultOnToggle):
    """Option for Sonic Mission 2."""
    display_name = "Sonic Mission 2"

class SonicMission3(DefaultOnToggle):
    """Option for Sonic Mission 3."""
    display_name = "Sonic Mission 3"

class SonicMission4(DefaultOnToggle):
    """Option for Sonic Mission 4."""
    display_name = "Sonic Mission 4"

class SonicMission5(DefaultOnToggle):
    """Option for Sonic Mission 5."""
    display_name = "Sonic Mission 5"

class SonicMissionCount(Range):
    """Option for Sonic Mission Count."""
    display_name = "Sonic Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class TailsMission2(DefaultOnToggle):
    """Option for Tails Mission 2."""
    display_name = "Tails Mission 2"

class TailsMission3(DefaultOnToggle):
    """Option for Tails Mission 3."""
    display_name = "Tails Mission 3"

class TailsMission4(DefaultOnToggle):
    """Option for Tails Mission 4."""
    display_name = "Tails Mission 4"

class TailsMission5(DefaultOnToggle):
    """Option for Tails Mission 5."""
    display_name = "Tails Mission 5"

class TailsMissionCount(Range):
    """Option for Tails Mission Count."""
    display_name = "Tails Mission Count"
    range_start = 1
    range_end = 5
    default = 2

class TimestopTrapWeight(Choice):
    """Option for Chaos Control Trap Weight."""
    display_name = "Chaos Control Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class TinyTrapWeight(Choice):
    """Option for Tiny Trap Weight."""
    display_name = "Tiny Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class TrapFillPercentage(Range):
    """Option for Trap Fill Percentage."""
    display_name = "Trap Fill Percentage"
    range_start = 0
    range_end = 100
    default = 0

class TrapLink(Toggle):
    """Option for Trap Link."""
    display_name = "Trap Link"

class TriviaTrapWeight(Choice):
    """Option for Trivia Trap Weight."""
    display_name = "Trivia Trap Weight"
    option_none = 0
    option_low = 1
    option_medium = 2
    option_high = 4
    default = 2

class VoiceShuffle(Choice):
    """Option for Voice Shuffle Type."""
    display_name = "Voice Shuffle Type"
    option_none = 0
    option_shuffled = 1
    option_rude = 2
    option_chao = 3
    option_singularity = 4
    default = 0

class Whistlesanity(Choice):
    """Option for Whistlesanity."""
    display_name = "Whistlesanity"
    option_none = 0
    option_pipes = 1
    option_hidden = 2
    option_both = 3
    default = 0


@dataclass
class SonicAdventure2BattleWorldGenOptions(PerGameCommonOptions):
    """Options for Sonic Adventure 2 Battle WorldGen."""
    randomize_items: RandomizeItems
    use_canonical_options: UseCanonicalOptions
    animalsanity: Animalsanity
    bee_trap_weight: BeeTrapWeight
    beetlesanity: Beetlesanity
    big_fishing_difficulty: BigFishingDifficulty
    bigsanity: Bigsanity
    black_market_price_multiplier: BlackMarketPriceMultiplier
    black_market_slots: BlackMarketSlots
    black_market_unlock_costs: BlackMarketUnlockCosts
    boss_rush_shuffle: BossRushShuffle
    breakout_trap_weight: BreakoutTrapWeight
    cannons_core_mission_2: CannonsCoreMission2
    cannons_core_mission_3: CannonsCoreMission3
    cannons_core_mission_4: CannonsCoreMission4
    cannons_core_mission_5: CannonsCoreMission5
    cannons_core_mission_count: CannonsCoreMissionCount
    chao_animal_parts: ChaoAnimalParts
    chao_entrance_randomization: ChaoEntranceRandomization
    chao_karate_difficulty: ChaoKarateDifficulty
    chao_kindergarten: ChaoKindergarten
    chao_race_difficulty: ChaoRaceDifficulty
    chao_stadium_checks: ChaoStadiumChecks
    chao_stats: ChaoStats
    chao_stats_frequency: ChaoStatsFrequency
    chao_stats_hidden: ChaoStatsHidden
    chao_stats_stamina: ChaoStatsStamina
    confusion_trap_weight: ConfusionTrapWeight
    controller_drift_trap_weight: ControllerDriftTrapWeight
    cutscene_trap_weight: CutsceneTrapWeight
    death_link: DeathLink
    eggman_mission_2: EggmanMission2
    eggman_mission_3: EggmanMission3
    eggman_mission_4: EggmanMission4
    eggman_mission_5: EggmanMission5
    eggman_mission_count: EggmanMissionCount
    emblem_percentage_for_cannons_core: EmblemPercentageForCannonsCore
    exposition_trap_weight: ExpositionTrapWeight
    fishing_trap_weight: FishingTrapWeight
    gate_boss_plando: GateBossPlando
    goal: Goal
    gravity_trap_weight: GravityTrapWeight
    ice_trap_weight: IceTrapWeight
    input_sequence_trap_weight: InputSequenceTrapWeight
    itemboxsanity: Itemboxsanity
    junk_fill_percentage: JunkFillPercentage
    kart_mission_2: KartMission2
    kart_mission_3: KartMission3
    kart_mission_4: KartMission4
    kart_mission_5: KartMission5
    kart_mission_count: KartMissionCount
    kart_race_checks: KartRaceChecks
    keysanity: Keysanity
    knuckles_mission_2: KnucklesMission2
    knuckles_mission_3: KnucklesMission3
    knuckles_mission_4: KnucklesMission4
    knuckles_mission_5: KnucklesMission5
    knuckles_mission_count: KnucklesMissionCount
    level_gate_costs: LevelGateCosts
    level_gate_distribution: LevelGateDistribution
    light_up_path_trap_weight: LightUpPathTrapWeight
    literature_trap_weight: LiteratureTrapWeight
    logic_difficulty: LogicDifficulty
    math_quiz_trap_weight: MathQuizTrapWeight
    max_emblem_cap: MaxEmblemCap
    minigame_madness_minimum: MinigameMadnessMinimum
    minigame_madness_requirement: MinigameMadnessRequirement
    minigame_trap_difficulty: MinigameTrapDifficulty
    mission_shuffle: MissionShuffle
    music_shuffle: MusicShuffle
    narrator: Narrator
    number_of_level_gates: NumberOfLevelGates
    number_sequence_trap_weight: NumberSequenceTrapWeight
    omochao_trap_weight: OmochaoTrapWeight
    omosanity: Omosanity
    pinball_trap_weight: PinballTrapWeight
    poison_trap_weight: PoisonTrapWeight
    pokemon_count_trap_weight: PokemonCountTrapWeight
    pokemon_trivia_trap_weight: PokemonTriviaTrapWeight
    pong_trap_weight: PongTrapWeight
    required_cannons_core_missions: RequiredCannonsCoreMissions
    required_rank: RequiredRank
    reverse_trap_weight: ReverseTrapWeight
    ring_link: RingLink
    ring_loss: RingLoss
    rouge_mission_2: RougeMission2
    rouge_mission_3: RougeMission3
    rouge_mission_4: RougeMission4
    rouge_mission_5: RougeMission5
    rouge_mission_count: RougeMissionCount
    sadx_music: SadxMusic
    shadow_mission_2: ShadowMission2
    shadow_mission_3: ShadowMission3
    shadow_mission_4: ShadowMission4
    shadow_mission_5: ShadowMission5
    shadow_mission_count: ShadowMissionCount
    shuffle_starting_chao_eggs: ShuffleStartingChaoEggs
    slow_trap_weight: SlowTrapWeight
    snake_trap_weight: SnakeTrapWeight
    sonic_mission_2: SonicMission2
    sonic_mission_3: SonicMission3
    sonic_mission_4: SonicMission4
    sonic_mission_5: SonicMission5
    sonic_mission_count: SonicMissionCount
    tails_mission_2: TailsMission2
    tails_mission_3: TailsMission3
    tails_mission_4: TailsMission4
    tails_mission_5: TailsMission5
    tails_mission_count: TailsMissionCount
    timestop_trap_weight: TimestopTrapWeight
    tiny_trap_weight: TinyTrapWeight
    trap_fill_percentage: TrapFillPercentage
    trap_link: TrapLink
    trivia_trap_weight: TriviaTrapWeight
    voice_shuffle: VoiceShuffle
    whistlesanity: Whistlesanity
