"""
Access rules for ChecksFinder WorldGen WorldGen.

Auto-generated by world_generator.
"""

from typing import TYPE_CHECKING


from rule_builder import True_, False_, HasFromList

if TYPE_CHECKING:
    from BaseClasses import CollectionState
    from worlds.AutoWorld import World


def set_rules(world: "World") -> None:
    """Set access rules for all locations and entrances."""
    player = world.player
    multiworld = world.multiworld

    # Location rules
    world.set_rule(
        multiworld.get_location("Tile 6", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=1)
    )

    world.set_rule(
        multiworld.get_location("Tile 7", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=2)
    )

    world.set_rule(
        multiworld.get_location("Tile 8", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=3)
    )

    world.set_rule(
        multiworld.get_location("Tile 9", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=4)
    )

    world.set_rule(
        multiworld.get_location("Tile 10", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=5)
    )

    world.set_rule(
        multiworld.get_location("Tile 11", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=6)
    )

    world.set_rule(
        multiworld.get_location("Tile 12", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=7)
    )

    world.set_rule(
        multiworld.get_location("Tile 13", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=8)
    )

    world.set_rule(
        multiworld.get_location("Tile 14", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=9)
    )

    world.set_rule(
        multiworld.get_location("Tile 15", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=10)
    )

    world.set_rule(
        multiworld.get_location("Tile 16", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=11)
    )

    world.set_rule(
        multiworld.get_location("Tile 17", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=12)
    )

    world.set_rule(
        multiworld.get_location("Tile 18", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=13)
    )

    world.set_rule(
        multiworld.get_location("Tile 19", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=14)
    )

    world.set_rule(
        multiworld.get_location("Tile 20", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=15)
    )

    world.set_rule(
        multiworld.get_location("Tile 21", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=16)
    )

    world.set_rule(
        multiworld.get_location("Tile 22", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=17)
    )

    world.set_rule(
        multiworld.get_location("Tile 23", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=18)
    )

    world.set_rule(
        multiworld.get_location("Tile 24", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=19)
    )

    world.set_rule(
        multiworld.get_location("Tile 25", player),
        HasFromList('Map Width', 'Map Height', 'Map Bombs', count=20)
    )
