"""
Location definitions for Super Mario World WorldGen.

Auto-generated by world_generator.
"""

from typing import Any, Dict, Optional
from BaseClasses import Location, LocationProgressType


class SuperMarioWorldWorldGenLocation(Location):
    """Location class for Super Mario World WorldGen."""
    game: str = "Super Mario World WorldGen"


class LocationData:
    """Data container for location definitions."""

    def __init__(self, region: str, name: str, location_id: Optional[int], event: bool = False,
                 progress_type: "LocationProgressType" = None, show_in_spoiler: bool = True,
                 access: Optional[Dict[str, Any]] = None):
        self.region = region
        self.name = name
        self.location_id = location_id
        self.event = event
        self.progress_type = progress_type
        self.show_in_spoiler = show_in_spoiler
        self.access = access  # Game-specific access data (e.g., Lingo AccessRequirements)


location_table: Dict[str, LocationData] = {
    "Yoshi's Island 1 - Normal Exit": LocationData("Yoshi's Island 1 - Normal Exit", "Yoshi's Island 1 - Normal Exit", 12320768, False),
    "Yoshi's Island 2 - Normal Exit": LocationData("Yoshi's Island 2 - Normal Exit", "Yoshi's Island 2 - Normal Exit", 12320769, False),
    "Yoshi's Island 3 - Normal Exit": LocationData("Yoshi's Island 3 - Normal Exit", "Yoshi's Island 3 - Normal Exit", 12320770, False),
    "Yoshi's Island 4 - Normal Exit": LocationData("Yoshi's Island 4 - Normal Exit", "Yoshi's Island 4 - Normal Exit", 12320771, False),
    "#1 Iggy's Castle - Normal Exit": LocationData("#1 Iggy's Castle - Normal Exit", "#1 Iggy's Castle - Normal Exit", 12320772, False),
    "#1 Iggy's Castle - Boss": LocationData("#1 Iggy's Castle - Normal Exit", "#1 Iggy's Castle - Boss", 12320928, False),
    "Yellow Switch Palace": LocationData("Yellow Switch Palace", "Yellow Switch Palace", 12320773, False),
    "Donut Plains 1 - Normal Exit": LocationData("Donut Plains 1 - Normal Exit", "Donut Plains 1 - Normal Exit", 12320774, False),
    "Donut Plains 1 - Secret Exit": LocationData("Donut Plains 1 - Secret Exit", "Donut Plains 1 - Secret Exit", 12320775, False),
    "Donut Plains 2 - Normal Exit": LocationData("Donut Plains 2 - Normal Exit", "Donut Plains 2 - Normal Exit", 12320776, False),
    "Donut Plains 2 - Secret Exit": LocationData("Donut Plains 2 - Secret Exit", "Donut Plains 2 - Secret Exit", 12320777, False),
    "Donut Plains 3 - Normal Exit": LocationData("Donut Plains 3 - Normal Exit", "Donut Plains 3 - Normal Exit", 12320778, False),
    "Donut Plains 4 - Normal Exit": LocationData("Donut Plains 4 - Normal Exit", "Donut Plains 4 - Normal Exit", 12320779, False),
    "Donut Secret 1 - Normal Exit": LocationData("Donut Secret 1 - Normal Exit", "Donut Secret 1 - Normal Exit", 12320780, False),
    "Donut Secret 1 - Secret Exit": LocationData("Donut Secret 1 - Secret Exit", "Donut Secret 1 - Secret Exit", 12320781, False),
    "Donut Secret 2 - Normal Exit": LocationData("Donut Secret 2 - Normal Exit", "Donut Secret 2 - Normal Exit", 12320867, False),
    "Donut Ghost House - Normal Exit": LocationData("Donut Ghost House - Normal Exit", "Donut Ghost House - Normal Exit", 12320782, False),
    "Donut Ghost House - Secret Exit": LocationData("Donut Ghost House - Secret Exit", "Donut Ghost House - Secret Exit", 12320783, False),
    "Donut Secret House - Normal Exit": LocationData("Donut Secret House - Normal Exit", "Donut Secret House - Normal Exit", 12320784, False),
    "Donut Secret House - Secret Exit": LocationData("Donut Secret House - Secret Exit", "Donut Secret House - Secret Exit", 12320785, False),
    "#2 Morton's Castle - Normal Exit": LocationData("#2 Morton's Castle - Normal Exit", "#2 Morton's Castle - Normal Exit", 12320786, False),
    "#2 Morton's Castle - Boss": LocationData("#2 Morton's Castle - Normal Exit", "#2 Morton's Castle - Boss", 12320929, False),
    "Green Switch Palace": LocationData("Green Switch Palace", "Green Switch Palace", 12320787, False),
    "Vanilla Dome 1 - Normal Exit": LocationData("Vanilla Dome 1 - Normal Exit", "Vanilla Dome 1 - Normal Exit", 12320788, False),
    "Vanilla Dome 1 - Secret Exit": LocationData("Vanilla Dome 1 - Secret Exit", "Vanilla Dome 1 - Secret Exit", 12320789, False),
    "Vanilla Dome 2 - Normal Exit": LocationData("Vanilla Dome 2 - Normal Exit", "Vanilla Dome 2 - Normal Exit", 12320790, False),
    "Vanilla Dome 2 - Secret Exit": LocationData("Vanilla Dome 2 - Secret Exit", "Vanilla Dome 2 - Secret Exit", 12320791, False),
    "Vanilla Dome 3 - Normal Exit": LocationData("Vanilla Dome 3 - Normal Exit", "Vanilla Dome 3 - Normal Exit", 12320792, False),
    "Vanilla Dome 4 - Normal Exit": LocationData("Vanilla Dome 4 - Normal Exit", "Vanilla Dome 4 - Normal Exit", 12320793, False),
    "Vanilla Secret 1 - Normal Exit": LocationData("Vanilla Secret 1 - Normal Exit", "Vanilla Secret 1 - Normal Exit", 12320794, False),
    "Vanilla Secret 1 - Secret Exit": LocationData("Vanilla Secret 1 - Secret Exit", "Vanilla Secret 1 - Secret Exit", 12320795, False),
    "Vanilla Secret 2 - Normal Exit": LocationData("Vanilla Secret 2 - Normal Exit", "Vanilla Secret 2 - Normal Exit", 12320796, False),
    "Vanilla Secret 3 - Normal Exit": LocationData("Vanilla Secret 3 - Normal Exit", "Vanilla Secret 3 - Normal Exit", 12320797, False),
    "Vanilla Ghost House - Normal Exit": LocationData("Vanilla Ghost House - Normal Exit", "Vanilla Ghost House - Normal Exit", 12320798, False),
    "Vanilla Fortress - Normal Exit": LocationData("Vanilla Fortress - Normal Exit", "Vanilla Fortress - Normal Exit", 12320800, False),
    "Vanilla Fortress - Boss": LocationData("Vanilla Fortress - Normal Exit", "Vanilla Fortress - Boss", 12320944, False),
    "#3 Lemmy's Castle - Normal Exit": LocationData("#3 Lemmy's Castle - Normal Exit", "#3 Lemmy's Castle - Normal Exit", 12320801, False),
    "#3 Lemmy's Castle - Boss": LocationData("#3 Lemmy's Castle - Normal Exit", "#3 Lemmy's Castle - Boss", 12320930, False),
    "Red Switch Palace": LocationData("Red Switch Palace", "Red Switch Palace", 12320802, False),
    "Butter Bridge 1 - Normal Exit": LocationData("Butter Bridge 1 - Normal Exit", "Butter Bridge 1 - Normal Exit", 12320803, False),
    "Butter Bridge 2 - Normal Exit": LocationData("Butter Bridge 2 - Normal Exit", "Butter Bridge 2 - Normal Exit", 12320804, False),
    "Cheese Bridge - Normal Exit": LocationData("Cheese Bridge - Normal Exit", "Cheese Bridge - Normal Exit", 12320805, False),
    "Cheese Bridge - Secret Exit": LocationData("Cheese Bridge - Secret Exit", "Cheese Bridge - Secret Exit", 12320806, False),
    "Cookie Mountain - Normal Exit": LocationData("Cookie Mountain - Normal Exit", "Cookie Mountain - Normal Exit", 12320807, False),
    "Soda Lake - Normal Exit": LocationData("Soda Lake - Normal Exit", "Soda Lake - Normal Exit", 12320808, False),
    "#4 Ludwig's Castle - Normal Exit": LocationData("#4 Ludwig's Castle - Normal Exit", "#4 Ludwig's Castle - Normal Exit", 12320809, False),
    "#4 Ludwig's Castle - Boss": LocationData("#4 Ludwig's Castle - Normal Exit", "#4 Ludwig's Castle - Boss", 12320931, False),
    "Forest of Illusion 1 - Normal Exit": LocationData("Forest of Illusion 1 - Normal Exit", "Forest of Illusion 1 - Normal Exit", 12320810, False),
    "Forest of Illusion 1 - Secret Exit": LocationData("Forest of Illusion 1 - Secret Exit", "Forest of Illusion 1 - Secret Exit", 12320811, False),
    "Forest of Illusion 2 - Normal Exit": LocationData("Forest of Illusion 2 - Normal Exit", "Forest of Illusion 2 - Normal Exit", 12320812, False),
    "Forest of Illusion 2 - Secret Exit": LocationData("Forest of Illusion 2 - Secret Exit", "Forest of Illusion 2 - Secret Exit", 12320813, False),
    "Forest of Illusion 3 - Normal Exit": LocationData("Forest of Illusion 3 - Normal Exit", "Forest of Illusion 3 - Normal Exit", 12320814, False),
    "Forest of Illusion 3 - Secret Exit": LocationData("Forest of Illusion 3 - Secret Exit", "Forest of Illusion 3 - Secret Exit", 12320815, False),
    "Forest of Illusion 4 - Normal Exit": LocationData("Forest of Illusion 4 - Normal Exit", "Forest of Illusion 4 - Normal Exit", 12320816, False),
    "Forest of Illusion 4 - Secret Exit": LocationData("Forest of Illusion 4 - Secret Exit", "Forest of Illusion 4 - Secret Exit", 12320817, False),
    "Forest Ghost House - Normal Exit": LocationData("Forest Ghost House - Normal Exit", "Forest Ghost House - Normal Exit", 12320818, False),
    "Forest Ghost House - Secret Exit": LocationData("Forest Ghost House - Secret Exit", "Forest Ghost House - Secret Exit", 12320819, False),
    "Forest Secret - Normal Exit": LocationData("Forest Secret - Normal Exit", "Forest Secret - Normal Exit", 12320820, False),
    "Forest Fortress - Normal Exit": LocationData("Forest Fortress - Normal Exit", "Forest Fortress - Normal Exit", 12320821, False),
    "Forest Fortress - Boss": LocationData("Forest Fortress - Normal Exit", "Forest Fortress - Boss", 12320945, False),
    "#5 Roy's Castle - Normal Exit": LocationData("#5 Roy's Castle - Normal Exit", "#5 Roy's Castle - Normal Exit", 12320822, False),
    "#5 Roy's Castle - Boss": LocationData("#5 Roy's Castle - Normal Exit", "#5 Roy's Castle - Boss", 12320932, False),
    "Blue Switch Palace": LocationData("Blue Switch Palace", "Blue Switch Palace", 12320823, False),
    "Chocolate Island 1 - Normal Exit": LocationData("Chocolate Island 1 - Normal Exit", "Chocolate Island 1 - Normal Exit", 12320824, False),
    "Chocolate Island 2 - Normal Exit": LocationData("Chocolate Island 2 - Normal Exit", "Chocolate Island 2 - Normal Exit", 12320825, False),
    "Chocolate Island 2 - Secret Exit": LocationData("Chocolate Island 2 - Secret Exit", "Chocolate Island 2 - Secret Exit", 12320826, False),
    "Chocolate Island 3 - Normal Exit": LocationData("Chocolate Island 3 - Normal Exit", "Chocolate Island 3 - Normal Exit", 12320827, False),
    "Chocolate Island 3 - Secret Exit": LocationData("Chocolate Island 3 - Secret Exit", "Chocolate Island 3 - Secret Exit", 12320828, False),
    "Chocolate Island 4 - Normal Exit": LocationData("Chocolate Island 4 - Normal Exit", "Chocolate Island 4 - Normal Exit", 12320829, False),
    "Chocolate Island 5 - Normal Exit": LocationData("Chocolate Island 5 - Normal Exit", "Chocolate Island 5 - Normal Exit", 12320830, False),
    "Choco-Ghost House - Normal Exit": LocationData("Choco-Ghost House - Normal Exit", "Choco-Ghost House - Normal Exit", 12320831, False),
    "Chocolate Secret - Normal Exit": LocationData("Chocolate Secret - Normal Exit", "Chocolate Secret - Normal Exit", 12320833, False),
    "Chocolate Fortress - Normal Exit": LocationData("Chocolate Fortress - Normal Exit", "Chocolate Fortress - Normal Exit", 12320834, False),
    "Chocolate Fortress - Boss": LocationData("Chocolate Fortress - Normal Exit", "Chocolate Fortress - Boss", 12320946, False),
    "#6 Wendy's Castle - Normal Exit": LocationData("#6 Wendy's Castle - Normal Exit", "#6 Wendy's Castle - Normal Exit", 12320835, False),
    "#6 Wendy's Castle - Boss": LocationData("#6 Wendy's Castle - Normal Exit", "#6 Wendy's Castle - Boss", 12320933, False),
    "Sunken Ghost Ship - Normal Exit": LocationData("Sunken Ghost Ship - Normal Exit", "Sunken Ghost Ship - Normal Exit", 12320836, False),
    "Valley of Bowser 1 - Normal Exit": LocationData("Valley of Bowser 1 - Normal Exit", "Valley of Bowser 1 - Normal Exit", 12320837, False),
    "Valley of Bowser 2 - Normal Exit": LocationData("Valley of Bowser 2 - Normal Exit", "Valley of Bowser 2 - Normal Exit", 12320838, False),
    "Valley of Bowser 2 - Secret Exit": LocationData("Valley of Bowser 2 - Secret Exit", "Valley of Bowser 2 - Secret Exit", 12320839, False),
    "Valley of Bowser 3 - Normal Exit": LocationData("Valley of Bowser 3 - Normal Exit", "Valley of Bowser 3 - Normal Exit", 12320840, False),
    "Valley of Bowser 4 - Normal Exit": LocationData("Valley of Bowser 4 - Normal Exit", "Valley of Bowser 4 - Normal Exit", 12320841, False),
    "Valley of Bowser 4 - Secret Exit": LocationData("Valley of Bowser 4 - Secret Exit", "Valley of Bowser 4 - Secret Exit", 12320842, False),
    "Valley Ghost House - Normal Exit": LocationData("Valley Ghost House - Normal Exit", "Valley Ghost House - Normal Exit", 12320843, False),
    "Valley Ghost House - Secret Exit": LocationData("Valley Ghost House - Secret Exit", "Valley Ghost House - Secret Exit", 12320844, False),
    "Valley Fortress - Normal Exit": LocationData("Valley Fortress - Normal Exit", "Valley Fortress - Normal Exit", 12320846, False),
    "Valley Fortress - Boss": LocationData("Valley Fortress - Normal Exit", "Valley Fortress - Boss", 12320947, False),
    "#7 Larry's Castle - Normal Exit": LocationData("#7 Larry's Castle - Normal Exit", "#7 Larry's Castle - Normal Exit", 12320847, False),
    "#7 Larry's Castle - Boss": LocationData("#7 Larry's Castle - Normal Exit", "#7 Larry's Castle - Boss", 12320934, False),
    "Bowser": LocationData("Bowser - Region", "Bowser", 12321280, False),
    "Star Road 1 - Normal Exit": LocationData("Star Road 1 - Normal Exit", "Star Road 1 - Normal Exit", 12320849, False),
    "Star Road 1 - Secret Exit": LocationData("Star Road 1 - Secret Exit", "Star Road 1 - Secret Exit", 12320850, False),
    "Star Road 2 - Normal Exit": LocationData("Star Road 2 - Normal Exit", "Star Road 2 - Normal Exit", 12320851, False),
    "Star Road 2 - Secret Exit": LocationData("Star Road 2 - Secret Exit", "Star Road 2 - Secret Exit", 12320852, False),
    "Star Road 3 - Normal Exit": LocationData("Star Road 3 - Normal Exit", "Star Road 3 - Normal Exit", 12320853, False),
    "Star Road 3 - Secret Exit": LocationData("Star Road 3 - Secret Exit", "Star Road 3 - Secret Exit", 12320854, False),
    "Star Road 4 - Normal Exit": LocationData("Star Road 4 - Normal Exit", "Star Road 4 - Normal Exit", 12320855, False),
    "Star Road 4 - Secret Exit": LocationData("Star Road 4 - Secret Exit", "Star Road 4 - Secret Exit", 12320856, False),
    "Star Road 5 - Normal Exit": LocationData("Star Road 5 - Normal Exit", "Star Road 5 - Normal Exit", 12320857, False),
    "Star Road 5 - Secret Exit": LocationData("Star Road 5 - Secret Exit", "Star Road 5 - Secret Exit", 12320858, False),
    "Gnarly - Normal Exit": LocationData("Gnarly - Normal Exit", "Gnarly - Normal Exit", 12320859, False),
    "Tubular - Normal Exit": LocationData("Tubular - Normal Exit", "Tubular - Normal Exit", 12320860, False),
    "Way Cool - Normal Exit": LocationData("Way Cool - Normal Exit", "Way Cool - Normal Exit", 12320861, False),
    "Awesome - Normal Exit": LocationData("Awesome - Normal Exit", "Awesome - Normal Exit", 12320862, False),
    "Groovy - Normal Exit": LocationData("Groovy - Normal Exit", "Groovy - Normal Exit", 12320863, False),
    "Mondo - Normal Exit": LocationData("Mondo - Normal Exit", "Mondo - Normal Exit", 12320864, False),
    "Outrageous - Normal Exit": LocationData("Outrageous - Normal Exit", "Outrageous - Normal Exit", 12320865, False),
    "Funky - Normal Exit": LocationData("Funky - Normal Exit", "Funky - Normal Exit", 12320866, False),
}
