"""
Location definitions for DepGraph Vanilla WorldGen.

Auto-generated by world_generator.
"""

from typing import Any, Dict, Optional
from BaseClasses import Location, LocationProgressType


class DepGraphVanillaWorldGenLocation(Location):
    """Location class for DepGraph Vanilla WorldGen."""
    game: str = "DepGraph Vanilla WorldGen"


class LocationData:
    """Data container for location definitions."""

    def __init__(self, region: str, name: str, location_id: Optional[int], event: bool = False,
                 progress_type: "LocationProgressType" = None, show_in_spoiler: bool = True,
                 access: Optional[Dict[str, Any]] = None, extra_attributes: Optional[Dict[str, Any]] = None):
        self.region = region
        self.name = name
        self.location_id = location_id
        self.event = event
        self.progress_type = progress_type
        self.show_in_spoiler = show_in_spoiler
        self.access = access  # Game-specific access data
        self.extra_attributes = extra_attributes or {}  # Game-specific attributes


location_table: Dict[str, LocationData] = {
    "Complete Node 2": LocationData("Complete Node 2", "Complete Node 2", 234800002, False),
    "Completed Node 2": LocationData("Complete Node 2", "Completed Node 2", None, True),
    "Complete Node 3": LocationData("Complete Node 3", "Complete Node 3", 234800003, False),
    "Completed Node 3": LocationData("Complete Node 3", "Completed Node 3", None, True),
    "Complete Node 4": LocationData("Complete Node 4", "Complete Node 4", 234800004, False),
    "Completed Node 4": LocationData("Complete Node 4", "Completed Node 4", None, True),
    "Complete Node 5": LocationData("Complete Node 5", "Complete Node 5", 234800005, False),
    "Completed Node 5": LocationData("Complete Node 5", "Completed Node 5", None, True),
    "Complete Node 6": LocationData("Complete Node 6", "Complete Node 6", 234800006, False),
    "Completed Node 6": LocationData("Complete Node 6", "Completed Node 6", None, True),
    "Complete Node 7": LocationData("Complete Node 7", "Complete Node 7", 234800007, False),
    "Completed Node 7": LocationData("Complete Node 7", "Completed Node 7", None, True),
    "Complete Node 8": LocationData("Complete Node 8", "Complete Node 8", 234800008, False),
    "Completed Node 8": LocationData("Complete Node 8", "Completed Node 8", None, True),
    "Complete Node 9": LocationData("Complete Node 9", "Complete Node 9", 234800009, False),
    "Completed Node 9": LocationData("Complete Node 9", "Completed Node 9", None, True),
    "Complete Node 10": LocationData("Complete Node 10", "Complete Node 10", 234800010, False),
    "Completed Node 10": LocationData("Complete Node 10", "Completed Node 10", None, True),
}
