"""
Game options for Castlevania - Circle of the Moon WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, Range, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True

class AlwaysAllowSpeedDash(Toggle):
    """Option for Always Allow Speed Dash."""
    display_name = "Always Allow Speed Dash"

class AutoRun(Toggle):
    """Option for Auto Run."""
    display_name = "Auto Run"

class AvailableLastKeys(Range):
    """Option for Available Last Keys."""
    display_name = "Available Last Keys"
    range_start = 0
    range_end = 9
    default = 1

class BattleArenaMusic(Choice):
    """Option for Battle Arena Music."""
    display_name = "Battle Arena Music"
    option_nothing = 0
    option_requiem = 1
    option_a_vision_of_dark_secrets = 2
    option_inversion = 3
    option_awake = 4
    option_the_sinking_old_sanctuary = 5
    option_clockwork = 6
    option_shudder = 7
    option_fate_to_despair = 8
    option_aquarius = 9
    option_clockwork_mansion = 10
    option_big_battle = 11
    option_nightmare = 12
    option_vampire_killer = 13
    option_illusionary_dance = 14
    option_proof_of_blood = 15
    option_repose_of_souls = 16
    option_circle_of_the_moon = 17
    default = 0

class BuffRangedFamiliars(Toggle):
    """Option for Buff Ranged Familiars."""
    display_name = "Buff Ranged Familiars"

class BuffShooterStrength(Toggle):
    """Option for Buff Shooter Strength."""
    display_name = "Buff Shooter Strength"

class BuffSubWeapons(Toggle):
    """Option for Buff Sub-weapons."""
    display_name = "Buff Sub-weapons"

class CompletionGoal(Choice):
    """Option for Completion Goal."""
    display_name = "Completion Goal"
    option_dracula = 0
    option_battle_arena = 1
    option_battle_arena_and_dracula = 2
    default = 0

class Countdown(Choice):
    """Option for Countdown."""
    display_name = "Countdown"
    option_none = 0
    option_majors = 1
    option_all_locations = 2
    default = 0

class DeathLink(Choice):
    """Option for Death Link."""
    display_name = "Death Link"
    option_off = 0
    option_on = 1
    option_arena_on = 2
    default = 0

class DisableBattleArenaMpDrain(Toggle):
    """Option for Disable Battle Arena MP Drain."""
    display_name = "Disable Battle Arena MP Drain"

class DssPatch(Toggle):
    """Option for DSS Patch."""
    display_name = "DSS Patch"

class EarlyEscapeItem(Choice):
    """Option for Early Escape Item."""
    display_name = "Early Escape Item"
    option_none = 0
    option_double = 1
    option_roc_wing = 2
    option_double_or_roc_wing = 3
    default = 1

class HalveDssCardsPlaced(Toggle):
    """Option for Halve DSS Cards Placed."""
    display_name = "Halve DSS Cards Placed"

class IgnoreCleansing(Toggle):
    """Option for Ignore Cleansing."""
    display_name = "Ignore Cleansing"

class IronMaidenBehavior(Choice):
    """Option for Iron Maiden Behavior."""
    display_name = "Iron Maiden Behavior"
    option_vanilla = 0
    option_start_broken = 1
    option_detonator_in_pool = 2
    default = 0

class ItemDropRandomization(Choice):
    """Option for Item Drop Randomization."""
    display_name = "Item Drop Randomization"
    option_disabled = 0
    option_normal = 1
    option_tiered = 2
    default = 1

class NerfRocWing(Toggle):
    """Option for Nerf Roc Wing."""
    display_name = "Nerf Roc Wing"

class PlutoGriffinAirSpeed(Toggle):
    """Option for DSS Pluto and Griffin Run Speed in Air."""
    display_name = "DSS Pluto and Griffin Run Speed in Air"

class RequiredLastKeys(Range):
    """Option for Required Last Keys."""
    display_name = "Required Last Keys"
    range_start = 0
    range_end = 9
    default = 1

class RequiredSkirmishes(Choice):
    """Option for Required Skirmishes."""
    display_name = "Required Skirmishes"
    option_none = 0
    option_all_bosses = 1
    option_all_bosses_and_arena = 2
    default = 0

class SkipDialogues(Toggle):
    """Option for Skip Cutscene Dialogue."""
    display_name = "Skip Cutscene Dialogue"

class SkipTutorials(Toggle):
    """Option for Skip Magic Item Tutorials."""
    display_name = "Skip Magic Item Tutorials"

class SubWeaponShuffle(Toggle):
    """Option for Sub-weapon Shuffle."""
    display_name = "Sub-weapon Shuffle"


@dataclass
class CastlevaniaCircleoftheMoonWorldGenOptions(PerGameCommonOptions):
    """Options for Castlevania - Circle of the Moon WorldGen."""
    randomize_items: RandomizeItems
    always_allow_speed_dash: AlwaysAllowSpeedDash
    auto_run: AutoRun
    available_last_keys: AvailableLastKeys
    battle_arena_music: BattleArenaMusic
    buff_ranged_familiars: BuffRangedFamiliars
    buff_shooter_strength: BuffShooterStrength
    buff_sub_weapons: BuffSubWeapons
    completion_goal: CompletionGoal
    countdown: Countdown
    death_link: DeathLink
    disable_battle_arena_mp_drain: DisableBattleArenaMpDrain
    dss_patch: DssPatch
    early_escape_item: EarlyEscapeItem
    halve_dss_cards_placed: HalveDssCardsPlaced
    ignore_cleansing: IgnoreCleansing
    iron_maiden_behavior: IronMaidenBehavior
    item_drop_randomization: ItemDropRandomization
    nerf_roc_wing: NerfRocWing
    pluto_griffin_air_speed: PlutoGriffinAirSpeed
    required_last_keys: RequiredLastKeys
    required_skirmishes: RequiredSkirmishes
    skip_dialogues: SkipDialogues
    skip_tutorials: SkipTutorials
    sub_weapon_shuffle: SubWeaponShuffle
