"""
Access rules for Yoshi's Island WorldGen.

Auto-generated by world_generator using Rule Builder pattern.
The world class must inherit from RuleWorldMixin to use these rules.
"""

from typing import TYPE_CHECKING

from rule_builder import True_, False_, Has, HasAll, HasAny

if TYPE_CHECKING:
    from worlds.AutoWorld import World


def set_rules(world: "World") -> None:
    """Set access rules for all locations and entrances.

    Uses world.set_rule() from RuleWorldMixin to properly resolve Rule Builder rules.
    """
    player = world.player
    multiworld = world.multiworld

    # Entrance rules
    world.set_rule(
        multiworld.get_entrance("Overworld -> World 1", player),
        Has("World 1 Gate")
    )

    world.set_rule(
        multiworld.get_entrance("Overworld -> World 2", player),
        Has("World 2 Gate")
    )

    world.set_rule(
        multiworld.get_entrance("Overworld -> World 3", player),
        Has("World 3 Gate")
    )

    world.set_rule(
        multiworld.get_entrance("Overworld -> World 4", player),
        Has("World 4 Gate")
    )

    world.set_rule(
        multiworld.get_entrance("Overworld -> World 5", player),
        Has("World 5 Gate")
    )

    world.set_rule(
        multiworld.get_entrance("Overworld -> World 6", player),
        Has("World 6 Gate")
    )

    world.set_rule(
        multiworld.get_entrance("World 6 -> 6-8", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("1-4 -> Burt The Bashful's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("1-8 -> Salvo The Slime's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("2-4 -> Bigger Boo's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("2-8 -> Roger The Ghost's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("3-4 -> Prince Froggy's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("3-8 -> Naval Piranha's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("4-4 -> Marching Milde's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("4-8 -> Hookbill The Koopa's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("5-4 -> Sluggy The Unshaven's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("5-8 -> Raphael The Raven's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("6-4 -> Tap-Tap The Red Nose's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_entrance("6-8 -> Bowser's Room", player),
        True_()
    )
    # Location rules
    world.set_rule(
        multiworld.get_location("Make Eggs, Throw Eggs: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Make Eggs, Throw Eggs: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Make Eggs, Throw Eggs: Stars", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Make Eggs, Throw Eggs: Level Clear", player),
        Has("Beanstalk")
    )

    world.set_rule(
        multiworld.get_location("Watch Out Below!: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Watch Out Below!: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Watch Out Below!: Stars", player),
        (True_()) & (Has("Large Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("Watch Out Below!: Level Clear", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of Chomp Rock: Red Coins", player),
        Has("Chomp Rock")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of Chomp Rock: Flowers", player),
        Has("Chomp Rock")
    )

    world.set_rule(
        multiworld.get_location("Burt The Bashful's Fort: Red Coins", player),
        Has("Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Burt The Bashful's Fort: Flowers", player),
        ((True_()) | (Has("Egg Capacity Upgrade", 3))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Burt The Bashful's Fort: Stars", player),
        ((True_()) | (Has("Key"))) & (Has("Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("Burt The Bashful's Fort: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Burt The Bashful's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Hop! Hop! Donut Lifts: Stars", player),
        (True_()) | (True_())
    )

    world.set_rule(
        multiworld.get_location("Shy-Guys On Stilts: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Shy-Guys On Stilts: Flowers", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Shy-Guys On Stilts: Stars", player),
        (((True_()) & (Has("Beanstalk"))) | ((True_()) & (Has("Tulip")))) & (Has("Large Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("Shy-Guys On Stilts: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Touch Fuzzy Get Dizzy: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Touch Fuzzy Get Dizzy: Stars", player),
        ((True_()) & (HasAll())) | (True_())
    )

    world.set_rule(
        multiworld.get_location("Touch Fuzzy Get Dizzy: Gather Coins", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Salvo The Slime's Castle: Red Coins", player),
        Has("Platform Ghost")
    )

    world.set_rule(
        multiworld.get_location("Salvo The Slime's Castle: Flowers", player),
        Has("Platform Ghost")
    )

    world.set_rule(
        multiworld.get_location("Salvo The Slime's Castle: Stars", player),
        (True_()) & ((HasAll()) | (Has("Platform Ghost")))
    )

    world.set_rule(
        multiworld.get_location("Salvo The Slime's Castle: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Salvo The Slime's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Visit Koopa And Para-Koopa: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Visit Koopa And Para-Koopa: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Visit Koopa And Para-Koopa: Stars", player),
        (True_()) & (Has("Large Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("Visit Koopa And Para-Koopa: Level Clear", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("The Baseball Boys: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Baseball Boys: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Baseball Boys: Stars", player),
        ((True_()) & (Has("Tulip"))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("The Baseball Boys: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("What's Gusty Taste Like?: Red Coins", player),
        Has("! Switch")
    )

    world.set_rule(
        multiworld.get_location("What's Gusty Taste Like?: Flowers", player),
        HasAny()
    )

    world.set_rule(
        multiworld.get_location("What's Gusty Taste Like?: Level Clear", player),
        HasAny()
    )

    world.set_rule(
        multiworld.get_location("Bigger Boo's Fort: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Bigger Boo's Fort: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Bigger Boo's Fort: Stars", player),
        (True_()) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Bigger Boo's Fort: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Bigger Boo's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Watch Out For Lakitu: Red Coins", player),
        Has("Chomp Rock")
    )

    world.set_rule(
        multiworld.get_location("Watch Out For Lakitu: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Watch Out For Lakitu: Level Clear", player),
        Has("Chomp Rock")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Mystery Maze: Red Coins", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Mystery Maze: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Mystery Maze: Stars", player),
        (True_()) & (Has("Large Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Mystery Maze: Level Clear", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of the Mystery Maze: Seed Spitting Contest", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Lakitu's Wall: Red Coins", player),
        ((True_()) | (HasAny())) & (Has("Large Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("Lakitu's Wall: Flowers", player),
        ((True_()) | (Has("Giant Eggs"))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Lakitu's Wall: Stars", player),
        (True_()) & (Has("Giant Eggs"))
    )

    world.set_rule(
        multiworld.get_location("Lakitu's Wall: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Lakitu's Wall: Gather Coins", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("The Potted Ghost's Castle: Red Coins", player),
        (HasAll()) & (Has("Egg Capacity Upgrade"))
    )

    world.set_rule(
        multiworld.get_location("The Potted Ghost's Castle: Flowers", player),
        (HasAll()) & (Has("Egg Capacity Upgrade"))
    )

    world.set_rule(
        multiworld.get_location("The Potted Ghost's Castle: Stars", player),
        (True_()) & (HasAll()) & (Has("Egg Capacity Upgrade"))
    )

    world.set_rule(
        multiworld.get_location("The Potted Ghost's Castle: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Roger The Ghost's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Welcome To Monkey World!: Stars", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Jungle Rhythm...: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Jungle Rhythm...: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Jungle Rhythm...: Stars", player),
        (True_()) & (Has("Tulip"))
    )

    world.set_rule(
        multiworld.get_location("Jungle Rhythm...: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Nep-Enuts' Domain: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Nep-Enuts' Domain: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Nep-Enuts' Domain: Stars", player),
        (True_()) | (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Nep-Enuts' Domain: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Prince Froggy's Fort: Red Coins", player),
        Has("Submarine Morph")
    )

    world.set_rule(
        multiworld.get_location("Prince Froggy's Fort: Flowers", player),
        ((True_()) | (Has("Egg Capacity Upgrade", 5))) & (Has("Dashed Platform"))
    )

    world.set_rule(
        multiworld.get_location("Prince Froggy's Fort: Stars", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Prince Froggy's Fort: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Prince Froggy's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Jammin' Through The Trees: Flowers", player),
        (True_()) | (Has("Watermelon"))
    )

    world.set_rule(
        multiworld.get_location("Jammin' Through The Trees: Stars", player),
        ((True_()) & ((True_()) | (Has("Tulip")))) | ((True_()) & (Has("Tulip")))
    )

    world.set_rule(
        multiworld.get_location("The Cave Of Harry Hedgehog: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Cave Of Harry Hedgehog: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Cave Of Harry Hedgehog: Stars", player),
        (True_()) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("The Cave Of Harry Hedgehog: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Monkeys' Favorite Lake: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Monkeys' Favorite Lake: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Monkeys' Favorite Lake: Stars", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Monkeys' Favorite Lake: Level Clear", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Naval Piranha's Castle: Red Coins", player),
        (True_()) | (Has("Egg Capacity Upgrade", 3))
    )

    world.set_rule(
        multiworld.get_location("Naval Piranha's Castle: Flowers", player),
        (True_()) | (Has("Egg Capacity Upgrade", 3))
    )

    world.set_rule(
        multiworld.get_location("Naval Piranha's Castle: Stars", player),
        (True_()) & (Has("Tulip"))
    )

    world.set_rule(
        multiworld.get_location("Naval Piranha's Castle: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Naval Piranha's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("GO! GO! MARIO!!: Red Coins", player),
        Has("Super Star")
    )

    world.set_rule(
        multiworld.get_location("GO! GO! MARIO!!: Flowers", player),
        Has("Super Star")
    )

    world.set_rule(
        multiworld.get_location("GO! GO! MARIO!!: Stars", player),
        ((True_()) & (Has("Tulip"))) | (True_())
    )

    world.set_rule(
        multiworld.get_location("GO! GO! MARIO!!: Level Clear", player),
        Has("Super Star")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Lakitus: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Lakitus: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Lakitus: Stars", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Lakitus: Level Clear", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Don't Look Back!: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Don't Look Back!: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Don't Look Back!: Stars", player),
        ((True_()) & (Has("Tulip"))) & (Has("! Switch"))
    )

    world.set_rule(
        multiworld.get_location("Don't Look Back!: Level Clear", player),
        Has("! Switch")
    )

    world.set_rule(
        multiworld.get_location("Marching Milde's Fort: Red Coins", player),
        ((True_()) | (Has("Egg Capacity Upgrade"))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Marching Milde's Fort: Flowers", player),
        ((True_()) | (Has("Egg Capacity Upgrade"))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Marching Milde's Fort: Stars", player),
        ((True_()) | (True_()) | (Has("Vanishing Arrow Wheel"))) & (Has("Dashed Stairs"))
    )

    world.set_rule(
        multiworld.get_location("Marching Milde's Fort: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Marching Milde's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Chomp Rock Zone: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Chomp Rock Zone: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Chomp Rock Zone: Stars", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Lake Shore Paradise: Red Coins", player),
        ((True_()) | (Has("Egg Plant"))) & (HasAny())
    )

    world.set_rule(
        multiworld.get_location("Lake Shore Paradise: Flowers", player),
        ((True_()) | (Has("Egg Plant"))) & (HasAny())
    )

    world.set_rule(
        multiworld.get_location("Lake Shore Paradise: Stars", player),
        (((True_()) & (Has("Tulip"))) | (True_())) & ((True_()) | (Has("Egg Plant")))
    )

    world.set_rule(
        multiworld.get_location("Lake Shore Paradise: Level Clear", player),
        (True_()) | (Has("Egg Plant"))
    )

    world.set_rule(
        multiworld.get_location("Ride Like The Wind: Red Coins", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Ride Like The Wind: Flowers", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Ride Like The Wind: Stars", player),
        ((True_()) & (Has("Helicopter Morph"))) & (Has("Large Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("Ride Like The Wind: Level Clear", player),
        Has("Large Spring Ball")
    )

    world.set_rule(
        multiworld.get_location("Ride Like The Wind: Gather Coins", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Hookbill The Koopa's Castle: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Hookbill The Koopa's Castle: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Hookbill The Koopa's Castle: Stars", player),
        (True_()) & (HasAny())
    )

    world.set_rule(
        multiworld.get_location("Hookbill The Koopa's Castle: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Hookbill The Koopa's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("BLIZZARD!!!: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("BLIZZARD!!!: Stars", player),
        (True_()) | (((True_()) & (Has("Dashed Stairs"))) | (Has("Tulip")))
    )

    world.set_rule(
        multiworld.get_location("Ride The Ski Lifts: Stars", player),
        (True_()) | (Has("Super Star"))
    )

    world.set_rule(
        multiworld.get_location("Danger - Icy Conditions Ahead: Red Coins", player),
        ((True_()) | (Has("Fire Melon"))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Danger - Icy Conditions Ahead: Flowers", player),
        ((True_()) | (Has("Fire Melon"))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Danger - Icy Conditions Ahead: Stars", player),
        ((True_()) & ((True_()) | (Has("Fire Melon")))) & (Has("Spring Ball"))
    )

    world.set_rule(
        multiworld.get_location("Danger - Icy Conditions Ahead: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Sluggy The Unshaven's Fort: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Sluggy The Unshaven's Fort: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Sluggy The Unshaven's Fort: Stars", player),
        ((True_()) & (Has("Dashed Platform")) & (Has("Dashed Stairs"))) | ((True_()) & (HasAll()))
    )

    world.set_rule(
        multiworld.get_location("Sluggy The Unshaven's Fort: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Sluggy The Unshaven's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Goonie Rides!: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Goonie Rides!: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Goonie Rides!: Stars", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Goonie Rides!: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Welcome To Cloud World: Stars", player),
        (True_()) | (Has("Tulip"))
    )

    world.set_rule(
        multiworld.get_location("Shifting Platforms Ahead: Red Coins", player),
        (True_()) | (Has("Egg Capacity Upgrade"))
    )

    world.set_rule(
        multiworld.get_location("Shifting Platforms Ahead: Flowers", player),
        (True_()) | (Has("Egg Capacity Upgrade"))
    )

    world.set_rule(
        multiworld.get_location("Shifting Platforms Ahead: Stars", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Raphael The Raven's Castle: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Raphael The Raven's Castle: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Raphael The Raven's Castle: Stars", player),
        (True_()) & (Has("Arrow Wheel"))
    )

    world.set_rule(
        multiworld.get_location("Raphael The Raven's Castle: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Raphael The Raven's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Scary Skeleton Goonies!: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Scary Skeleton Goonies!: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("Scary Skeleton Goonies!: Stars", player),
        (True_()) & (Has("Dashed Platform"))
    )

    world.set_rule(
        multiworld.get_location("Scary Skeleton Goonies!: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Bandits: Red Coins", player),
        Has("Super Star")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Bandits: Flowers", player),
        Has("Super Star")
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Bandits: Stars", player),
        (True_()) | (True_())
    )

    world.set_rule(
        multiworld.get_location("The Cave Of The Bandits: Level Clear", player),
        Has("Super Star")
    )

    world.set_rule(
        multiworld.get_location("Tap-Tap The Red Nose's Fort: Red Coins", player),
        ((True_()) | (Has("Egg Capacity Upgrade", 3))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Tap-Tap The Red Nose's Fort: Flowers", player),
        ((True_()) | (Has("Egg Capacity Upgrade", 3))) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Tap-Tap The Red Nose's Fort: Stars", player),
        (True_()) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("Tap-Tap The Red Nose's Fort: Level Clear", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("Tap-Tap The Red Nose's Boss Room", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("The Very Loooooong Cave: Red Coins", player),
        ((True_()) | (Has("Egg Capacity Upgrade", 3))) & (Has("Chomp Rock"))
    )

    world.set_rule(
        multiworld.get_location("The Very Loooooong Cave: Flowers", player),
        ((True_()) | (Has("Egg Capacity Upgrade", 3))) & (Has("Chomp Rock"))
    )

    world.set_rule(
        multiworld.get_location("The Very Loooooong Cave: Stars", player),
        (True_()) & ((True_()) | (Has("Egg Capacity Upgrade", 3))) & (Has("Chomp Rock"))
    )

    world.set_rule(
        multiworld.get_location("The Deep, Underground Maze: Red Coins", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Deep, Underground Maze: Flowers", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("The Deep, Underground Maze: Stars", player),
        ((True_()) & (HasAll())) | (HasAll())
    )

    world.set_rule(
        multiworld.get_location("The Deep, Underground Maze: Level Clear", player),
        HasAll()
    )

    world.set_rule(
        multiworld.get_location("KEEP MOVING!!!!: Red Coins", player),
        (True_()) | (Has("Egg Capacity Upgrade"))
    )

    world.set_rule(
        multiworld.get_location("KEEP MOVING!!!!: Flowers", player),
        Has("Egg Plant")
    )

    world.set_rule(
        multiworld.get_location("KEEP MOVING!!!!: Stars", player),
        True_()
    )

    world.set_rule(
        multiworld.get_location("King Bowser's Castle: Red Coins", player),
        (True_()) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("King Bowser's Castle: Flowers", player),
        (True_()) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("King Bowser's Castle: Stars", player),
        (True_()) & (HasAll())
    )

    world.set_rule(
        multiworld.get_location("King Bowser's Castle: Level Clear", player),
        True_()
    )
