"""
Item definitions for Faxanadu WorldGen.

Auto-generated by world_generator.
"""

from typing import Dict, Optional
from BaseClasses import ItemClassification, Item


class FaxanaduWorldGenItem(Item):
    """Item class for Faxanadu WorldGen."""
    game: str = "Faxanadu WorldGen"


class ItemData:
    """Data container for item definitions."""

    def __init__(self, item_id: Optional[int], classification: ItemClassification, classification_counts: Optional[Dict[str, int]] = None):
        self.id = item_id
        self.classification = classification
        self.classification_counts = classification_counts


item_table: Dict[str, ItemData] = {
    "Progressive Sword": ItemData(400000, ItemClassification.progression, None),
    "Progressive Armor": ItemData(400001, ItemClassification.progression, None),
    "Progressive Shield": ItemData(400002, ItemClassification.useful, None),
    "Spring Elixir": ItemData(400003, ItemClassification.progression, None),
    "Mattock": ItemData(400004, ItemClassification.progression, None),
    "Unlock Wingboots": ItemData(400005, ItemClassification.progression, None),
    "Key Jack": ItemData(400006, ItemClassification.progression, None),
    "Key Queen": ItemData(400007, ItemClassification.progression, None),
    "Key King": ItemData(400008, ItemClassification.progression, None),
    "Key Joker": ItemData(400009, ItemClassification.progression, None),
    "Key Ace": ItemData(400010, ItemClassification.progression, None),
    "Ring of Ruby": ItemData(400011, ItemClassification.progression, None),
    "Ring of Dworf": ItemData(400012, ItemClassification.progression, None),
    "Demons Ring": ItemData(400013, ItemClassification.progression, None),
    "Black Onyx": ItemData(400014, ItemClassification.progression, None),
    "Deluge": ItemData(400015, ItemClassification.progression, None),
    "Thunder": ItemData(400016, ItemClassification.useful, None),
    "Fire": ItemData(400017, ItemClassification.useful, None),
    "Death": ItemData(400018, ItemClassification.useful, None),
    "Tilte": ItemData(400019, ItemClassification.useful, None),
    "Ring of Elf": ItemData(400020, ItemClassification.useful, None),
    "Magical Rod": ItemData(400021, ItemClassification.useful, None),
    "Pendant": ItemData(400022, ItemClassification.useful, None),
    "Hourglass": ItemData(400023, ItemClassification.filler, None),
    "Red Potion": ItemData(400024, ItemClassification.progression, {"filler": 31, "progression": 4}),
    "Elixir": ItemData(400025, ItemClassification.filler, None),
    "Glove": ItemData(400026, ItemClassification.filler, None),
    "Ointment": ItemData(400027, ItemClassification.filler, None),
    "Poison": ItemData(400028, ItemClassification.trap, None),
    "Wingboots": ItemData(400029, ItemClassification.useful, None),
    "Sky Spring Flow": ItemData(None, ItemClassification.progression, None),
    "Joker Spring Flow": ItemData(None, ItemClassification.progression, None),
    "Tower of Fortress Spring Flow": ItemData(None, ItemClassification.progression, None),
    "Killed Evil One": ItemData(None, ItemClassification.progression, None),
}
