"""
Game options for Faxanadu WorldGen.

Auto-generated by world_generator.
"""

from dataclasses import dataclass
from Options import Choice, DefaultOnToggle, StartInventoryPool, Toggle, PerGameCommonOptions


class RandomizeItems(Toggle):
    """Enable item randomization.

    When disabled, items will be placed in their original locations.
    """
    display_name = "Randomize Items"
    default = True


class UseCanonicalOptions(Toggle):
    """Use canonical options for seed 1.

    When enabled and generating seed 1, options will be loaded from the
    _worldgen_settings.json file to reproduce the exact original seed.
    This ensures deterministic output matching the original world export.
    """
    display_name = "Use Canonical Options"
    default = True

class IncludePendant(Toggle):
    """Option for Include Pendant."""
    display_name = "Include Pendant"

class IncludePoisons(DefaultOnToggle):
    """Option for Include Poisons."""
    display_name = "Include Poisons"

class KeepShopRedPotions(Toggle):
    """Option for Keep Shop Red Potions."""
    display_name = "Keep Shop Red Potions"

class RandomMonsters(Choice):
    """Option for Random Monsters."""
    display_name = "Random Monsters"
    option_vanilla = 0
    option_level_shuffle = 1
    option_level_random = 2
    option_world_shuffle = 3
    option_world_random = 4
    option_chaotic = 5
    default = 0

class RandomMusics(Toggle):
    """Option for Random Musics."""
    display_name = "Random Musics"

class RandomNpcs(Toggle):
    """Option for Random NPCs."""
    display_name = "Random NPCs"

class RandomRewards(Toggle):
    """Option for Random Rewards."""
    display_name = "Random Rewards"

class RandomSounds(Toggle):
    """Option for Random Sounds."""
    display_name = "Random Sounds"

class RequireDragonSlayer(Toggle):
    """Option for Require Dragon Slayer."""
    display_name = "Require Dragon Slayer"

class StartInventoryFromPool(StartInventoryPool):
    """Start inventory from pool for Start Inventory from Pool."""


@dataclass
class FaxanaduWorldGenOptions(PerGameCommonOptions):
    """Options for Faxanadu WorldGen."""
    randomize_items: RandomizeItems
    use_canonical_options: UseCanonicalOptions
    include_pendant: IncludePendant
    include_poisons: IncludePoisons
    keep_shop_red_potions: KeepShopRedPotions
    random_monsters: RandomMonsters
    random_musics: RandomMusics
    random_npcs: RandomNpcs
    random_rewards: RandomRewards
    random_sounds: RandomSounds
    require_dragon_slayer: RequireDragonSlayer
    start_inventory_from_pool: StartInventoryFromPool
